import "server-only";
import { NextResponse } from "next/server";
import { resolveIdentityEnterprise,type IdentityEnterpriseRole } from "@/lib/identity-signals/enterprise-context";

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export class TrustArchitectureApiError extends Error{constructor(message:string,readonly status:number,readonly code:string){super(message);}}
export function architectureCorrelationId(request?:Request){const value=request?.headers.get("x-correlation-id")?.trim();return value&&uuid.test(value)?value:crypto.randomUUID();}
export function architectureResponse(body:Record<string,unknown>,status:number,correlationId:string){return NextResponse.json({schemaVersion:"enterprise-trust-architecture-v1",generatedAt:new Date().toISOString(),correlationId,...body},{status,headers:{"cache-control":"private, no-store","x-correlation-id":correlationId}});}
export function architectureFailure(error:unknown,correlationId:string){const candidate=error as Error&{status?:number;code?:string};const status=candidate.status??500;if(status>=500)console.error("Trust Architecture API failed safely.",{code:candidate.code??"TRUST_ARCHITECTURE_API_FAILED"});return architectureResponse({ok:false,code:candidate.code??"TRUST_ARCHITECTURE_API_FAILED",error:status<500?candidate.message:"Trust Architecture operation failed safely."},status,correlationId);}
export async function architectureContext(request:Request,roles:IdentityEnterpriseRole[]=["owner","admin","reviewer","observer"]){try{return await resolveIdentityEnterprise(request,roles);}catch(error){const candidate=error as Error&{status?:number;code?:string};throw new TrustArchitectureApiError(candidate.message,candidate.status??500,candidate.code??"ENTERPRISE_CONTEXT_FAILED");}}
export function assertArchitectureMutation(request:Request){const type=(request.headers.get("content-type")??"").split(";",1)[0].trim().toLowerCase();if(type!=="application/json")throw new TrustArchitectureApiError("application/json is required.",415,"UNSUPPORTED_CONTENT_TYPE");if(Number(request.headers.get("content-length")??0)>64_000)throw new TrustArchitectureApiError("Request is too large.",413,"PAYLOAD_TOO_LARGE");const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new TrustArchitectureApiError("Cross-site mutation denied.",403,"CSRF_ORIGIN_DENIED");if(request.headers.get("sec-fetch-site")==="cross-site")throw new TrustArchitectureApiError("Cross-site mutation denied.",403,"CSRF_SITE_DENIED");if(process.env.NODE_ENV==="production"&&!origin)throw new TrustArchitectureApiError("Mutation origin is required.",403,"CSRF_ORIGIN_REQUIRED");}
export function architectureReference(value:unknown,name:string){const result=typeof value==="string"?value.trim():"";if(!/^[A-Za-z0-9_.:@-]{1,160}$/.test(result))throw new TrustArchitectureApiError(`${name} is invalid.`,400,"REFERENCE_INVALID");return result;}
