import "server-only";
import { createServiceRoleClient } from "@/lib/supabase/service-role";
import { safeGraphMetadata,type EvidenceGraph } from "./evidence-graph.ts";
import { insufficientKpi,trustKpiKeys,type TrustKpi } from "./kpis.ts";
import type { CanonicalTrustEvent } from "../trust-events/types.ts";
import type { TrustPolicyVersion } from "../trust-policy/policy-types.ts";

function failure(operation:string,error:unknown):never{console.error(`${operation} failed.`,{code:(error as {code?:string})?.code});throw Object.assign(new Error(`${operation} failed safely.`),{status:500,code:"TRUST_ARCHITECTURE_PERSISTENCE_FAILED"});}
function rows<T>(result:{data:T[]|null;error:unknown},operation:string):T[]{if(result.error)failure(operation,result.error);return result.data??[];}

export function trustArchitectureRepository(){const db=createServiceRoleClient();return {
  async domains(){const result=await db.from("trust_domain_versions").select("domain_key,version,display_name,description,active,effective_at").eq("active",true).order("domain_key");return rows(result,"Trust domains");},
  async overview(enterpriseId:string){const tables=["trust_subjects","evidence_objects","trust_state_decisions","trust_policy_versions","evidence_graph_nodes","evidence_graph_edges","trust_simulations"] as const;const values=await Promise.all(tables.map(async table=>{let query=db.from(table).select("*",{count:"exact",head:true});if(table!=="trust_policy_versions")query=query.eq("enterprise_id",enterpriseId);else query=query.or(`enterprise_id.is.null,enterprise_id.eq.${enterpriseId}`);const result=await query;if(result.error)failure(`Architecture overview ${table}`,result.error);return [table,result.count??0] as const;}));return Object.fromEntries(values);},
  async health(enterpriseId:string){const [domains,overview]=await Promise.all([this.domains(),this.overview(enterpriseId)]);return {status:domains.length===10?"OPERATIONAL":"DEGRADED",domainRegistry:{status:domains.length===10?"OPERATIONAL":"DEGRADED",count:domains.length},stateEngine:{status:Number(overview.trust_state_decisions)>0?"EVIDENCE_AVAILABLE":"INSUFFICIENT_DATA",decisionCount:Number(overview.trust_state_decisions)},evidenceGraph:{status:Number(overview.evidence_graph_nodes)>0?"EVIDENCE_AVAILABLE":"INSUFFICIENT_DATA",nodeCount:Number(overview.evidence_graph_nodes),edgeCount:Number(overview.evidence_graph_edges)},measuredAt:new Date().toISOString()};},
  async kpis(enterpriseId:string):Promise<TrustKpi[]>{const result=await db.from("trust_kpi_snapshots").select("metric_key,metric_value,metric_status,numerator,denominator,evidence_hash,measured_at").eq("enterprise_id",enterpriseId).order("measured_at",{ascending:false});if(result.error)failure("Trust KPI snapshots",result.error);const latest=new Map<string,Record<string,unknown>>();for(const row of result.data??[])if(!latest.has(String(row.metric_key)))latest.set(String(row.metric_key),row as Record<string,unknown>);const now=new Date().toISOString();return trustKpiKeys.map((metricKey)=>{const row=latest.get(metricKey);return row?{metricKey,status:String(row.metric_status) as TrustKpi["status"],value:row.metric_value===null?null:Number(row.metric_value),numerator:row.numerator===null?null:Number(row.numerator),denominator:row.denominator===null?null:Number(row.denominator),evidenceHash:String(row.evidence_hash),measuredAt:String(row.measured_at)}:insufficientKpi(metricKey,now);});},
  async subject(enterpriseId:string,subjectId:string){const [subject,state]=await Promise.all([db.from("trust_subjects").select("domain_key,subject_id,subject_type,display_label,created_at,retired_at").eq("enterprise_id",enterpriseId).eq("subject_id",subjectId).maybeSingle(),db.from("subject_trust_state").select("domain_key,subject_id,workflow_id,state,confidence,current_decision_id,current_state_decision_id,updated_at").eq("enterprise_id",enterpriseId).eq("subject_id",subjectId).maybeSingle()]);if(subject.error)failure("Trust subject",subject.error);if(state.error)failure("Subject state",state.error);return subject.data||state.data?{subject:subject.data,state:state.data}:null;},
  async timeline(enterpriseId:string,subjectId:string){const [decisions,memory]=await Promise.all([db.from("trust_state_decisions").select("state_decision_id,decision_contract_id,domain_key,prior_state,next_state,recommendation_id,policy_id,policy_version,decision_hash,decided_at,reason_codes").eq("enterprise_id",enterpriseId).eq("subject_id",subjectId).order("decided_at",{ascending:true}).limit(500),db.from("trust_memory_index").select("memory_id,memory_type,source_id,occurred_at,summary").eq("enterprise_id",enterpriseId).eq("subject_id",subjectId).order("occurred_at",{ascending:true}).limit(500)]);return {stateDecisions:rows(decisions,"Subject state timeline"),memory:rows(memory,"Subject Trust Memory")};},
  async graph(enterpriseId:string,subjectId:string,limit:number):Promise<EvidenceGraph>{const root=await db.from("evidence_graph_nodes").select("node_id").eq("enterprise_id",enterpriseId).eq("external_id",subjectId).limit(1).maybeSingle();if(root.error)failure("Evidence Graph root",root.error);if(!root.data)return {rootNodeId:null,nodes:[],edges:[],depth:1,truncated:false};const rootId=String(root.data.node_id);const edgeResult=await db.from("evidence_graph_edges").select("edge_id,enterprise_id,from_node_id,to_node_id,edge_type,evidence_id,created_at").eq("enterprise_id",enterpriseId).or(`from_node_id.eq.${rootId},to_node_id.eq.${rootId}`).order("created_at").limit(limit+1);const rawEdges=rows(edgeResult,"Evidence Graph edges");const selected=rawEdges.slice(0,limit);const ids=[...new Set([rootId,...selected.flatMap((edge)=>[String(edge.from_node_id),String(edge.to_node_id)])])];const nodeResult=await db.from("evidence_graph_nodes").select("node_id,enterprise_id,node_type,external_id,domain_key,label,metadata,created_at").eq("enterprise_id",enterpriseId).in("node_id",ids);const rawNodes=rows(nodeResult,"Evidence Graph nodes");return {rootNodeId:rootId,depth:1,truncated:rawEdges.length>limit,nodes:rawNodes.map((node)=>({nodeId:String(node.node_id),enterpriseId:String(node.enterprise_id),nodeType:String(node.node_type),externalId:String(node.external_id),domainKey:node.domain_key?String(node.domain_key):null,label:node.label?String(node.label):null,metadata:safeGraphMetadata(node.metadata),createdAt:String(node.created_at)})),edges:selected.map((edge)=>({edgeId:String(edge.edge_id),enterpriseId:String(edge.enterprise_id),fromNodeId:String(edge.from_node_id),toNodeId:String(edge.to_node_id),edgeType:String(edge.edge_type) as never,evidenceId:edge.evidence_id?String(edge.evidence_id):null,createdAt:String(edge.created_at)}))};},
  async decision(enterpriseId:string,decisionId:string){const [recommendation,stateDecision]=await Promise.all([db.from("consensus_decisions").select("decision_json").eq("enterprise_id",enterpriseId).eq("decision_id",decisionId).maybeSingle(),db.from("trust_state_decisions").select("*,trust_decision_contracts(*)").eq("enterprise_id",enterpriseId).eq("recommendation_id",decisionId).maybeSingle()]);if(recommendation.error)failure("Consensus recommendation",recommendation.error);if(stateDecision.error)failure("Trust state decision",stateDecision.error);return recommendation.data||stateDecision.data?{recommendation:recommendation.data?.decision_json??null,stateDecision:stateDecision.data??null}:null;},
  async replayInputs(enterpriseId:string,decisionId:string){const decision=await this.decision(enterpriseId,decisionId);if(!decision)return null;const recommendation=decision.recommendation as Record<string,unknown>|null;const evaluatedAt=String(recommendation?.evaluatedAt??new Date(0).toISOString());const [evidence,health,policies,consent]=await Promise.all([db.from("provider_observations").select("observation_id,provider_key,result,assurance,quality,signature_verified,server_verified,evidence_digest,occurred_at,received_at,expires_at,reason_codes").eq("enterprise_id",enterpriseId).lte("received_at",evaluatedAt),db.from("provider_health_snapshots").select("provider_key,state,observed_at,reason_codes").eq("enterprise_id",enterpriseId).lte("observed_at",evaluatedAt),db.from("trust_policy_versions").select("policy_id,version,layer,rules,valid_from,valid_until").or(`enterprise_id.is.null,enterprise_id.eq.${enterpriseId}`).lte("valid_from",evaluatedAt),db.from("consent_receipts").select("receipt_id,policy_version,consent_action,categories,occurred_at,expires_at,receipt_hash").eq("enterprise_id",enterpriseId).lte("received_at",evaluatedAt)]);return {decision,evaluatedAt,evidence:rows(evidence,"Replay evidence"),providerHealth:rows(health,"Replay health"),policies:rows(policies,"Replay policies"),consent:rows(consent,"Replay consent")};},
  async policies(enterpriseId:string){const result=await db.from("trust_policy_versions").select("policy_version_id,enterprise_id,policy_id,version,layer,domain_key,workflow_id,authority_id,active,valid_from,valid_until,rules,policy_hash,created_at").or(`enterprise_id.is.null,enterprise_id.eq.${enterpriseId}`).order("valid_from",{ascending:false});return rows(result,"Trust policies");},
  async policyGovernanceEvents(enterpriseId:string,policyId:string){const result=await db.from("enterprise_policy_governance_events").select("event_id,enterprise_id,policy_version_id,previous_state,next_state,actor_id,reviewer_id,reason,approval_evidence,authority_reference,replay_reference,rollback_policy_version_id,correlation_id,created_at,trust_policy_versions!inner(policy_id,version)").eq("enterprise_id",enterpriseId).eq("trust_policy_versions.policy_id",policyId).order("created_at",{ascending:false});return rows(result,"Policy governance history");},
  async persistPolicyGovernance(input:{enterpriseId:string;policyVersionId:string;previousState:string;nextState:string;actorId:string;reviewerId:string|null;reason:string;approvalEvidence:string[];authorityReference:string;replayReference:string;rollbackPolicyVersionId:string|null;correlationId:string}){const result=await db.rpc("record_enterprise_policy_governance_event_v1",{p_enterprise_id:input.enterpriseId,p_policy_version_id:input.policyVersionId,p_previous_state:input.previousState,p_next_state:input.nextState,p_actor_id:input.actorId,p_reviewer_id:input.reviewerId,p_reason:input.reason,p_approval_evidence:input.approvalEvidence,p_authority_reference:input.authorityReference,p_replay_reference:input.replayReference,p_rollback_policy_version_id:input.rollbackPolicyVersionId,p_correlation_id:input.correlationId});if(result.error)failure("Policy governance event",result.error);return result.data;},
  async persistPolicy(enterpriseId:string,actorId:string,policy:TrustPolicyVersion,policyHash:string,event:CanonicalTrustEvent,correlationId:string){const result=await db.rpc("create_trust_policy_version_v1",{p_enterprise_id:enterpriseId,p_actor_id:actorId,p_policy:policy,p_policy_hash:policyHash,p_trust_event:event,p_correlation_id:correlationId});if(result.error)failure("Trust policy version",result.error);return result.data;},
  async persistSimulation(input:{simulationId:string;enterpriseId:string;simulationType:string;subjectId:string|null;decisionId:string|null;inputHash:string;requestedBy:string;requestedAt:string;resultHash:string;result:Record<string,unknown>;correlationId:string}){const response=await db.rpc("persist_trust_simulation_v1",{p_simulation:input,p_result:input.result,p_correlation_id:input.correlationId});if(response.error)failure("Trust simulation",response.error);return response.data;},
  async simulation(enterpriseId:string,simulationId:string){const result=await db.from("trust_simulations").select("*,trust_simulation_results(*)").eq("enterprise_id",enterpriseId).eq("simulation_id",simulationId).maybeSingle();if(result.error)failure("Trust simulation",result.error);return result.data;},
};}
