import "server-only";
import { hashCanonical,deterministicUuid } from "../trust-core/hash.ts";
import { buildReplayArtifact,replayModes,type ReplayMode } from "./replay.ts";
import { trustArchitectureRepository } from "./repository.ts";
import { validatePolicyVersion } from "../trust-policy/policy-validation.ts";
import { signTrustEvent } from "../trust-events/hash.ts";
import { TRUST_EVENT_CANONICALIZATION,TRUST_EVENT_HASH_ALGORITHM,TRUST_EVENT_SCHEMA_VERSION } from "../trust-events/types.ts";
import { consensusRepository } from "../consensus/repository.ts";

export async function createTrustPolicy(input:{enterpriseId:string;actorId:string;value:unknown;correlationId:string;expectedPolicyId?:string}){const policy=validatePolicyVersion(input.value);if(input.expectedPolicyId&&policy.policyId!==input.expectedPolicyId)throw Object.assign(new Error("Policy path and body do not match."),{status:400,code:"POLICY_ID_MISMATCH"});if(policy.layer==="PLATFORM_DEFAULT")throw Object.assign(new Error("Tenant administrators cannot create platform defaults."),{status:403,code:"PLATFORM_POLICY_FORBIDDEN"});policy.enterpriseId=input.enterpriseId;const policyHash=hashCanonical(policy as unknown as Record<string,unknown>);const head=await consensusRepository().chainHead(input.enterpriseId);const now=new Date().toISOString();const event=signTrustEvent({eventId:crypto.randomUUID(),enterpriseId:input.enterpriseId,schemaVersion:TRUST_EVENT_SCHEMA_VERSION,eventType:"governance.trust_policy.changed",subject:{type:"ORGANIZATION",id:`enterprise:${input.enterpriseId}`},actor:{type:"ADMINISTRATOR",id:input.actorId},workflow:policy.workflowId?{type:"WORKFLOW",id:policy.workflowId}:null,session:null,authority:policy.authorityId?{type:"AUTHORITY",id:policy.authorityId}:null,provider:{key:"cyber_sentinels_trust_policy",protocol:"UNSIGNED",serverVerified:true,eventId:policy.policyId,transactionId:input.correlationId,deliveryId:null},normalizedFacts:{policyId:policy.policyId,policyVersion:policy.version,layer:policy.layer,policyHash},reasonCodes:["TRUST_POLICY_VERSION_CREATED"],evidenceReferences:[],occurredAt:now,receivedAt:now,sequence:head.sequence+1,previousHash:head.eventHash,canonicalization:TRUST_EVENT_CANONICALIZATION,hashAlgorithm:TRUST_EVENT_HASH_ALGORITHM,ordering:{late:false,supersedesEventId:null,providerSequence:null}});return trustArchitectureRepository().persistPolicy(input.enterpriseId,input.actorId,policy,policyHash,event,input.correlationId);}

export async function createTrustSimulation(input:{enterpriseId:string;actorId:string;value:unknown;correlationId:string}){if(!input.value||typeof input.value!=="object"||Array.isArray(input.value))throw Object.assign(new Error("Simulation request must be an object."),{status:400,code:"SIMULATION_INVALID"});const row=input.value as Record<string,unknown>;const mode=String(row.mode??"") as ReplayMode;if(!replayModes.includes(mode))throw Object.assign(new Error("Simulation mode is unsupported."),{status:400,code:"SIMULATION_MODE_INVALID"});const decisionId=typeof row.decisionId==="string"?row.decisionId:null;const subjectId=typeof row.subjectId==="string"?row.subjectId:null;if(!decisionId&&!subjectId)throw Object.assign(new Error("Simulation requires a decisionId or subjectId."),{status:400,code:"SIMULATION_TARGET_REQUIRED"});const historicalInputs=decisionId?await trustArchitectureRepository().replayInputs(input.enterpriseId,decisionId):{subjectId};if(!historicalInputs)throw Object.assign(new Error("Simulation decision was not found."),{status:404,code:"DECISION_NOT_FOUND"});const overrides=row.overrides&&typeof row.overrides==="object"&&!Array.isArray(row.overrides)?row.overrides as Record<string,unknown>:{};const artifact=buildReplayArtifact({mode,enterpriseId:input.enterpriseId,decisionId:decisionId??`subject:${subjectId}`,historicalInputs:historicalInputs as unknown as Record<string,unknown>,simulationOverrides:overrides});const requestedAt=new Date().toISOString();const inputHash=hashCanonical({mode,decisionId,subjectId,overrides,historicalInputs});const simulationId=deterministicUuid({enterpriseId:input.enterpriseId,inputHash,requestedAt});const result={...artifact,simulationId,status:"COMPLETED",productionMutationCount:0};const resultHash=hashCanonical(result);await trustArchitectureRepository().persistSimulation({simulationId,enterpriseId:input.enterpriseId,simulationType:mode,subjectId,decisionId,inputHash,requestedBy:input.actorId,requestedAt,resultHash,result,correlationId:input.correlationId});return result;}
