import Link from "next/link";
import type { TrustKpi } from "@/src/lib/trust-architecture/kpis";

const panel="rounded-2xl border border-white/10 bg-white/[0.035] p-5";
export function ArchitectureOverview({overview}:{overview:Record<string,unknown>}){return <section className={panel}><h2 className="text-lg font-semibold">Architecture health</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(overview).map(([key,value])=><div key={key} className="rounded-xl border border-white/10 p-4"><p className="text-xs uppercase tracking-wider text-zinc-500">{key.replaceAll("_"," ")}</p><p className="mt-2 text-2xl font-semibold text-cyan-200">{String(value)}</p></div>)}</div></section>}
export function DomainGrid({domains}:{domains:Array<Record<string,unknown>>}){return <section><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{domains.map((domain)=><Link key={String(domain.domain_key)} href={`/dashboard/trust-architecture/domains/${domain.domain_key}`} className={`${panel} block transition hover:border-cyan-400/40`}><div className="flex items-center justify-between"><h3 className="font-semibold">{String(domain.display_name)}</h3><span className="text-xs text-emerald-300">v{String(domain.version)}</span></div><p className="mt-3 text-sm leading-6 text-zinc-400">{String(domain.description)}</p><p className="mt-4 text-xs uppercase tracking-wider text-cyan-300">{String(domain.domain_key)}</p></Link>)}</div></section>}
export function TrustKpiCards({kpis}:{kpis:TrustKpi[]}){return <section><h2 className="mb-4 text-lg font-semibold">Evidence-backed KPIs</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{kpis.map((kpi)=><article key={kpi.metricKey} className={panel}><p className="text-xs uppercase tracking-wider text-zinc-500">{kpi.metricKey.replaceAll("_"," ")}</p><p className={`mt-3 text-xl font-semibold ${kpi.status==="MEASURED"?"text-cyan-200":"text-amber-200"}`}>{kpi.status==="MEASURED"?`${kpi.value}%`:"INSUFFICIENT_DATA"}</p>{kpi.status==="MEASURED"&&<p className="mt-2 text-xs text-zinc-500">{kpi.numerator} / {kpi.denominator}</p>}</article>)}</div></section>}
export function TrustPosture({state}:{state:Record<string,unknown>|null}){return <section className={panel}><h2 className="text-lg font-semibold">Current posture</h2>{state?<div className="mt-4 flex flex-wrap items-end gap-6"><div><p className="text-xs uppercase text-zinc-500">State</p><p className="mt-1 text-3xl font-semibold text-cyan-200">{String(state.state)}</p></div><div><p className="text-xs uppercase text-zinc-500">Confidence</p><p className="mt-1 text-xl">{String(state.confidence)}%</p></div><div><p className="text-xs uppercase text-zinc-500">Updated</p><p className="mt-1 text-sm text-zinc-300">{String(state.updated_at)}</p></div></div>:<p className="mt-3 text-amber-200">INSUFFICIENT_DATA</p>}</section>}
export function StateTimeline({decisions}:{decisions:Array<Record<string,unknown>>}){return <section className={panel}><h2 className="text-lg font-semibold">State timeline</h2>{decisions.length?<ol className="mt-4 space-y-4">{decisions.map((decision)=><li key={String(decision.state_decision_id)} className="border-l border-cyan-500/40 pl-4"><p className="font-medium">{String(decision.prior_state)} → {String(decision.next_state)}</p><p className="mt-1 text-xs text-zinc-500">{String(decision.decided_at)} · {String(decision.policy_id)}@{String(decision.policy_version)}</p></li>)}</ol>:<p className="mt-3 text-amber-200">No state decisions recorded.</p>}</section>}
export function EvidenceGraphView({graph}:{graph:{nodes:Array<Record<string,unknown>>;edges:Array<Record<string,unknown>>;truncated:boolean}}){return <section className={panel}><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Evidence Graph™</h2><span className="text-xs text-zinc-500">{graph.nodes.length} nodes · {graph.edges.length} edges</span></div>{graph.nodes.length?<div className="mt-4 grid gap-3 md:grid-cols-2">{graph.nodes.map((node)=><div key={String(node.nodeId)} className="rounded-xl border border-white/10 p-3"><p className="font-medium">{String(node.label??node.externalId)}</p><p className="mt-1 text-xs text-zinc-500">{String(node.nodeType)} · {String(node.domainKey??"UNSCOPED")}</p></div>)}</div>:<p className="mt-3 text-amber-200">No graph evidence is available.</p>}{graph.truncated&&<p className="mt-3 text-xs text-amber-200">Traversal was safely truncated.</p>}</section>}
export function PolicyHealth({policies}:{policies:Array<Record<string,unknown>>}){return <section className={panel}><h2 className="text-lg font-semibold">Policy health</h2><div className="mt-4 space-y-3">{policies.map((policy)=><div key={String(policy.policy_version_id)} className="flex flex-wrap justify-between gap-3 rounded-xl border border-white/10 p-3"><span>{String(policy.policy_id)}@{String(policy.version)}</span><span className={policy.active?"text-emerald-300":"text-zinc-500"}>{policy.active?"ACTIVE":"INACTIVE"} · {String(policy.layer)}</span></div>)}</div></section>}
export function ReplayView({decisionId,stateDecision}:{decisionId:string;stateDecision:Record<string,unknown>|null}){return <section className={panel}><h2 className="text-lg font-semibold">Replay™</h2><p className="mt-3 text-sm text-zinc-400">Historical replay restores evidence, provider health, consent and policy inputs as they existed at decision time. It never mutates current state.</p><Link href={`/api/trust-architecture/replay/${decisionId}`} className="mt-4 inline-block text-sm text-cyan-300 hover:underline">Open reproducible replay artifact</Link>{!stateDecision&&<p className="mt-3 text-xs text-amber-200">No authoritative Trust State decision is linked yet.</p>}</section>}
export function SimulationPanel(){return <section className={panel}><h2 className="text-lg font-semibold">Isolated simulations</h2><p className="mt-3 text-sm text-zinc-400">Policy, provider outage, evidence exclusion, consent and authority-lineage simulations are hash-addressed and production-immutable.</p><p className="mt-4 text-xs uppercase tracking-wider text-emerald-300">Production mutation count: 0</p></section>}
export function CoverageMap({domains}:{domains:Array<Record<string,unknown>>}){return <section className={panel}><h2 className="text-lg font-semibold">Coverage map</h2><div className="mt-4 flex flex-wrap gap-2">{domains.map((domain)=><span key={String(domain.domain_key)} className="rounded-full border border-cyan-500/20 bg-cyan-500/5 px-3 py-1 text-xs text-cyan-200">{String(domain.domain_key)}</span>)}</div></section>}
