import "server-only";
import { createServiceRoleClient } from "@/lib/supabase/service-role";
import { hashCanonical } from "../trust-core/hash.ts";
import type { TrustContract, TrustContractEvaluation } from "./types.ts";

function fail(operation: string, error: unknown): never {
  console.error("Enterprise Trust Fabric persistence failed safely.",{operation,code:(error as {code?:string})?.code??"UNKNOWN"});
  throw Object.assign(new Error(`${operation} failed safely.`),{status:500,code:"TRUST_FABRIC_PERSISTENCE_FAILED"});
}
export function enterpriseTrustFabricRepository() {
  const db=createServiceRoleClient();
  return {
    async objects(enterpriseId:string,subjectType?:string,subjectId?:string,limit=100){let query=db.from("enterprise_trust_objects").select("*").eq("enterprise_id",enterpriseId).limit(Math.min(200,Math.max(1,limit)));if(subjectType)query=query.eq("subject_type",subjectType);if(subjectId)query=query.eq("subject_id",subjectId);const result=await query;if(result.error)fail("Trust Object projection",result.error);return result.data??[];},
    async contracts(enterpriseId:string,contractId?:string){let query=db.from("trust_contracts").select("contract,record_hash,created_at").eq("enterprise_id",enterpriseId).order("issued_at",{ascending:false}).limit(100);if(contractId)query=query.eq("contract_id",contractId);const result=await query;if(result.error)fail("Trust Contract read",result.error);return (result.data??[]).map((row)=>row.contract as TrustContract);},
    async persistContract(enterpriseId:string,actorId:string,contract:TrustContract,correlationId:string){const result=await db.rpc("persist_trust_contract_v1",{p_enterprise_id:enterpriseId,p_actor_id:actorId,p_contract:contract,p_record_hash:hashCanonical(contract),p_correlation_id:correlationId});if(result.error)fail("Trust Contract write",result.error);return result.data;},
    async persistEvaluation(enterpriseId:string,actorId:string,evaluation:TrustContractEvaluation){const result=await db.rpc("persist_trust_contract_evaluation_v1",{p_enterprise_id:enterpriseId,p_actor_id:actorId,p_evaluation:evaluation});if(result.error)fail("Trust Contract evaluation write",result.error);return result.data;},
    async timelineSources(enterpriseId:string,subjectId:string){const subjectIsUuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(subjectId);const scopeQuery=db.from("scope_continuity_replay").select("*").eq("enterprise_id",enterpriseId).limit(200);const incidentQuery=db.from("incident_reporting_replay").select("*").eq("enterprise_id",enterpriseId).limit(200);const [scope,incidents,events]=await Promise.all([subjectIsUuid?scopeQuery.eq("execution_context_id",subjectId):Promise.resolve({data:[],error:null}),subjectIsUuid?incidentQuery.eq("incident_id",subjectId):Promise.resolve({data:[],error:null}),db.from("trust_events").select("*").eq("enterprise_id",enterpriseId).eq("subject_id",subjectId).limit(200)]);for(const [name,result] of [["scope",scope],["incidents",incidents],["events",events]] as const)if(result.error)fail(`Trust Timeline ${name}`,result.error);return {scope:scope.data??[],incidents:incidents.data??[],events:events.data??[]};},
    async overview(enterpriseId:string){const [objects,contracts,decisions,evaluations]=await Promise.all([db.from("enterprise_trust_objects").select("current_trust_state,evidence_completeness").eq("enterprise_id",enterpriseId),db.from("trust_contracts").select("contract_id,revocation_state,expires_at").eq("enterprise_id",enterpriseId),db.from("trust_fabric_decisions").select("trust_state,decision_type").eq("enterprise_id",enterpriseId).limit(500),db.from("trust_contract_evaluations").select("outcome").eq("enterprise_id",enterpriseId).limit(500)]);for(const [name,result] of [["objects",objects],["contracts",contracts],["decisions",decisions],["evaluations",evaluations]] as const)if(result.error)fail(`Trust Fabric overview ${name}`,result.error);const objectRows=objects.data??[];return {trustObjectCount:objectRows.length,states:Object.fromEntries(["verified","degraded","contested","suspended","revoked"].map((state)=>[state,objectRows.filter((row)=>row.current_trust_state===state).length])),evidenceIncompleteCount:objectRows.filter((row)=>row.evidence_completeness!=="complete").length,activeContractCount:(contracts.data??[]).filter((row)=>row.revocation_state==="active"&&new Date(String(row.expires_at))>new Date()).length,contractOutcomes:Object.fromEntries(["satisfied","satisfied_with_degraded_evidence","review_required","paused","breached","revoked"].map((outcome)=>[outcome,(evaluations.data??[]).filter((row)=>row.outcome===outcome).length])),decisionCount:(decisions.data??[]).length};},
  };
}
