import { InteractiveDemoScenario, type DemoScenarioStep } from "@/components/interactive-demo-scenario";

const steps: DemoScenarioStep[] = [
  { title: "Candidate enters workflow", state: "Observed", explanation: "A verified-looking candidate enters a governed remote interview session for a sensitive role.", evidence: "Session identity, start time, recruiter owner, role context and channel metadata.", action: "Start from the operational workflow, not a generic alert queue." },
  { title: "Verification begins", state: "Partial match", explanation: "The identity result is linked to the session, but the reviewer can still see that identity assurance and live-session behavior are separate states.", evidence: "Provider result, assurance context, candidate-provided evidence and verified email record.", action: "Keep identity assurance separate from session authenticity." },
  { title: "Session integrity fails", state: "High risk", explanation: "A mid-interview anomaly appears: device context changes, the camera feed stutters at a handoff point and the audio cadence no longer aligns with prior evidence. Detection is one signal.", evidence: "Device-channel state, anomaly timestamp, injection risk, liveness context, media-risk marker and evidence source.", action: "Escalate the changed session state before the interview outcome advances." },
  { title: "Governance review opens", state: "Assigned", explanation: "A named reviewer receives the session chronology, policy reason and evidence package instead of a hidden automated verdict.", evidence: "Assigned reviewer, policy context, open action and escalation reason.", action: "Route the case to a named reviewer with policy context and evidence." },
  { title: "Replay evidence generated", state: "Chronology ready", explanation: "The reviewer scans identity submission, session changes, risk events, reviewer notes and prior actions in order. This is not a standalone deepfake verdict.", evidence: "Replay timeline joining evidence, signals, actions, analyst notes, metadata/channel integrity summary and audit history.", action: "Make the decision path readable without asking teams to reconstruct it manually." },
  { title: "Risky session blocked", state: "Resolved", explanation: "The reviewer blocks the compromised session while keeping the candidate employment decision separate for the recruiting team.", evidence: "Resolution notes, human authority, block timestamp and escalation closure reason.", action: "Stop the compromised session and preserve the human rationale." },
  { title: "Verification receipt issued", state: "Issued", explanation: "Security, talent and compliance teams receive the same concise explanation of the evidence reviewed and the operational action taken.", evidence: "Printable receipt with identity, session integrity, injection, governance, reviewer and audit states.", action: "Create an audit-ready explanation for follow-up review." },
];

export default function SessionIntegrityDemoPage() {
  return <InteractiveDemoScenario label="Session Integrity" title="Verification happened at entry. Trust still changed during the session." summary="See why identity verification alone is insufficient and how Cyber Sentinels preserves evidence, governance and operational memory. Session integrity, evidence and governance determine the final review state." steps={steps} />;
}
