import Link from "next/link";
import { trustCentreUiContext } from "@/src/lib/trust-centre/ui-context";
import { enterpriseTrustFabricRepository } from "@/src/lib/trust-fabric/repository";

export const dynamic="force-dynamic";
const panel="rounded-2xl border border-white/10 bg-white/[0.035] p-5";
const links=[
  ["Identity","/trust-centre?view=continuous"],["Authority","/admin/trust-architecture"],["Environment","/trust-centre?view=continuous"],
  ["Scope","/trust-centre?view=continuous"],["Evidence","/trust-centre?view=graph"],["Continuous Trust","/trust-centre?view=continuous"],
  ["Contradictions","/trust-centre?view=alerts"],["Incidents","/admin/trust-integrity"],["Reviews","/trust-centre?view=alerts"],
  ["Timeline","/trust-replay"],["Replay","/trust-replay"],["Trust Memory","/trust-centre?view=replay"],
] as const;
export default async function TrustFabricPage(){const {workspace}=await trustCentreUiContext();if(!workspace)return <main className="min-h-screen bg-[#05080d] px-5 py-12 text-white"><p>Enterprise workspace required.</p></main>;const repository=enterpriseTrustFabricRepository();const [overview,objects,contracts]=await Promise.all([repository.overview(workspace.id),repository.objects(workspace.id,undefined,undefined,50),repository.contracts(workspace.id)]);return <main className="min-h-screen bg-[#05080d] px-4 py-8 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px] space-y-6">
  <header className={panel}><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Enterprise Trust Centre / Control plane</p><h1 className="mt-3 text-3xl font-semibold">Enterprise Trust Fabric™</h1><p className="mt-3 max-w-4xl text-zinc-400">A provider-neutral projection of identity, authority, environment, scope, evidence, Continuous Trust, incidents and review. Source systems remain authoritative.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/trust-centre" className="brand-secondary-action">Trust Centre overview</Link><Link href="/trust-replay" className="brand-secondary-action">Open Replay</Link></div></header>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Trust Health"><article className={panel}><p className="text-xs text-zinc-500">Trust Objects</p><p className="mt-2 text-3xl">{overview.trustObjectCount}</p></article><article className={panel}><p className="text-xs text-zinc-500">Active Contracts</p><p className="mt-2 text-3xl">{overview.activeContractCount}</p></article><article className={panel}><p className="text-xs text-zinc-500">Evidence incomplete</p><p className="mt-2 text-3xl">{overview.evidenceIncompleteCount}</p></article><article className={panel}><p className="text-xs text-zinc-500">Suspended or revoked</p><p className="mt-2 text-3xl">{Number(overview.states.suspended??0)+Number(overview.states.revoked??0)}</p></article></section>
  <section className={panel}><h2 className="text-xl font-semibold">Current Trust State</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{objects.map((object,index)=><article key={String(object.subject_id??index)} className="rounded-xl border border-white/10 p-4"><p className="font-medium">{String(object.display_label??object.subject_id)}</p><p className="mt-1 text-xs text-zinc-500">{String(object.subject_type)} · {String(object.subject_id)}</p><p className="mt-3 text-sm">State: <span className="font-semibold">{String(object.current_trust_state).replaceAll("_"," ")}</span></p><p className="mt-1 text-xs text-zinc-500">Evidence: {String(object.evidence_completeness)} · provenance: canonical Trust Object projection</p></article>)}{!objects.length?<p className="text-sm text-zinc-400">No canonical subjects are available in this workspace.</p>:null}</div></section>
  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{links.map(([label,href])=><Link key={label} href={href} className={`${panel} transition hover:border-cyan-400/50`}><h2 className="font-semibold">{label}</h2><p className="mt-2 text-sm text-zinc-500">Open the canonical source surface. Provenance and uncertainty are preserved.</p></Link>)}</section>
  <section className={panel}><h2 className="text-xl font-semibold">Active Contract</h2><div className="mt-4 space-y-3">{contracts.slice(0,10).map((contract)=><article key={contract.contractId} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">{contract.authorizedObjective}</p><span className="text-sm text-cyan-200">{contract.revocationState}</span></div><p className="mt-2 text-xs text-zinc-500">{contract.subject.displayName} · policy {contract.policyVersion} · expires {new Date(contract.expiresAt).toISOString()}</p></article>)}{!contracts.length?<p className="text-sm text-zinc-400">No Trust Contract has been issued for this workspace.</p>:null}</div></section>
</div></main>;}
