import assert from "node:assert/strict";
import test from "node:test";
import { consentDefaults, currentConsentPolicy, normalizeConsentChoices, privacyLevel, regionProfileFromCountry } from "../src/lib/consent/policy.ts";
import { canonicalizeConsentReceipt, signConsentReceipt, verifyConsentReceipt } from "../src/lib/consent/receipt.ts";
import { parseConsentCookie, serializeConsentCookie } from "../src/lib/consent/cookie.ts";
import { googleConsentModeState } from "../src/lib/consent/google-consent.ts";
import { applyConsentState, consentAllows, registerConsentTracker } from "../src/lib/consent/tracker-loader.ts";
import { consentIntegrationAdapters, mapHistoricalConsent } from "../src/lib/consent/integrations.ts";

const strict = { essential: true, functional: false, analytics: false, ai_improvements: false, marketing: false };
test("EEA, UK and unknown locations use strict optional defaults", () => { assert.deepEqual(consentDefaults("EEA"), strict); assert.deepEqual(consentDefaults("UK"), strict); assert.deepEqual(consentDefaults("GLOBAL_DEFAULT"), strict); assert.equal(regionProfileFromCountry("DE"), "EEA"); assert.equal(regionProfileFromCountry("GB"), "UK"); assert.equal(regionProfileFromCountry(null), "GLOBAL_DEFAULT"); assert.equal(currentConsentPolicy.categories.filter((category) => !category.required).every((category) => category.key !== "essential"), true); });
test("Essential cannot be disabled and privacy levels remain informational", () => { const normalized = normalizeConsentChoices({ essential: false, analytics: true }, "EEA"); assert.equal(normalized.essential, true); assert.equal(normalized.analytics, true); assert.equal(normalized.functional, false); assert.equal(privacyLevel(strict), "High"); assert.equal(privacyLevel({ ...strict, analytics: true }), "Custom"); });
function unsigned(overrides = {}) { return { receiptId: "11111111-1111-4111-8111-111111111111", enterpriseId: "22222222-2222-4222-8222-222222222222", userId: "33333333-3333-4333-8333-333333333333", anonymousId: null, policyVersion: currentConsentPolicy.version, bannerVersion: currentConsentPolicy.bannerVersion, preferenceSchemaVersion: currentConsentPolicy.preferenceSchemaVersion, regionProfile: "EEA", language: "en", categories: strict, purposes: ["consent_storage", "authentication"], providers: ["Supabase", "Cyber Sentinels"], consentAction: "REJECT_OPTIONAL", occurredAt: "2026-07-20T12:00:00+02:00", receivedAt: "2026-07-20T10:00:01.000Z", expiresAt: "2027-01-16T10:00:00.000Z", source: "CONSENT_BANNER", userAgentHash: null, coarseCountry: "ES", hashAlgorithm: "SHA-256", canonicalization: "RFC8785-JCS", ...overrides }; }
test("Consent Receipts are deterministic, normalized and tamper evident", () => { const first = signConsentReceipt(unsigned()); const second = signConsentReceipt(unsigned({ purposes: ["authentication", "consent_storage"], providers: ["Cyber Sentinels", "Supabase"] })); assert.equal(first.receiptHash, second.receiptHash); assert.match(first.receiptHash, /^[a-f0-9]{64}$/); assert.equal(verifyConsentReceipt(first), true); assert.equal(verifyConsentReceipt({ ...first, categories: { ...first.categories, analytics: true } }), false); assert.match(canonicalizeConsentReceipt(first), /"occurredAt":"2026-07-20T10:00:00.000Z"/); });
test("Consent cookie is short, signed and rejects tampering", () => { const state = { version: 1, policyVersion: currentConsentPolicy.version, categories: strict, receiptId: "11111111-1111-4111-8111-111111111111", expiresAt: "2099-01-01T00:00:00.000Z" }; const secret = "a-secure-test-only-consent-secret-at-least-32-bytes"; const value = serializeConsentCookie(state, secret); assert.ok(value.length < 1024); assert.deepEqual(parseConsentCookie(value, secret), state); assert.equal(parseConsentCookie(`${value}x`, secret), null); });
test("Google Consent Mode maps every optional category without requiring GTM", () => { const denied = googleConsentModeState(strict); assert.equal(denied.analytics_storage, "denied"); assert.equal(denied.ad_storage, "denied"); assert.equal(denied.functionality_storage, "denied"); assert.equal(denied.security_storage, "granted"); const granted = googleConsentModeState({ ...strict, analytics: true, marketing: true }); assert.equal(granted.analytics_storage, "granted"); assert.equal(granted.ad_personalization, "granted"); });
test("registry-driven trackers load only after consent and stop on withdrawal", () => { let loads = 0; let cleanups = 0; applyConsentState(strict, true); const unregister = registerConsentTracker({ id: "analytics-test", category: "analytics", load: () => { loads += 1; return () => { cleanups += 1; }; } }); assert.equal(loads, 0); assert.equal(consentAllows("analytics"), false); applyConsentState({ ...strict, analytics: true }); assert.equal(loads, 1); assert.equal(consentAllows("analytics"), true); applyConsentState(strict); assert.equal(cleanups, 1); unregister(); });
test("third-party hooks are disabled and historical imports never fabricate grants", () => { assert.equal(consentIntegrationAdapters.every((adapter) => !adapter.enabled), true); assert.deepEqual(mapHistoricalConsent({ analytics: true, marketing: "granted" }), { ...strict, analytics: true }); });
