import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read=(path)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
test("all required consensus APIs exist with tenant and mutation controls",()=>{for(const path of ["app/api/consensus/evaluate/route.ts","app/api/consensus/decisions/route.ts","app/api/consensus/decisions/[id]/route.ts","app/api/consensus/decisions/[id]/explanation/route.ts","app/api/consensus/subjects/[subjectId]/route.ts","app/api/consensus/subjects/[subjectId]/timeline/route.ts","app/api/consensus/providers/route.ts","app/api/consensus/providers/health/route.ts","app/api/consensus/policies/route.ts","app/api/admin/consensus/policies/route.ts","app/api/admin/consensus/policies/[id]/route.ts","app/api/admin/consensus/simulate/route.ts"]){const source=read(path);assert.match(source,/consensusContext/);if(/POST|PATCH/.test(source))assert.match(source,/assertConsensusMutation/);}});
test("enterprise UI includes every required consensus component and route",()=>{for(const component of ["ConsensusStatus","ConsensusScore","ProviderContributionList","ConflictPanel","DecisionExplanation","ProviderHealthGrid","ConsensusTimeline","PolicySummary"])assert.match(read(`src/components/consensus/${component}.tsx`),new RegExp(`function ${component}`));for(const route of ["app/dashboard/consensus/page.tsx","app/dashboard/consensus/subjects/[subjectId]/page.tsx","app/dashboard/consensus/decisions/[decisionId]/page.tsx","app/admin/consensus/providers/page.tsx","app/admin/consensus/policies/page.tsx"])assert.match(read(route),/Consensus/);});
test("World ID health UI states the exact zero-weight boundary",()=>{const source=read("src/components/consensus/ProviderHealthGrid.tsx");assert.match(source,/INCONCLUSIVE/);assert.match(source,/Server verification pending/);assert.match(source,/Zero positive consensus contribution/);});
test("API responses do not expose raw provider payloads",()=>{for(const path of ["src/lib/consensus/repository.ts","app/api/consensus/decisions/[id]/route.ts","app/api/consensus/providers/health/route.ts"])assert.doesNotMatch(read(path),/raw_payload|rawPayload|provider_payload/);});
test("Trust Event registry contains consensus lifecycle and provider health",()=>{const source=read("src/lib/trust-events/event-types.ts");for(const event of ["consensus.evaluation.started","consensus.evaluation.completed","consensus.verified","consensus.trusted","consensus.challenged","consensus.inconclusive","consensus.blocked","consensus.revoked","consensus.conflict.detected","consensus.policy.changed","provider.health.changed"])assert.match(source,new RegExp(event.replaceAll(".","\\.")));});
