import test from "node:test";
import assert from "node:assert/strict";
import { evaluateConsensus } from "../src/lib/consensus/engine.ts";
import { freshnessMultiplier } from "../src/lib/consensus/freshness.ts";
import { providerCapabilities } from "../src/lib/consensus/provider-capabilities.ts";
import { defaultConsensusPolicy } from "../src/lib/consensus/policy.ts";
import { verifyConsensusDecision } from "../src/lib/consensus/decision-lineage.ts";
import { replayConsensus } from "../src/lib/consensus/replay.ts";
import { validateConsensusDecision, validateProviderCapability, validateProviderObservation } from "../src/lib/consensus/types.ts";

const enterpriseId="11111111-1111-4111-8111-111111111111";const subjectId="subject-17-2";const now="2026-07-20T12:00:00.000Z";
const environment={HOPAE_ENABLED:"true",HOPAE_CLIENT_ID:"present",HOPAE_CLIENT_SECRET:"present",HOPAE_WEBHOOK_SECRET:"present",HOPAE_PROVIDER_ID:"present"};
const health=(providerKey="hopae_connect",state="HEALTHY")=>({providerKey,state,observedAt:now,latencyMs:80,errorRate:0,timeoutRate:0,signatureFailures:0,schemaFailures:0,circuitOpen:false,reasonCodes:[]});
function observation(overrides={}){return {observationId:crypto.randomUUID(),enterpriseId,subjectId,workflowId:"workflow-1",providerKey:"hopae_connect",signalType:"identity_verification",result:"PASS",assurance:.95,quality:.95,signatureVerified:true,serverVerified:true,authoritative:false,evidenceDigest:crypto.createHash?.("sha256")?.update?.(crypto.randomUUID())?.digest?.("hex")??"a".repeat(64),evidenceReference:`evidence:${crypto.randomUUID()}`,correlationKey:"hopae-government-source",occurredAt:"2026-07-20T11:59:00.000Z",receivedAt:"2026-07-20T11:59:01.000Z",expiresAt:null,supersedesObservationId:null,revokedObservationId:null,reasonCodes:["NORMALIZED_PROVIDER_EVIDENCE"],...overrides};}
// Web Crypto has no createHash; keep fixture digests deterministic and valid.
let digestCounter=0;function obs(overrides={}){digestCounter+=1;return observation({evidenceDigest:digestCounter.toString(16).padStart(64,"0"),...overrides});}
function evaluate(observations,extra={}){return evaluateConsensus({enterpriseId,subjectId,workflowId:"workflow-1",observations,policy:defaultConsensusPolicy,health:[health()],evaluatedAt:now,environment,...extra});}

test("capability registry centralizes safe provider truth",()=>{const registry=providerCapabilities(environment);assert.equal(registry.find((row)=>row.providerKey==="hopae_connect").positiveEvidence,true);const world=registry.find((row)=>row.providerKey==="world_id");assert.equal(world.baseWeight,0);assert.equal(world.positiveEvidence,false);assert.ok(registry.filter((row)=>!["hopae_connect","world_id"].includes(row.providerKey)).every((row)=>row.baseWeight===0&&row.state==="UNSUPPORTED"));});
test("strict observation validator rejects unbounded quality",()=>assert.throws(()=>validateProviderObservation({...obs(),quality:2}),/between 0 and 1/));
test("all four domain schemas have strict runtime validation",()=>{const capability=providerCapabilities(environment)[0];assert.equal(validateProviderCapability(capability).providerKey,"hopae_connect");const decision=evaluate([obs()]);assert.equal(validateConsensusDecision(decision).decisionHash,decision.decisionHash);assert.throws(()=>validateConsensusDecision({...decision,state:"APPROVED"}),/unsupported/);});
test("valid signed Hopae evidence contributes but one group cannot verify",()=>{const decision=evaluate([obs()]);assert.equal(decision.state,"TRUSTED");assert.ok(decision.confidence>=50);assert.ok(decision.reasonCodes.includes("INDEPENDENT_GROUP_REQUIREMENT_NOT_MET"));});
test("invalid Hopae signature contributes zero positive weight",()=>{const decision=evaluate([obs({signatureVerified:false})]);assert.equal(decision.state,"INCONCLUSIVE");assert.equal(decision.confidence,0);assert.equal(decision.evidence[0].ignoredReason,"CRYPTOGRAPHIC_VERIFICATION_REQUIRED");});
test("Hopae evidence without server verification contributes zero positive weight",()=>{const decision=evaluate([obs({serverVerified:false})]);assert.equal(decision.state,"INCONCLUSIVE");assert.equal(decision.confidence,0);assert.equal(decision.evidence[0].ignoredReason,"SERVER_VERIFICATION_REQUIRED");});
test("World ID remains inconclusive with zero positive contribution",()=>{const decision=evaluate([obs({providerKey:"world_id",signalType:"proof_of_personhood",serverVerified:false,reasonCodes:["WORLD_ID_SERVER_VERIFICATION_NOT_IMPLEMENTED"]})],{health:[health("world_id")]});assert.equal(decision.state,"INCONCLUSIVE");assert.equal(decision.confidence,0);assert.equal(decision.evidence[0].ignoredReason,"WORLD_ID_SERVER_VERIFICATION_NOT_IMPLEMENTED");});
test("provider count and placeholders cannot verify",()=>{const providers=["persona","entrust","onfido","stripe_identity"].map((providerKey)=>obs({providerKey,correlationKey:providerKey}));const decision=evaluate(providers,{health:providers.map((item)=>health(item.providerKey))});assert.equal(decision.state,"INCONCLUSIVE");assert.equal(decision.confidence,0);});
test("duplicate evidence is counted once",()=>{const first=obs();const duplicate=obs({evidenceDigest:first.evidenceDigest});const decision=evaluate([first,duplicate]);assert.equal(decision.evidence.filter((item)=>item.included).length,1);assert.ok(decision.evidence.some((item)=>item.ignoredReason==="DUPLICATE_EVIDENCE"));});
test("correlation penalty is explicit and cannot satisfy independent groups",()=>{const decision=evaluate([obs(),obs()]);assert.ok(decision.evidence.some((item)=>item.independenceMultiplier===.25));assert.notEqual(decision.state,"VERIFIED");});
test("expired evidence has zero freshness",()=>{const item=obs({expiresAt:"2026-07-20T11:00:00.000Z"});assert.equal(freshnessMultiplier(item,86400,defaultConsensusPolicy,now),0);assert.equal(evaluate([item]).confidence,0);});
test("delayed provider delivery is classified in decision reasons",()=>{const decision=evaluate([obs({occurredAt:"2026-07-20T11:00:00.000Z",receivedAt:"2026-07-20T11:30:00.000Z"})]);assert.ok(decision.reasonCodes.includes("DELAYED_PROVIDER_DELIVERY"));});
test("high-assurance negative evidence overrides weak positive evidence",()=>{const positive=obs({assurance:.55,quality:.6});const negative=obs({result:"FAIL",assurance:1,quality:1,authoritative:true,correlationKey:"independent-negative"});const decision=evaluate([positive,negative]);assert.ok(["BLOCKED","CHALLENGED"].includes(decision.state));assert.ok(decision.conflicts.some((item)=>["MATERIAL","CRITICAL"].includes(item.severity)));});
test("authoritative revocation forces REVOKED",()=>{const decision=evaluate([obs({result:"REVOKED",authoritative:true})]);assert.equal(decision.state,"REVOKED");});
test("decision lineage hash is deterministic and tamper evident",()=>{const item=obs();const first=evaluate([item]);const second=evaluate([item]);assert.equal(first.decisionId,second.decisionId);assert.equal(first.decisionHash,second.decisionHash);assert.equal(verifyConsensusDecision(first),true);assert.equal(verifyConsensusDecision({...first,confidence:first.confidence+1}),false);});
test("historical replay supports evidence exclusion and provider outages without mutation",()=>{const item=obs();const baseline=replayConsensus({enterpriseId,subjectId,workflowId:"workflow-1",observations:[item],policies:[defaultConsensusPolicy],health:[health()],asOf:now});const outage=replayConsensus({enterpriseId,subjectId,workflowId:"workflow-1",observations:[item],policies:[defaultConsensusPolicy],health:[health()],asOf:now,providerOutages:["hopae_connect"]});assert.equal(baseline.simulated,true);assert.equal(outage.state,"INCONCLUSIVE");assert.equal(outage.confidence,0);assert.equal(item.result,"PASS");});
