import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read = (path) => readFile(new URL(path, import.meta.url), "utf8");
const [banner, preferences, category, manager, layout, mainApi, withdrawApi, service, consentHttp, eventTypes, shell, cookieApi, consentRepository, observability] = await Promise.all([read("../src/components/consent/ConsentBanner.tsx"),read("../src/components/consent/ConsentPreferences.tsx"),read("../src/components/consent/ConsentCategory.tsx"),read("../src/components/consent/ConsentManager.tsx"),read("../app/layout.tsx"),read("../app/api/consent/route.ts"),read("../app/api/consent/withdraw/route.ts"),read("../src/lib/consent/service.ts"),read("../src/lib/consent/http.ts"),read("../src/lib/trust-events/event-types.ts"),read("../components/trust-os/enterprise-shell.tsx"),read("../app/api/consent/cookies/route.ts"),read("../src/lib/consent/repository.ts"),read("../src/lib/consent/observability.ts")]);
test("banner is global, accessible, responsive and keeps accept/reject equally prominent", () => { assert.match(layout, /<ConsentManager/); assert.match(banner, /Your Privacy\. Your Trust\./); assert.match(banner, /role="dialog"/); assert.match(banner, /aria-modal="true"/); assert.match(banner, /event\.key !== "Tab"/); assert.match(banner, /event\.key === "Escape"/); assert.equal([...banner.matchAll(/className=\{equalAction\}/g)].length, 2); assert.match(banner, /Accept All/); assert.match(banner, /Reject Optional/); assert.match(banner, /Manage Preferences/); });
test("preference centre exposes all controls and locks Essential", () => { for (const label of ["Save Preferences","Accept All","Reject Optional","Cancel"]) assert.match(preferences, new RegExp(label)); assert.match(category, /disabled=\{category\.required\}/); assert.match(category, /role="switch"/); assert.match(category, /aria-label/); assert.match(preferences, /policy\.version/); });
test("preference dialog is viewport-safe, visibly elevated, and internally scrollable", () => {
  assert.match(manager, /fixed inset-0 z-\[10000\] flex items-center justify-center/);
  assert.match(manager, /bg-slate-950\/80/);
  assert.match(manager, /max-h-\[90dvh\]/);
  assert.match(manager, /w-full max-w-2xl/);
  assert.match(manager, /overflow-hidden/);
  assert.match(manager, /overscroll-contain overflow-y-auto/);
  assert.match(manager, /bg-\[var\(--brand-surface\)\]/);
  assert.match(manager, /safe-area-inset-top/);
});
test("preference dialog has labelled semantics, contained focus, scroll lock, and policy-safe dismissal", () => {
  assert.match(manager, /role="dialog"/);
  assert.match(manager, /aria-modal="true"/);
  assert.match(manager, /aria-labelledby="consent-preferences-heading"/);
  assert.match(manager, /aria-describedby="consent-preferences-description"/);
  assert.match(preferences, /id="consent-preferences-heading"/);
  assert.match(preferences, /id="consent-preferences-description"/);
  assert.match(manager, /aria-label="Close cookie preferences"/);
  assert.match(manager, /event\.key === "Escape"/);
  assert.match(manager, /event\.key !== "Tab"/);
  assert.match(manager, /document\.body\.style\.overflow = "hidden"/);
  assert.match(manager, /document\.documentElement\.style\.overflow = "hidden"/);
  assert.match(manager, /event\.target === event\.currentTarget/);
  assert.match(manager, /preferenceReturnFocus\.current\?\.focus\(\)/);
});
test("preference controls retain reachable mobile actions and readable category surfaces", () => {
  assert.match(preferences, /grid gap-2 sm:grid-cols-2/);
  assert.doesNotMatch(preferences, /lg:grid-cols-4/);
  assert.equal([...preferences.matchAll(/min-h-11 w-full/g)].length, 2);
  assert.match(category, /flex flex-col[\s\S]*sm:flex-row/);
  assert.match(category, /bg-\[var\(--brand-surface-raised\)\]/);
  assert.match(category, /min-h-11/);
});
test("choices persist through controlled APIs with CSRF, idempotency and withdrawal cleanup", () => { assert.match(mainApi, /assertConsentMutationRequest/); assert.match(mainApi, /idempotency-key/); assert.match(mainApi, /serializeConsentCookie/); assert.match(mainApi, /sameSite: "lax"/); assert.match(withdrawApi, /maxAge: 0/); assert.match(manager, /applyConsentState/); });
test("consent emits canonical Trust Events without raw subject identifiers", () => { for (const type of ["consent.banner.displayed","consent.accept_all","consent.reject_optional","consent.preferences.saved","consent.withdrawn","consent.policy.reconsent_required","consent.policy.version_changed","consent.receipt.created"]) assert.match(eventTypes, new RegExp(type.replaceAll(".","\\."))); assert.match(service, /signTrustEvent/); assert.match(service, /consent-receipt:/); assert.match(consentHttp, /sha256Hex\(`consent-user-v1/); assert.doesNotMatch(service, /normalizedFacts:[\s\S]{0,500}userId/); });
test("settings exposes Privacy & Trust Preferences and optional loading is fail closed", () => { assert.match(shell, /Settings → Privacy &amp; Trust Preferences/); assert.match(manager, /consentDefaults\("GLOBAL_DEFAULT"\)/); assert.doesNotMatch(layout, /googletagmanager|google-analytics|posthog|plausible|zaraz/i); });
test("history uses a stable compound cursor and receipt retrieval reports recomputed integrity", async () => { const history=await read("../app/api/consent/history/route.ts");const repository=await read("../src/lib/consent/repository.ts");assert.match(history,/JSON\.stringify\(\[last\.occurred_at,last\.receipt_id\]\)/);assert.match(repository,/occurred_at\.lt/);assert.match(repository,/receipt_id\.lt/);assert.match(repository,/verifyConsentReceipt/);assert.match(repository,/integrity_valid/); });
test("consent retry failures preserve typed reason codes and correlation-safe structured telemetry", () => {
  assert.match(cookieApi, /consentErrorTelemetry\(error, "consent\.cookies\.persist"\)/);
  assert.match(cookieApi, /reasonCode: errorCode/);
  assert.match(cookieApi, /correlationId/);
  assert.match(cookieApi, /operation: telemetry\.operation/);
  assert.match(cookieApi, /supabaseCode: telemetry\.supabaseCode/);
  assert.match(consentHttp, /consentErrorTelemetry\(error, "consent\.api"\)/);
  assert.match(consentRepository, /operation,/);
  assert.match(consentRepository, /supabaseMessage/);
  assert.match(observability, /redactSensitive/);
  assert.match(observability, /\[redacted-ip\]/);
  assert.match(observability, /\[redacted-jwt\]/);
});
