import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { evaluateContinuousTrust } from "../src/lib/continuous-trust/engine.ts";
import { defaultContinuousTrustPolicy } from "../src/lib/continuous-trust/types.ts";
import { hashCanonical } from "../src/lib/trust-core/hash.ts";

const enterpriseId = "11111111-1111-4111-8111-111111111111";
const evaluatedAt = "2026-07-21T12:00:00.000Z";
const providerHealth = [{ providerKey: "provider_a", state: "HEALTHY", observedAt: evaluatedAt, latencyMs: 80, errorRate: 0, circuitOpen: false, reasonCodes: [] }, { providerKey: "provider_b", state: "HEALTHY", observedAt: evaluatedAt, latencyMs: 90, errorRate: 0, circuitOpen: false, reasonCodes: [] }];
function evidence(index, overrides = {}) { const evidenceId = `22222222-2222-4222-8222-${String(index).padStart(12, "0")}`; return { evidenceId, enterpriseId, domainKey: "IDENTITY", subjectId: "human:1", subjectType: "HUMAN", evidenceType: "identity_verification", sourceType: "PROVIDER_OBSERVATION", sourceKey: index % 2 ? "provider_a" : "provider_b", result: "POSITIVE", assuranceLevel: "VERY_HIGH", cryptographicallyVerified: true, serverVerified: true, occurredAt: "2026-07-21T11:55:00.000Z", receivedAt: "2026-07-21T11:55:01.000Z", expiresAt: "2026-07-22T12:00:00.000Z", payloadHash: hashCanonical({ evidenceId }), canonicalization: "JCS", hashAlgorithm: "SHA-256", references: [{ refType: "PROVIDER_OBSERVATION", refId: evidenceId }], reasonCodes: [], ...overrides }; }
function input(overrides = {}) { return { enterpriseId, domainKey: "IDENTITY", subjectId: "human:1", subjectType: "HUMAN", evaluatedAt, sourceEventId: "33333333-3333-4333-8333-333333333333", evidence: [evidence(1), evidence(2)], providerHealth, previous: null, policy: { ...defaultContinuousTrustPolicy, freshnessByEvidenceType: {} }, ...overrides }; }

test("continuous evaluation is deterministic and duplicate-safe for identical inputs", () => { const first = evaluateContinuousTrust(input()); const second = evaluateContinuousTrust(input()); assert.deepEqual(first, second); assert.equal(first.assessmentId, second.assessmentId); assert.match(first.assessmentHash, /^[a-f0-9]{64}$/); assert.equal(first.recommendation.recommendedState, "VERIFIED"); });
test("policy thresholds deterministically control runtime transitions", () => { const strict = evaluateContinuousTrust(input({ evidence: [evidence(1)], policy: { ...defaultContinuousTrustPolicy, policyVersion: "strict-2", verifiedScore: 100, trustedScore: 99, freshnessByEvidenceType: {} } })); assert.equal(strict.recommendation.recommendedState, "CHALLENGED"); assert.equal(strict.policyVersion, "strict-2"); });
test("expired evidence causes expiry and schedules recalculation without deleting history", () => { const result = evaluateContinuousTrust(input({ evidence: [evidence(1, { expiresAt: "2026-07-21T11:59:59.000Z" })] })); assert.equal(result.evidenceFreshness, "EXPIRED"); assert.equal(result.recommendation.recommendedState, "EXPIRED"); assert.ok(result.evidenceReferences.length === 1); assert.ok(result.drift.some((finding) => finding.reasonCode === "EVIDENCE_EXPIRED")); });
test("revocation fails closed and materially changes the evidence snapshot", () => { const valid = evaluateContinuousTrust(input({ evidence: [evidence(1)] })); const revoked = evaluateContinuousTrust(input({ evidence: [evidence(1, { result: "REVOKED" })] })); assert.equal(revoked.recommendation.recommendedState, "REVOKED"); assert.equal(revoked.score, 0); assert.notEqual(revoked.evidenceSnapshotHash, valid.evidenceSnapshotHash); });
test("score deterioration creates rule-bound drift and an alert", () => { const result = evaluateContinuousTrust(input({ evidence: [evidence(1)], previous: { state: "VERIFIED", score: 98, confidence: 100, evidenceFreshness: "CURRENT", policyVersion: "1.0.0", riskFlags: [], stateDecisionId: "44444444-4444-4444-8444-444444444444" } })); assert.equal(result.transitionType, "DEGRADED"); assert.ok(result.drift.some((finding) => finding.ruleId === "CTR-SCORE-001")); assert.ok(result.alerts.some((alert) => alert.driftId === result.drift.find((finding) => finding.ruleId === "CTR-SCORE-001")?.driftId)); });
test("fresh independent evidence restores trust from a challenged state", () => { const result = evaluateContinuousTrust(input({ previous: { state: "CHALLENGED", score: 45, confidence: 50, evidenceFreshness: "DEGRADED", policyVersion: "1.0.0", riskFlags: [], stateDecisionId: null } })); assert.equal(result.recommendation.recommendedState, "VERIFIED"); assert.equal(result.transitionType, "RESTORED"); });
test("provider disagreement produces explainable high-severity drift", () => { const result = evaluateContinuousTrust(input({ evidence: [evidence(1), evidence(2, { result: "NEGATIVE" })] })); const finding = result.drift.find((item) => item.reasonCode === "PROVIDER_DISAGREEMENT"); assert.equal(finding?.severity, "high"); assert.equal(finding?.ruleId, "CTR-PROVIDER-001"); assert.ok(finding?.evidenceReferences.length === 2); });
test("provider outage reduces confidence and creates a bounded operational alert", () => { const outage = [{ ...providerHealth[0], state: "UNAVAILABLE", circuitOpen: true, reasonCodes: ["PROVIDER_CIRCUIT_OR_INCIDENT_OPEN"] }, providerHealth[1]]; const result = evaluateContinuousTrust(input({ providerHealth: outage })); assert.ok(result.confidence < 100); assert.ok(result.riskFlags.includes("PROVIDER_OUTAGE_IMPACT")); assert.ok(result.alerts.some((alert) => alert.alertType === "continuous_provider_outage")); });
test("repeated verification failures fail closed", () => { const result = evaluateContinuousTrust(input({ evidence: [evidence(1, { result: "NEGATIVE" }), evidence(2, { result: "NEGATIVE" })] })); assert.equal(result.recommendation.recommendedState, "BLOCKED"); assert.ok(result.riskFlags.includes("REPEATED_VERIFICATION_FAILURE")); });

test("EPIC 19 routes use enterprise auth, validation, canonical sources and bounded polling", async () => { const paths = ["../app/api/trust/runtime/route.ts", "../app/api/trust/runtime/[subjectId]/route.ts", "../app/api/trust/timeline/route.ts", "../app/api/trust/events/route.ts", "../app/api/trust/evidence/route.ts", "../app/api/trust/alerts/route.ts", "../app/api/trust/replay/[decisionId]/route.ts", "../app/api/trust/providers/health/route.ts", "../app/api/trust/recalculate/route.ts", "../app/api/trust/refresh/route.ts", "../app/api/trust/alerts/[id]/acknowledge/route.ts", "../app/api/trust/alerts/[id]/resolve/route.ts"]; const sources = await Promise.all(paths.map((path) => readFile(new URL(path, import.meta.url), "utf8"))); for (const source of sources) assert.match(source, /continuousTrust(Context|CorrelationId|Repository|Response)|mutationContext/); assert.match(sources[0], /boundedLimit/); assert.match(sources[8], /mutationContext/); assert.match(sources[11], /RESOLUTION_NOTE_REQUIRED/); const events = sources[3]; const evidenceRoute = sources[4]; assert.match(events, /continuousTrustRepository\(\)\.events/); assert.doesNotMatch(events, /from\("signals"\)|trackTrustEvent/); assert.match(evidenceRoute, /listEvidence/); assert.doesNotMatch(evidenceRoute, /demoEvidence|placeholder/); const dashboard = await readFile(new URL("../src/components/continuous-trust/ContinuousTrustDashboard.tsx", import.meta.url), "utf8"); assert.match(dashboard, /pollIntervalMs = 30_000/); assert.match(dashboard, /document\.visibilityState/); assert.match(dashboard, /aria-live="polite"/); });

test("Replay is read-only and carries continuous assessment, drift and alert context", async () => { const route = await readFile(new URL("../app/api/trust/replay/[decisionId]/route.ts", import.meta.url), "utf8"); const repository = await readFile(new URL("../src/lib/continuous-trust/repository.ts", import.meta.url), "utf8"); assert.match(route, /mutatedProduction: false/); assert.match(route, /buildReplayArtifact/); assert.match(repository, /trust_drift_findings/); assert.match(repository, /trust_alerts/); assert.match(repository, /revoked_at/); assert.match(repository, /\.is\("superseded_by_evidence_id", null\)/); assert.match(repository, /freshness_policy_seconds/); assert.doesNotMatch(route, /\.insert\(|\.update\(|\.delete\(/); });
