import assert from "node:assert/strict";
import test from "node:test";

import { createDesignPartnerDecisionEngine } from "../lib/design-partner/trust-transaction.ts";

test("registers an agent with tenant, owner and lineage fields", () => {
  const engine = createDesignPartnerDecisionEngine();
  const agent = engine.registerAgent({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    agentId: "agent-alpha",
    accountableOwnerId: "owner-1",
    operatorId: "operator-1",
    agentName: "Agent Alpha",
    agentType: "assistant",
    provider: "hopae_connect",
    modelFamily: "gpt",
    modelVersion: "4.1",
    runtime: "staging",
    purpose: "security workflow review",
    permittedTools: ["github_pull_request_create"],
    permittedDataClasses: ["internal"],
    permittedResources: ["repo:demo"],
    environment: "staging",
    status: "active",
    registeredAt: "2026-08-01T00:00:00.000Z",
    evidenceReferences: ["evidence-1"],
    canonicalDigest: "digest-agent",
  });

  assert.equal(agent.tenantId, "tenant-a");
  assert.equal(agent.status, "active");
  assert.equal(agent.accountableOwnerId, "owner-1");
  assert.ok(agent.agentId);
});

test("delegated authority requires expiry, scope and resource binding", () => {
  const engine = createDesignPartnerDecisionEngine();
  const authority = engine.delegateAuthority({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    principalHumanId: "owner-1",
    delegatedAgentId: "agent-alpha",
    purpose: "create pull requests",
    permittedActionTypes: ["github_pull_request_create"],
    permittedTools: ["github_pull_request_create"],
    permittedResources: ["repo:demo"],
    permittedRepositories: ["demo/repo"],
    permittedBranches: ["feature/*"],
    permittedEnvironments: ["staging"],
    dataBoundary: "internal",
    maximumActionCount: 5,
    maximumDelegationDepth: 0,
    issuedAt: "2026-08-01T00:00:00.000Z",
    effectiveAt: "2026-08-01T00:00:00.000Z",
    expiresAt: "2026-08-02T00:00:00.000Z",
    policyId: "policy-1",
    policyVersion: "v1",
    canonicalDigest: "digest-authority",
  });

  assert.equal(authority.authorityId.startsWith("auth-"), true);
  assert.equal(authority.permittedActionTypes[0], "github_pull_request_create");
  assert.equal(authority.expiresAt, "2026-08-02T00:00:00.000Z");
});

test("evaluateTrustDecision returns allow, review or deny with stable reason codes", () => {
  const engine = createDesignPartnerDecisionEngine();
  const agent = engine.registerAgent({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    agentId: "agent-alpha",
    accountableOwnerId: "owner-1",
    operatorId: "operator-1",
    agentName: "Agent Alpha",
    agentType: "assistant",
    provider: "hopae_connect",
    modelFamily: "gpt",
    modelVersion: "4.1",
    runtime: "staging",
    purpose: "security workflow review",
    permittedTools: ["github_pull_request_create"],
    permittedDataClasses: ["internal"],
    permittedResources: ["repo:demo"],
    environment: "staging",
    status: "active",
    registeredAt: "2026-08-01T00:00:00.000Z",
    evidenceReferences: ["evidence-1"],
    canonicalDigest: "digest-agent",
  });

  const authority = engine.delegateAuthority({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    principalHumanId: "owner-1",
    delegatedAgentId: agent.agentId,
    purpose: "create pull requests",
    permittedActionTypes: ["github_pull_request_create"],
    permittedTools: ["github_pull_request_create"],
    permittedResources: ["repo:demo"],
    permittedRepositories: ["demo/repo"],
    permittedBranches: ["feature/*"],
    permittedEnvironments: ["staging"],
    dataBoundary: "internal",
    maximumActionCount: 5,
    maximumDelegationDepth: 0,
    issuedAt: "2026-08-01T00:00:00.000Z",
    effectiveAt: "2026-08-01T00:00:00.000Z",
    expiresAt: "2026-08-02T00:00:00.000Z",
    policyId: "policy-1",
    policyVersion: "v1",
    canonicalDigest: "digest-authority",
  });

  const allowDecision = engine.evaluateTrustDecision({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    actorContext: { authenticatedActorId: "owner-1", actorType: "human" },
    agent,
    authority,
    action: {
      requestId: "req-allow",
      actionType: "github_pull_request_create",
      targetSystem: "github",
      repository: "demo/repo",
      branch: "feature/demo",
      resource: "repo:demo",
      requestedOperation: "create",
      changeClassification: "minor",
      environment: "staging",
      purpose: "create a pull request",
      toolReference: "github_pull_request_create",
      agentVersion: "4.1",
      modelVersion: "4.1",
      requestedAt: "2026-08-01T01:00:00.000Z",
      idempotencyKey: "idem-allow",
      correlationId: "corr-allow",
      evidenceReferences: ["evidence-1"],
      canonicalDigest: "digest-request",
    },
    policy: { id: "policy-1", version: "v1", digest: "policy-digest" },
    trustState: { state: "verified", updatedAt: "2026-08-01T00:30:00.000Z" },
    providerEvidence: [{
      providerId: "hopae_connect",
      providerEnvironment: "staging",
      providerOperation: "assessment",
      externalReference: "ext-1",
      assuranceLevel: "medium",
      normalizedResult: "pass",
      providerNativeStatus: "available",
      providerTimestamp: "2026-08-01T00:50:00.000Z",
      receivedAt: "2026-08-01T00:51:00.000Z",
      freshness: 0.95,
      confidence: 0.9,
      evidenceDigest: "provider-digest",
      limitations: [],
      timeout: false,
      correlationId: "corr-provider",
    }],
    activeIncidents: [],
    environment: "staging",
    correlationId: "corr-allow",
  });

  assert.equal(allowDecision.decision, "allow");
  assert.equal(allowDecision.reviewRequired, false);
  assert.ok(allowDecision.reasonCodes.includes("AUTHORITY_VALID"));

  const reviewDecision = engine.evaluateTrustDecision({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    actorContext: { authenticatedActorId: "owner-1", actorType: "human" },
    agent,
    authority,
    action: {
      requestId: "req-review",
      actionType: "github_security_configuration_change",
      targetSystem: "github",
      repository: "demo/repo",
      branch: "main",
      resource: "repo:demo",
      requestedOperation: "change",
      changeClassification: "security",
      environment: "staging",
      purpose: "change security workflow",
      toolReference: "github_security_configuration_change",
      agentVersion: "4.1",
      modelVersion: "4.1",
      requestedAt: "2026-08-01T01:10:00.000Z",
      idempotencyKey: "idem-review",
      correlationId: "corr-review",
      evidenceReferences: ["evidence-1"],
      canonicalDigest: "digest-request-review",
    },
    policy: { id: "policy-1", version: "v1", digest: "policy-digest" },
    trustState: { state: "verified", updatedAt: "2026-08-01T00:30:00.000Z" },
    providerEvidence: [],
    activeIncidents: [],
    environment: "staging",
    correlationId: "corr-review",
  });

  assert.equal(reviewDecision.decision, "review");
  assert.ok(reviewDecision.reasonCodes.includes("EVIDENCE_MISSING"));

  const denyDecision = engine.evaluateTrustDecision({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    actorContext: { authenticatedActorId: "owner-1", actorType: "human" },
    agent,
    authority,
    action: {
      requestId: "req-deny",
      actionType: "github_pull_request_merge",
      targetSystem: "github",
      repository: "demo/repo",
      branch: "main",
      resource: "repo:demo",
      requestedOperation: "merge",
      changeClassification: "minor",
      environment: "staging",
      purpose: "merge to main",
      toolReference: "github_pull_request_merge",
      agentVersion: "4.1",
      modelVersion: "4.1",
      requestedAt: "2026-08-01T01:20:00.000Z",
      idempotencyKey: "idem-deny",
      correlationId: "corr-deny",
      evidenceReferences: ["evidence-1"],
      canonicalDigest: "digest-request-deny",
    },
    policy: { id: "policy-1", version: "v1", digest: "policy-digest" },
    trustState: { state: "verified", updatedAt: "2026-08-01T00:30:00.000Z" },
    providerEvidence: [{
      providerId: "hopae_connect",
      providerEnvironment: "staging",
      providerOperation: "assessment",
      externalReference: "ext-1",
      assuranceLevel: "medium",
      normalizedResult: "pass",
      providerNativeStatus: "available",
      providerTimestamp: "2026-08-01T00:50:00.000Z",
      receivedAt: "2026-08-01T00:51:00.000Z",
      freshness: 0.95,
      confidence: 0.9,
      evidenceDigest: "provider-digest",
      limitations: [],
      timeout: false,
      correlationId: "corr-provider",
    }],
    activeIncidents: [],
    environment: "staging",
    correlationId: "corr-deny",
  });

  assert.equal(denyDecision.decision, "deny");
  assert.ok(denyDecision.reasonCodes.includes("AUTHORITY_SCOPE_EXCEEDED"));
});

test("idempotency returns the prior decision and rejects changed retries", () => {
  const engine = createDesignPartnerDecisionEngine();
  const agent = engine.registerAgent({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    agentId: "agent-alpha",
    accountableOwnerId: "owner-1",
    operatorId: "operator-1",
    agentName: "Agent Alpha",
    agentType: "assistant",
    provider: "hopae_connect",
    modelFamily: "gpt",
    modelVersion: "4.1",
    runtime: "staging",
    purpose: "security workflow review",
    permittedTools: ["github_pull_request_create"],
    permittedDataClasses: ["internal"],
    permittedResources: ["repo:demo"],
    environment: "staging",
    status: "active",
    registeredAt: "2026-08-01T00:00:00.000Z",
    evidenceReferences: ["evidence-1"],
    canonicalDigest: "digest-agent",
  });
  const authority = engine.delegateAuthority({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    principalHumanId: "owner-1",
    delegatedAgentId: agent.agentId,
    purpose: "create pull requests",
    permittedActionTypes: ["github_pull_request_create"],
    permittedTools: ["github_pull_request_create"],
    permittedResources: ["repo:demo"],
    permittedRepositories: ["demo/repo"],
    permittedBranches: ["feature/*"],
    permittedEnvironments: ["staging"],
    dataBoundary: "internal",
    maximumActionCount: 5,
    maximumDelegationDepth: 0,
    issuedAt: "2026-08-01T00:00:00.000Z",
    effectiveAt: "2026-08-01T00:00:00.000Z",
    expiresAt: "2026-08-02T00:00:00.000Z",
    policyId: "policy-1",
    policyVersion: "v1",
    canonicalDigest: "digest-authority",
  });

  const first = engine.evaluateTrustDecision({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    actorContext: { authenticatedActorId: "owner-1", actorType: "human" },
    agent,
    authority,
    action: {
      requestId: "req-idempotent",
      actionType: "github_pull_request_create",
      targetSystem: "github",
      repository: "demo/repo",
      branch: "feature/demo",
      resource: "repo:demo",
      requestedOperation: "create",
      changeClassification: "minor",
      environment: "staging",
      purpose: "create a pull request",
      toolReference: "github_pull_request_create",
      agentVersion: "4.1",
      modelVersion: "4.1",
      requestedAt: "2026-08-01T01:00:00.000Z",
      idempotencyKey: "same-key",
      correlationId: "corr-idempotent-1",
      evidenceReferences: ["evidence-1"],
      canonicalDigest: "digest-request",
    },
    policy: { id: "policy-1", version: "v1", digest: "policy-digest" },
    trustState: { state: "verified", updatedAt: "2026-08-01T00:30:00.000Z" },
    providerEvidence: [{
      providerId: "hopae_connect",
      providerEnvironment: "staging",
      providerOperation: "assessment",
      externalReference: "ext-1",
      assuranceLevel: "medium",
      normalizedResult: "pass",
      providerNativeStatus: "available",
      providerTimestamp: "2026-08-01T00:50:00.000Z",
      receivedAt: "2026-08-01T00:51:00.000Z",
      freshness: 0.95,
      confidence: 0.9,
      evidenceDigest: "provider-digest",
      limitations: [],
      timeout: false,
      correlationId: "corr-provider",
    }],
    activeIncidents: [],
    environment: "staging",
    correlationId: "corr-idempotent-1",
  });

  const replayed = engine.evaluateTrustDecision({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    actorContext: { authenticatedActorId: "owner-1", actorType: "human" },
    agent,
    authority,
    action: {
      requestId: "req-idempotent",
      actionType: "github_pull_request_create",
      targetSystem: "github",
      repository: "demo/repo",
      branch: "feature/demo",
      resource: "repo:demo",
      requestedOperation: "create",
      changeClassification: "minor",
      environment: "staging",
      purpose: "create a pull request",
      toolReference: "github_pull_request_create",
      agentVersion: "4.1",
      modelVersion: "4.1",
      requestedAt: "2026-08-01T01:00:00.000Z",
      idempotencyKey: "same-key",
      correlationId: "corr-idempotent-2",
      evidenceReferences: ["evidence-1"],
      canonicalDigest: "digest-request",
    },
    policy: { id: "policy-1", version: "v1", digest: "policy-digest" },
    trustState: { state: "verified", updatedAt: "2026-08-01T00:30:00.000Z" },
    providerEvidence: [{
      providerId: "hopae_connect",
      providerEnvironment: "staging",
      providerOperation: "assessment",
      externalReference: "ext-1",
      assuranceLevel: "medium",
      normalizedResult: "pass",
      providerNativeStatus: "available",
      providerTimestamp: "2026-08-01T00:50:00.000Z",
      receivedAt: "2026-08-01T00:51:00.000Z",
      freshness: 0.95,
      confidence: 0.9,
      evidenceDigest: "provider-digest",
      limitations: [],
      timeout: false,
      correlationId: "corr-provider",
    }],
    activeIncidents: [],
    environment: "staging",
    correlationId: "corr-idempotent-2",
  });

  assert.equal(replayed.decisionId, first.decisionId);

  const conflict = engine.evaluateTrustDecision({
    tenantId: "tenant-a",
    enterpriseId: "enterprise-a",
    actorContext: { authenticatedActorId: "owner-1", actorType: "human" },
    agent,
    authority,
    action: {
      requestId: "req-idempotent-conflict",
      actionType: "github_pull_request_create",
      targetSystem: "github",
      repository: "demo/repo",
      branch: "feature/demo",
      resource: "repo:demo",
      requestedOperation: "create",
      changeClassification: "minor",
      environment: "staging",
      purpose: "create a pull request",
      toolReference: "github_pull_request_create",
      agentVersion: "4.1",
      modelVersion: "4.1",
      requestedAt: "2026-08-01T01:00:00.000Z",
      idempotencyKey: "same-key",
      correlationId: "corr-idempotent-3",
      evidenceReferences: ["evidence-1"],
      canonicalDigest: "digest-request-different",
    },
    policy: { id: "policy-1", version: "v1", digest: "policy-digest" },
    trustState: { state: "verified", updatedAt: "2026-08-01T00:30:00.000Z" },
    providerEvidence: [{
      providerId: "hopae_connect",
      providerEnvironment: "staging",
      providerOperation: "assessment",
      externalReference: "ext-1",
      assuranceLevel: "medium",
      normalizedResult: "pass",
      providerNativeStatus: "available",
      providerTimestamp: "2026-08-01T00:50:00.000Z",
      receivedAt: "2026-08-01T00:51:00.000Z",
      freshness: 0.95,
      confidence: 0.9,
      evidenceDigest: "provider-digest",
      limitations: [],
      timeout: false,
      correlationId: "corr-provider",
    }],
    activeIncidents: [],
    environment: "staging",
    correlationId: "corr-idempotent-3",
  });

  assert.equal(conflict.decision, "deny");
  assert.ok(conflict.reasonCodes.includes("IDEMPOTENCY_CONFLICT"));
});
