import assert from "node:assert/strict";
import test from "node:test";
import { createDecisionEnvelope,evaluateEnterpriseTrust,strongestAdverseState } from "../src/lib/trust-fabric/control-plane.ts";
import { evaluateTrustContract } from "../src/lib/trust-fabric/contracts.ts";
import { assertTimelineTenant,projectEnterpriseTrustTimeline } from "../src/lib/trust-fabric/timeline.ts";
import { syntheticEvidenceAdapter } from "../src/lib/trust-fabric/adapters.ts";
import { resolveReplayAvailability } from "../src/lib/trust-fabric/replay.ts";
import { canonicalProviderRuntimeState } from "../lib/providers/runtime-contract.ts";

const ids={enterprise:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",correlation:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"};
const ref=(type,id)=>({type,id});
const decision=(state="verified",code="VERIFIED")=>({state,reasonCodes:[code],evidenceReferences:[ref("evidence",`evidence:${code}`)],decisionReference:ref("decision",`decision:${code}`)});
function fabric(overrides={}){return {enterpriseId:ids.enterprise,subject:{type:"ai_agent",id:"agent:treasury",displayName:"Treasury agent"},workflow:{id:"workflow:approval",objective:"approve payment"},identity:decision(),authority:decision(),environment:{...decision(),consistent:true},scope:{...decision(),continuous:true},providers:[{...decision(),providerId:"provider:a"}],policy:{id:"policy:fabric",version:"1.0.0"},continuousTrust:decision(),evidenceCompleteness:"complete",contradictions:[],incidents:[],reviewerDecisions:[],evaluatedAt:"2026-08-01T12:00:00.000Z",correlationId:ids.correlation,...overrides};}

for(const type of ["human","ai_agent","workflow","provider"]){test(`Trust Object composes ${type} without copying source payloads`,()=>{const result=evaluateEnterpriseTrust(fabric({subject:{type,id:`${type}:1`,displayName:`${type} one`}}));assert.equal(result.trustObject.subject.type,type);assert.equal(result.currentTrustState,"verified");assert.equal("score" in result.trustObject,false);assert.ok(result.evidenceReferences.length);});}
test("missing evidence is explicit and degrades trust",()=>{const result=evaluateEnterpriseTrust(fabric({evidenceCompleteness:"insufficient"}));assert.equal(result.currentTrustState,"degraded");assert.ok(result.reasonCodes.includes("EVIDENCE_INSUFFICIENT"));});
test("contradictory evidence contests trust and requires operational action",()=>{const result=evaluateEnterpriseTrust(fabric({contradictions:[{id:"contradiction:1",state:"contested",reasonCode:"PROVIDER_ASSERTION_CONTRADICTED",evidenceReferences:[ref("evidence","evidence:counter")]}]}));assert.equal(result.currentTrustState,"contested");assert.ok(result.recommendedOperationalActions.includes("resolve contradictions"));});
test("strongest adverse state preserves suspended and revoked outcomes",()=>{assert.equal(strongestAdverseState(["verified","suspended","degraded"]),"suspended");assert.equal(strongestAdverseState(["suspended","revoked","contested"]),"revoked");});
test("control plane composes canonical decision references and deterministic reason codes",()=>{const result=evaluateEnterpriseTrust(fabric());assert.equal(result.reasonCodes.join(","),[...result.reasonCodes].sort().join(","));assert.ok(result.trustObject.continuousTrustStateReference);assert.equal(result.trustObject.policyVersion,"1.0.0");});
test("legal decisions remain specialist references",()=>{assert.throws(()=>createDecisionEnvelope({enterpriseId:ids.enterprise,subject:fabric().subject,workflow:null,decisionType:"legal_reference",outcome:"reportable",trustState:"contested",reasonCodes:[],evidenceReferences:[],policyId:"policy:legal-boundary",policyVersion:"1",evaluator:"fabric-reference-adapter",evaluatorVersion:"1",actorOrSystemAuthority:"system:fabric",humanReviewRequired:true,createdAt:"2026-08-01T12:00:00.000Z",supersededDecisionId:null,correlationId:ids.correlation,legalDecisionReference:null}),/externally referenced/);const input={enterpriseId:ids.enterprise,subject:fabric().subject,workflow:null,decisionType:"legal_reference",outcome:"referenced",trustState:"contested",reasonCodes:["LEGAL_DECISION_REFERENCED"],evidenceReferences:[],policyId:"policy:legal-boundary",policyVersion:"1",evaluator:"fabric-reference-adapter",evaluatorVersion:"1",actorOrSystemAuthority:"legal:external",humanReviewRequired:false,createdAt:"2026-08-01T12:00:00.000Z",supersededDecisionId:null,correlationId:ids.correlation,legalDecisionReference:ref("legal_decision","legal:123")};assert.equal(createDecisionEnvelope(input).deterministicDigest,createDecisionEnvelope(input).deterministicDigest);});

function contract(overrides={}){return {contractId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc",enterpriseId:ids.enterprise,subject:fabric().subject,workflow:{id:"workflow:approval",objective:"approve payment"},authorizedObjective:"approve payment",requiredIdentityState:"verified",requiredAuthority:["approve_payment"],requiredEnvironmentState:"verified",permittedScope:["payments:approve"],permittedProviders:["provider:a"],requiredEvidenceTypes:["identity","environment"],maximumEvidenceAgeSeconds:3600,monitoringRequirements:["continuous"],humanReviewThresholds:["material_contradiction"],contradictionPolicy:"review",incidentThreshold:"critical",expiresAt:"2026-08-02T12:00:00.000Z",revocationState:"active",issuer:"authority:risk",approver:"human:risk",policyVersion:"1.0.0",evidenceReferences:[ref("mandate","mandate:1")],issuedAt:"2026-08-01T00:00:00.000Z",...overrides};}
function contractInput(overrides={}){return {contract:contract(),evaluatedAt:"2026-08-01T12:00:00.000Z",identityState:"verified",authorityState:"verified",effectiveAuthority:["approve_payment"],environmentState:"verified",scopeState:"verified",requestedScope:["payments:approve"],activeProviders:["provider:a"],evidence:[{type:"identity",observedAt:"2026-08-01T11:30:00.000Z",reference:ref("evidence","identity:1")},{type:"environment",observedAt:"2026-08-01T11:45:00.000Z",reference:ref("evidence","environment:1")}],monitoring:["continuous"],contradictions:[],highestIncidentSeverity:"none",humanReviewRequired:false,correlationId:ids.correlation,...overrides};}
const contractCases=[
  ["satisfied",{},"satisfied"],
  ["degraded evidence",{evidence:[]},"satisfied_with_degraded_evidence"],
  ["human review",{humanReviewRequired:true},"review_required"],
  ["paused on stale attestation",{evidence:[{type:"identity",observedAt:"2026-08-01T10:00:00.000Z",reference:ref("evidence","old:1")},{type:"environment",observedAt:"2026-08-01T11:45:00.000Z",reference:ref("evidence","environment:1")}]},"paused"],
  ["breached by wrong provider",{activeProviders:["provider:b"]},"breached"],
  ["breached by wrong environment",{environmentState:"contested"},"breached"],
  ["breached by scope contradiction",{requestedScope:["payments:transfer"]},"breached"],
  ["breached by incident threshold",{highestIncidentSeverity:"critical"},"breached"],
  ["revoked",{contract:contract({revocationState:"revoked"})},"revoked"],
  ["authority revoked",{authorityState:"revoked"},"revoked"],
  ["expired",{evaluatedAt:"2026-08-03T12:00:00.000Z"},"breached"],
];
for(const [name,override,outcome] of contractCases)test(`Trust Contract ${name}`,()=>assert.equal(evaluateTrustContract(contractInput(override)).outcome,outcome));
test("Trust Contract digest is stable",()=>{const input=contractInput();assert.equal(evaluateTrustContract(input).deterministicDigest,evaluateTrustContract(input).deterministicDigest);});

function timelineItem(id,category,timestamp="2026-08-01T12:00:00.000Z",confidence="confirmed",enterpriseId=ids.enterprise){return {id,category,source:"canonical source",sourceType:"trust_event",eventType:`${category}_EVENT`,timestamp,timestampConfidence:confidence,evidenceStrength:"observed",integrityState:"verified",enterpriseId,subject:fabric().subject,correlationId:ids.correlation,evidenceReferences:[ref("evidence",`evidence:${id}`)],supersedesItemId:null,uncertainty:[],summary:`${category} event`};}
test("timeline preserves every category, source attribution and supersession",()=>{const categories=["IDENTITY","AUTHORITY","ENVIRONMENT","SCOPE","PROVIDER","POLICY","TRUST_STATE","INCIDENT","REVIEW","LEGAL","REGULATOR","CORRECTIVE_ACTION"];const items=categories.map((category,index)=>({...timelineItem(`item:${index}`,category),...(index===1?{supersedesItemId:"item:0"}:{})}));const result=projectEnterpriseTrustTimeline([items]);assert.deepEqual(new Set(result.map((item)=>item.category)),new Set(categories));assert.equal(result[1].source,"canonical source");assert.equal(result[1].supersedesItemId,"item:0");});
test("timeline marks uncertain equal-time ordering and fabricates no action",()=>{const result=projectEnterpriseTrustTimeline([[timelineItem("b","REVIEW",undefined,"low"),timelineItem("a","REVIEW",undefined,"unknown")]]);assert.ok(result.every((item)=>item.uncertainty.length));assert.ok(result.every((item)=>!item.summary.includes("performed")));});
test("timeline rejects cross-tenant projection",()=>assert.throws(()=>assertTimelineTenant([timelineItem("x","SCOPE",undefined,undefined,"dddddddd-dddd-4ddd-8ddd-dddddddddddd")],ids.enterprise),/Cross-tenant/));

test("provider adapter attributes assertions and produces a stable digest",()=>{const input={providerIdentity:"provider:a",providerType:"identity_provider",subjectType:"human",subjectId:"human:1",displayName:"Human one",observedAt:"2026-08-01T12:00:00.000Z",receivedAt:"2026-08-01T12:00:01.000Z",category:"identity",classification:"assertion",confidence:.8,evidenceStrength:"asserted",integrityStatus:"unverified",externalReference:"provider-event:1",normalizedData:{outcome:"pass"},correlationId:ids.correlation};const output=syntheticEvidenceAdapter.normalize(input);assert.equal(output.classification,"assertion");assert.equal(output.sourceSystem,"synthetic_example");assert.equal(output.deterministicDigest,syntheticEvidenceAdapter.normalize(input).deterministicDigest);});
test("provider runtime uses five operational states",()=>{assert.equal(canonicalProviderRuntimeState({configured:true,usesMockData:false,safeFailure:true,runtimeState:"Live"}),"available");assert.equal(canonicalProviderRuntimeState({configured:true,usesMockData:true,safeFailure:true,runtimeState:"Simulated"}),"degraded");assert.equal(canonicalProviderRuntimeState({configured:false,usesMockData:false,safeFailure:false,runtimeState:"Disabled"}),"unavailable");assert.equal(canonicalProviderRuntimeState({configured:true,usesMockData:false,safeFailure:true,runtimeState:"Live",hasContradiction:true}),"contradicted");assert.equal(canonicalProviderRuntimeState({configured:false,usesMockData:false,safeFailure:true,runtimeState:"Prototype"}),"unknown");});
test("Replay preserves unavailable, missing, empty, failed, denied and ready states",()=>{const base={authorized:true,generationFailed:false,sourceAvailable:true,collectionAttempted:true,evidenceReferences:[],relevantEventCount:0};assert.equal(resolveReplayAvailability(base).state,"empty");assert.equal(resolveReplayAvailability({...base,collectionAttempted:false}).state,"evidence_missing");assert.equal(resolveReplayAvailability({...base,sourceAvailable:false}).state,"source_unavailable");assert.equal(resolveReplayAvailability({...base,generationFailed:true}).state,"generation_failed");assert.equal(resolveReplayAvailability({...base,authorized:false}).state,"access_denied");assert.equal(resolveReplayAvailability({...base,evidenceReferences:[ref("provider_evidence","provider:1")],relevantEventCount:4}).state,"ready");});
test("provider activity count cannot become provider-backed Replay evidence",()=>{const result=resolveReplayAvailability({authorized:true,generationFailed:false,sourceAvailable:true,collectionAttempted:true,evidenceReferences:[],relevantEventCount:9});assert.equal(result.state,"evidence_missing");assert.equal(result.evidenceReferences.length,0);});
