import assert from "node:assert/strict";import fs from "node:fs";import test from "node:test";
const read=(path)=>fs.readFileSync(path,"utf8");
test("Trust Fabric APIs authenticate, authorize mutations, bound streams and return correlations",()=>{const files=["app/api/trust-fabric/objects/route.ts","app/api/trust-fabric/contracts/route.ts","app/api/trust-fabric/contracts/[contractId]/evaluate/route.ts","app/api/trust-fabric/timeline/[subjectType]/[subjectId]/route.ts","app/api/trust-fabric/overview/route.ts"].map(read).join("\n");assert.match(files,/fabricContext/);assert.match(files,/\["owner","admin"/);assert.match(files,/readFabricJson/);const http=read("src/lib/trust-fabric/http.ts")+read("src/lib/scope-continuity/http.ts")+read("src/lib/trust-architecture/http.ts");assert.match(http,/getReader\(\)/);assert.match(http,/PAYLOAD_TOO_LARGE/);assert.match(http,/CSRF_/);assert.match(http,/x-correlation-id/);});
test("strict schemas reject unknown fields",()=>assert.match(read("src/lib/trust-fabric/validation.ts"),/UNKNOWN_FIELD/));
test("Trust Fabric API does not expose service credentials or log evidence bodies",()=>{const files=fs.readdirSync("app/api/trust-fabric",{recursive:true}).filter((file)=>String(file).endsWith(".ts")).map((file)=>read(`app/api/trust-fabric/${file}`)).join("\n");assert.doesNotMatch(files,/service_role|SUPABASE_SERVICE|process\.env|console\.log/);});
test("Trust Centre extends its existing shell with canonical control-plane sections",()=>{const page=read("app/(enterprise)/trust-centre/fabric/page.tsx");for(const section of ["Current Trust State","Identity","Authority","Environment","Scope","Provider State","Evidence Completeness","Active Trust Contract","Contradictions","Serious Incidents","Reviewer Queue","Corrective Actions","Trust Timeline","Replay","Trust Memory"])assert.match(page,new RegExp(section));assert.match(read("src/components/trust-centre/EnterpriseTrustCentre.tsx"),/\/trust-centre\/fabric/);});
test("canonical navigation owns public, authenticated, admin, Trust Centre, dashboard and capability routes",()=>{const navigation=read("lib/navigation/canonical-navigation.ts");for(const key of ["public","authenticated","admin","trustCentre","dashboard","productCapabilities"])assert.match(navigation,new RegExp(`${key}:`));assert.match(read("components/global-navigation.tsx"),/canonicalNavigation/);});
test("homepage uses bounded canonical positioning and routes approved CTAs",()=>{const home=read("app/page.tsx");assert.match(home,/Operational Trust Intelligence™/);assert.match(home,/Cyber Sentinels is building/);assert.match(home,/href="#operational-trust-intelligence"/);assert.match(home,/enterprise-access\?intent=design_partner/);assert.match(home,/enterprise-access\?intent=intro_call/);assert.doesNotMatch(home,/Private Beta|guaranteed containment|automatic legal compliance|regulator approval/i);});
test("canonical demo answers fourteen cross-Epic questions and legacy execution entry redirects",()=>{const demo=read("app/demo/page.tsx");for(const question of ["Who or what acted?","What identity was verified?","What authority existed?","What environment was declared?","What environment was observed?","What scope was permitted?","What evidence supported the decision?","Why did trust change?","Was an incident opened?","What containment was requested?","What containment was confirmed?","Who reviewed it?","What corrective action followed?","How can the complete sequence be replayed?"])assert.match(demo,new RegExp(question.replace(/[?]/g,"\\?")));assert.match(read("app/demo/trust-execution-flow/page.tsx"),/redirect\("\/demo"\)/);});
