import test from "node:test";
import assert from "node:assert/strict";
import { canonicalize } from "../src/lib/trust-core/canonicalize.ts";
import { hashCanonical } from "../src/lib/trust-core/hash.ts";
import { resolveTrustDomain,trustDomainRegistry } from "../src/lib/trust-architecture/domain-registry.ts";
import { validateEvidenceObject } from "../src/lib/trust-architecture/evidence.ts";
import { createTrustDecisionContract } from "../src/lib/trust-architecture/decision-contracts.ts";
import { evaluateTrustState } from "../src/lib/trust-state/engine.ts";
import { assertTransition } from "../src/lib/trust-state/transitions.ts";
import { resolveTrustPolicy } from "../src/lib/trust-policy/policy-resolution.ts";
import { safeGraphMetadata } from "../src/lib/trust-architecture/evidence-graph.ts";
import { insufficientKpi } from "../src/lib/trust-architecture/kpis.ts";

const enterpriseId="11111111-1111-4111-8111-111111111111";
const evidenceId="22222222-2222-4222-8222-222222222222";
const payloadHash="a".repeat(64);
function evidence(overrides={}){return {evidenceId,enterpriseId,domainKey:"IDENTITY",subjectId:"human:1",subjectType:"HUMAN",evidenceType:"identity_verification",sourceType:"PROVIDER_OBSERVATION",sourceKey:"hopae_connect",result:"POSITIVE",assuranceLevel:"VERY_HIGH",cryptographicallyVerified:true,serverVerified:true,occurredAt:"2026-07-21T10:00:00.000Z",receivedAt:"2026-07-21T10:00:01.000Z",expiresAt:"2026-07-22T10:00:00.000Z",payloadHash,canonicalization:"JCS",hashAlgorithm:"SHA-256",references:[{refType:"PROVIDER_OBSERVATION",refId:evidenceId}],reasonCodes:["HOPAE_SIGNED_EVIDENCE"],...overrides};}

test("shared JCS and SHA-256 are deterministic",()=>{assert.equal(canonicalize({b:2,a:1}),'{"a":1,"b":2}');assert.equal(hashCanonical({b:2,a:1}),hashCanonical({a:1,b:2}));});
test("domain registry is versioned and unknown domains fail closed",()=>{assert.equal(trustDomainRegistry.length,10);assert.equal(resolveTrustDomain("IDENTITY").version,"1.0.0");assert.throws(()=>resolveTrustDomain("UNKNOWN_DOMAIN"),/Unknown trust domain/);});
test("Evidence Objects enforce integrity and World ID cannot masquerade as server verified",()=>{assert.equal(validateEvidenceObject(evidence()).result,"POSITIVE");const world=validateEvidenceObject(evidence({sourceKey:"world_id",result:"INCONCLUSIVE",serverVerified:false,cryptographicallyVerified:false,assuranceLevel:"NONE"}));assert.equal(world.serverVerified,false);assert.equal(world.result,"INCONCLUSIVE");});
test("Trust State Engine alone applies a valid first evidence-backed transition",()=>{const item=evidence();const snapshot=hashCanonical([evidenceId]);const contract=createTrustDecisionContract({enterpriseId,domainKey:"IDENTITY",subjectId:"human:1",policyId:"identity-default",policyVersion:"1",evidenceSnapshotHash:snapshot,requestedAt:"2026-07-21T10:01:00.000Z",decisionInputs:{recommendation:"TRUSTED"}});const decision=evaluateTrustState({contract,priorState:"UNKNOWN",recommendation:{recommendationId:"33333333-3333-4333-8333-333333333333",recommendedState:"TRUSTED",confidence:90,reasonCodes:["CONSENSUS_TRUSTED"],evidenceSnapshotHash:snapshot},evidence:[item],policy:{policyId:"identity-default",policyVersion:"1",allowRecoveryFromBlocked:false,minimumEvidenceForTrusted:1,minimumEvidenceForVerified:2},decidedAt:"2026-07-21T10:01:00.000Z"});assert.equal(decision.nextState,"TRUSTED");assert.match(decision.decisionHash,/^[a-f0-9]{64}$/);});
test("revocation is irreversible and stale evidence cannot sustain VERIFIED",()=>{assert.throws(()=>assertTransition("REVOKED","VERIFIED"),/not permitted/);const item=evidence({expiresAt:"2026-07-20T00:00:00.000Z"});const snapshot=hashCanonical([evidenceId]);const contract=createTrustDecisionContract({enterpriseId,domainKey:"IDENTITY",subjectId:"human:1",policyId:"identity-default",policyVersion:"1",evidenceSnapshotHash:snapshot,requestedAt:"2026-07-21T10:01:00.000Z",decisionInputs:{recommendation:"VERIFIED"}});const decision=evaluateTrustState({contract,priorState:"OBSERVED",recommendation:{recommendationId:"33333333-3333-4333-8333-333333333333",recommendedState:"VERIFIED",confidence:99,reasonCodes:[],evidenceSnapshotHash:snapshot},evidence:[item],policy:{policyId:"identity-default",policyVersion:"1",allowRecoveryFromBlocked:false,minimumEvidenceForTrusted:1,minimumEvidenceForVerified:1},decidedAt:"2026-07-21T10:01:00.000Z"});assert.equal(decision.nextState,"EXPIRED");});
test("policy resolution is deterministic by prescribed layer order",()=>{const base={policyId:"p",active:true,validFrom:"2026-01-01T00:00:00Z"};const resolved=resolveTrustPolicy({enterpriseId,domainKey:"IDENTITY",asOf:"2026-07-21T00:00:00Z",versions:[{...base,version:"1",layer:"PLATFORM_DEFAULT",rules:{threshold:50}},{...base,enterpriseId,version:"2",layer:"ENTERPRISE_OVERRIDE",rules:{threshold:70}}]});assert.equal(resolved.rules.threshold,70);assert.match(resolved.resolutionHash,/^[a-f0-9]{64}$/);});
test("UI graph shaping removes sensitive payload fields and KPIs do not invent data",()=>{assert.deepEqual(safeGraphMetadata({label:"safe",rawPayload:"secret",credential:"secret",score:4}),{label:"safe",score:4});assert.equal(insufficientKpi("workflow_trust",new Date(0).toISOString()).status,"INSUFFICIENT_DATA");});
