import test from "node:test";
import assert from "node:assert/strict";
import { criticalContradictionScenario, consistentContextScenario } from "../src/lib/scope-continuity/scenarios.ts";
import { evaluateScopeContinuity } from "../src/lib/scope-continuity/evaluator.ts";
import { strongerEvidence, validateEvidenceAttribution } from "../src/lib/scope-continuity/evidence.ts";
import { validateEnvironmentAttestation, validateExecutionContextDeclaration, validateScopeContinuityInput } from "../src/lib/scope-continuity/validation.ts";

function consistentInput() { return structuredClone(consistentContextScenario().input); }
function evaluate(mutator) { const input=consistentInput(); mutator?.(input); return evaluateScopeContinuity(input); }

test("valid execution-context declaration preserves accountable source and integrity",()=>{const input=consistentInput();const value=validateExecutionContextDeclaration(input.declaration);assert.equal(value.environmentClass,"simulation");assert.equal(value.accountableOwnerId,"operator:demo-owner");assert.equal(value.integrityMetadata.status,"verified");});
test("invalid environment class fails closed",()=>{const input=consistentInput();input.declaration.environmentClass="sandbox";assert.throws(()=>validateExecutionContextDeclaration(input.declaration),{code:"ENVIRONMENT_CLASS_INVALID"});});
test("invalid declaration validity range fails closed",()=>{const input=consistentInput();input.declaration.validUntil=input.declaration.validFrom;assert.throws(()=>validateExecutionContextDeclaration(input.declaration),{code:"DECLARATION_VALIDITY_INVALID"});});
test("invalid evidence source fails closed",()=>{const input=consistentInput();input.attestations[0].attestationSourceType="anonymous_claim";assert.throws(()=>validateEnvironmentAttestation(input.attestations[0]),{code:"ATTESTATION_SOURCE_INVALID"});});
test("untrusted boolean and control-state values fail closed",()=>{const input=consistentInput();input.declaration.internetAccessExpected="false";assert.throws(()=>validateExecutionContextDeclaration(input.declaration),{code:"BOOLEAN_VALUE_INVALID"});const second=consistentInput();second.attestations[0].monitoringState="nominal";assert.throws(()=>validateEnvironmentAttestation(second.attestations[0]),{code:"ENUM_VALUE_INVALID"});});
test("invalid policy outcomes fail closed",()=>{const input=consistentInput();input.policy.criticalContradictionOutcome="allow";assert.throws(()=>validateScopeContinuityInput(input),{code:"POLICY_INVALID"});});
test("expired scope lease is denied",()=>{const decision=evaluate((input)=>{input.authorization.issuedAt="2026-07-31T10:00:00.000Z";input.authorization.expiresAt="2026-07-31T11:00:00.000Z";});assert.equal(decision.outcome,"deny");assert.ok(decision.reasonCodes.includes("SCOPE_AUTHORIZATION_INVALID"));});
test("revoked scope lease revokes scope",()=>{const decision=evaluate((input)=>{input.authorization.revokedAt="2026-07-31T11:30:00.000Z";input.authorization.revocationReason="operator revocation";});assert.equal(decision.outcome,"revoke_scope");assert.equal(decision.trustImpact.nextState,"revoked");});
test("cross-enterprise references are rejected",()=>{const input=consistentInput();input.attestations[0].enterpriseId="77777777-7777-4777-8777-777777777777";assert.throws(()=>validateScopeContinuityInput(input),{code:"CROSS_ENTERPRISE_REFERENCE"});});
test("declared simulation versus observed production is critical and denied",()=>{const {decision}=criticalContradictionScenario();assert.equal(decision.outcome,"deny");assert.ok(decision.contradictions.some((item)=>item.type==="declared_simulation_observed_production"&&item.severity==="critical"));});
test("unexpected internet access emits a stable critical contradiction",()=>{const {decision}=criticalContradictionScenario();assert.ok(decision.reasonCodes.includes("INTERNET_REACHABILITY_UNEXPECTED"));});
test("unexpected production target is denied",()=>{const decision=evaluate((input)=>{input.request.targetEnvironmentClass="production";});assert.equal(decision.outcome,"deny");assert.ok(decision.reasonCodes.includes("PRODUCTION_TARGET_NOT_EXPECTED"));});
test("target outside authorized set is denied",()=>{const decision=evaluate((input)=>{input.request.targetIdentifier="other.internal";});assert.equal(decision.outcome,"deny");assert.ok(decision.reasonCodes.includes("TARGET_OUTSIDE_AUTHORIZED_SCOPE"));});
test("missing independent attestation requires human approval",()=>{const decision=evaluate((input)=>{input.attestations=[];});assert.equal(decision.outcome,"require_human_approval");assert.equal(decision.evidenceAvailability,"insufficient");assert.ok(decision.missingEvidence.includes("attestation:independent"));});
test("stale attestation pauses rather than representing verified context",()=>{const decision=evaluate((input)=>{input.attestations[0].freshness="stale";});assert.equal(decision.outcome,"pause");assert.notEqual(decision.trustImpact.nextState,"verified");assert.ok(decision.reasonCodes.includes("ATTESTATION_STALE"));});
test("independent evidence prevails over a contradictory provider assertion",()=>{const input=consistentInput();const provider=structuredClone(input.attestations[0]);provider.id="77777777-7777-4777-8777-777777777777";provider.attestationSourceType="provider_assertion";provider.attestationSourceId="provider:runtime-host";provider.providerOrThirdPartyIdentity="provider:runtime-host";provider.sourceAuthority="provider:self-report";provider.evidenceStrength="asserted";provider.observedEnvironmentClass="production";provider.internetReachable=true;provider.productionReachable=true;provider.evidenceReference="evidence:provider:runtime-host";input.attestations.push(provider);const decision=evaluateScopeContinuity(input);assert.ok(decision.reasonCodes.includes("PROVIDER_ASSERTION_CONTRADICTED"));assert.equal(decision.trustImpact.nextState,"contested");assert.equal(strongerEvidence(provider,input.attestations[0]).attestationSourceType,"independent_attestation");});
test("monitoring unavailable never becomes verified",()=>{const decision=evaluate((input)=>{input.attestations[0].monitoringState="unavailable";});assert.equal(decision.outcome,"require_human_approval");assert.equal(decision.trustImpact.nextState,"degraded");});
test("consistent current context is allowed and verified",()=>{const {decision}=consistentContextScenario();assert.equal(decision.outcome,"allow");assert.equal(decision.trustImpact.nextState,"verified");assert.deepEqual(decision.reasonCodes,["SCOPE_CONTEXT_CONSISTENT"]);});
test("reason codes and decision hash are deterministic",()=>{const left=consistentContextScenario().decision;const right=consistentContextScenario().decision;assert.deepEqual(left.reasonCodes,right.reasonCodes);assert.equal(left.decisionHash,right.decisionHash);assert.match(left.decisionHash,/^[a-f0-9]{64}$/);});
test("material contradiction after prior allow revokes scope under policy",()=>{const prior=consistentContextScenario().decision;const decision=evaluate((input)=>{input.previousDecision={id:prior.id,outcome:prior.outcome,trustImpact:prior.trustImpact};input.attestations[0].monitoringState="unavailable";});assert.equal(decision.outcome,"revoke_scope");assert.ok(decision.reasonCodes.includes("MATERIAL_CONTRADICTION_AFTER_ALLOW"));});
test("provider assertions must retain provider attribution",()=>{const input=consistentInput();const item=input.attestations[0];item.attestationSourceType="provider_assertion";item.evidenceStrength="asserted";item.providerOrThirdPartyIdentity=null;assert.throws(()=>validateEvidenceAttribution(item),{code:"PROVIDER_ATTRIBUTION_REQUIRED"});});
test("cryptographic strength requires verified signature evidence",()=>{const input=consistentInput();const item=input.attestations[0];item.evidenceStrength="cryptographically_attested";item.integrityMetadata.signatureVerified=false;assert.throws(()=>validateEvidenceAttribution(item),{code:"CRYPTOGRAPHIC_ATTESTATION_UNVERIFIED"});});
test("contradictions link declaration and observation evidence",()=>{const {decision}=criticalContradictionScenario();const item=decision.contradictions.find((entry)=>entry.type==="declared_simulation_observed_production");assert.ok(item);assert.ok(item.evidenceReferences.includes("evidence:declaration:scope-demo"));assert.ok(item.evidenceReferences.includes("evidence:attestation:critical"));});
test("Replay remains chronological and source-attributed",()=>{const {artifacts}=criticalContradictionScenario();assert.ok(artifacts.replay.every((item,index)=>index===0||Date.parse(item.occurredAt)>=Date.parse(artifacts.replay[index-1].occurredAt)));assert.ok(artifacts.replay.every((item)=>item.sourceType&&item.sourceIdentity&&item.correlationId));});
test("Replay does not invent an external action",()=>{for(const result of [criticalContradictionScenario(),consistentContextScenario()])assert.equal(result.artifacts.replay.some((item)=>item.stage==="external_action"),false);});
test("correction evidence creates a superseding record",()=>{const input=consistentInput();input.attestations[0].supersedesAttestationId="77777777-7777-4777-8777-777777777777";assert.equal(validateEnvironmentAttestation(input.attestations[0]).supersedesAttestationId,"77777777-7777-4777-8777-777777777777");});
test("artifacts connect evidence graph, authority lineage, Trust Memory, and Continuous Trust",()=>{const {artifacts}=criticalContradictionScenario();assert.ok(artifacts.authorityLineage.some((item)=>item.type==="AUTHORIZED_BY"));assert.ok(artifacts.evidenceGraph.relationships.some((item)=>item.type==="CONTRADICTS"));assert.equal(artifacts.trustMemory.eventKind,"runtime_change");assert.equal(artifacts.canonicalTrustState,"BLOCKED");});
