import test from "node:test";
import assert from "node:assert/strict";
import { seriousIncidentScenario } from "../src/lib/serious-incident/scenarios.ts";
import { correctionTrustMemory } from "../src/lib/serious-incident/integrations.ts";
import { buildSubmissionPackage, assertPackageMutation, assertSupersedingPackage } from "../src/lib/serious-incident/packages.ts";
import { screenPotentialRegulatoryRelevance } from "../src/lib/serious-incident/screening.ts";
import { assessmentTransitionMatrix, assertAssessmentTransition, assertAutomatedTransition, assertContainmentProgression, assertReviewerAuthorization, assertTransitionPrerequisites, containmentEvidenceLevel, deadlineProvenance } from "../src/lib/serious-incident/workflow.ts";
import { assessmentStates } from "../src/lib/serious-incident/types.ts";
import { assertDataMinimized, validateAssessmentInput, validateChronologyEvent, validateCorrectiveAction, validateDeadlineMetadata, validateEvidenceSupersession, validateExternalSubmission, validateImpact, validateReviewerDecision } from "../src/lib/serious-incident/validation.ts";

const scenario = () => structuredClone(seriousIncidentScenario());
const at = "2026-08-01T12:00:00.000Z";
const correlationId = "66666666-6666-4666-8666-666666666666";

function noTriggerInput() { return { jurisdiction:"EU",systemClassification:"other",gpaiSystemicRisk:false,highRiskUseContext:false,cybersecurityImpact:false,executionBoundaryViolation:false,outsideAuthorizedHumanControl:false,seriousMalfunction:false,thirdPartyHarm:false,fundamentalRightsImpact:false,criticalSectorImpact:false,modelProviderRole:false,deployerRole:false,contractualReportingObligation:false,organizationAwarenessRecorded:true,containmentFailure:false,evidenceCompleteness:"complete" }; }
function decision(overrides={}) { return validateReviewerDecision({ id:"77777777-7777-4777-8777-777777777777", reviewerRole:"legal_reviewer", organizationalAuthority:"authority:legal", decisionType:"reporting_decision", decision:"specialist assessment complete", targetState:"reporting_required", rationale:"Evidence and limitations were reviewed.", evidenceReferences:["evidence:1"], unresolvedIssues:[], conditions:[], decidedAt:at, approvalChain:["legal_reviewer"], supersedesDecisionId:null, conflictOfInterestDeclared:false, ...overrides }); }
function packageInput(overrides={}) { return { id:"88888888-8888-4888-8888-888888888888",version:1,state:"internal_draft",incidentSummary:"Reviewable incident evidence package.",evidenceIndex:["evidence:1"],unresolvedUncertainty:["impact under review"],evidenceIntegrityDigests:["b".repeat(64)],replayReference:"replay:1",trustMemoryReference:"memory:1",exportSchemaVersion:"serious-incident-package-v1",exportedAt:at,approvedByDecisionId:null,supersedesPackageId:null,...overrides }; }

test("canonical incident assessment validates identity, clocks, lineage, and minimized snapshot",()=>{const value=validateAssessmentInput(scenario().assessment);assert.equal(value.regulatoryContext.incidentCategory,"execution_boundary_violation");assert.equal(value.clocks.organizationAwarenessAt,"2026-08-01T10:06:00.000Z");assert.equal(value.evidenceSnapshot.promptConfigurationDigest.length,64);});
test("technical incident with complete evidence can produce no known trigger",()=>{const result=screenPotentialRegulatoryRelevance(noTriggerInput(),at);assert.equal(result.outcome,"no_known_trigger");assert.deepEqual(result.reasonCodes,["NO_KNOWN_OPERATIONAL_TRIGGER"]);});
test("potential cybersecurity trigger remains operational screening",()=>{const input=noTriggerInput();input.cybersecurityImpact=true;const result=screenPotentialRegulatoryRelevance(input,at);assert.equal(result.outcome,"potential_trigger");assert.equal(result.label,"OPERATIONAL SCREENING — NOT A LEGAL CONCLUSION");});
test("AI outside authorized human control requires specialist review",()=>{const input=noTriggerInput();input.outsideAuthorizedHumanControl=true;const result=screenPotentialRegulatoryRelevance(input,at);assert.equal(result.outcome,"specialist_review_required");assert.ok(result.recommendedReviewerRoles.includes("legal_reviewer"));});
test("multiple potential triggers are deterministic",()=>{const input=noTriggerInput();input.cybersecurityImpact=true;input.containmentFailure=true;const left=screenPotentialRegulatoryRelevance(input,at);const right=screenPotentialRegulatoryRelevance(input,at);assert.equal(left.outcome,"multiple_potential_triggers");assert.equal(left.resultDigest,right.resultDigest);});
test("changed evidence creates a new screening identity even when the outcome is unchanged",()=>{const first=noTriggerInput();const second={...first,deployerRole:true};const left=screenPotentialRegulatoryRelevance(first,at);const right=screenPotentialRegulatoryRelevance(second,at);assert.equal(left.outcome,right.outcome);assert.notEqual(left.inputDigest,right.inputDigest);assert.notEqual(left.id,right.id);});
test("missing classification and impact remain insufficient information",()=>{const input=noTriggerInput();input.jurisdiction=null;input.systemClassification=null;input.cybersecurityImpact=null;input.outsideAuthorizedHumanControl=null;input.seriousMalfunction=null;input.thirdPartyHarm=null;input.evidenceCompleteness="unknown";const result=screenPotentialRegulatoryRelevance(input,at);assert.equal(result.outcome,"insufficient_information");assert.ok(result.missingEvidence.includes("jurisdiction"));});
test("organization awareness remains distinct from technical detection",()=>{const {assessment,artifacts}=scenario();assert.notEqual(assessment.clocks.firstDetectionAt,assessment.clocks.organizationAwarenessAt);assert.ok(artifacts.replay.some((event)=>event.eventType==="organization_became_aware"));});
test("automated logic cannot set reporting_required or not_reportable",()=>{assert.throws(()=>assertAutomatedTransition("reporting_required"),{code:"AUTOMATION_LEGAL_STATE_DENIED"});assert.throws(()=>assertAutomatedTransition("not_reportable"),{code:"AUTOMATION_LEGAL_STATE_DENIED"});assert.equal(assertAutomatedTransition("potentially_reportable"),"potentially_reportable");});
test("the explicit state matrix allows only enumerated transitions",()=>{for(const from of assessmentStates){for(const to of assessmentStates){if(assessmentTransitionMatrix[from].includes(to))assert.equal(assertAssessmentTransition(from,to),to);else assert.throws(()=>assertAssessmentTransition(from,to),{code:"ASSESSMENT_TRANSITION_DENIED"});}}});
test("resolved incidents reopen through an explicit preserved transition",()=>{assert.equal(assertAssessmentTransition("resolved","reopened"),"reopened");assert.throws(()=>assertAssessmentTransition("resolved","evidence_collection"),{code:"ASSESSMENT_TRANSITION_DENIED"});});
test("unauthorized reviewer cannot set legal-review reporting decision",()=>{assert.throws(()=>assertReviewerAuthorization({workspaceRole:"reviewer",assignedRoles:["technical_reviewer"],decision:decision()}),{code:"REVIEWER_ASSIGNMENT_REQUIRED"});});
test("assigned legal reviewer can approve reporting decision",()=>{assert.equal(assertReviewerAuthorization({workspaceRole:"reviewer",assignedRoles:["legal_reviewer"],decision:decision()}).targetState,"reporting_required");});
test("technical reviewer cannot set a protected reporting state",()=>{const value=decision({reviewerRole:"technical_reviewer"});assert.throws(()=>assertReviewerAuthorization({workspaceRole:"reviewer",assignedRoles:["technical_reviewer"],decision:value}),{code:"DECISION_ROLE_DENIED"});});
test("submitted requires an approved package",()=>{const value=decision({targetState:"submitted"});assert.throws(()=>assertReviewerAuthorization({workspaceRole:"reviewer",assignedRoles:["legal_reviewer"],decision:value}),{code:"APPROVED_PACKAGE_REQUIRED"});assert.equal(assertReviewerAuthorization({workspaceRole:"reviewer",assignedRoles:["legal_reviewer"],decision:value,approvedPackageId:"package:1"}).targetState,"submitted");});
test("package approval requires correct role",()=>{const value=decision({reviewerRole:"technical_reviewer",decisionType:"submission_approval",targetState:null});assert.throws(()=>assertReviewerAuthorization({workspaceRole:"reviewer",assignedRoles:["technical_reviewer"],decision:value}),{code:"DECISION_ROLE_DENIED"});});
test("legal reviewers cannot silently rewrite technical findings",()=>{const value=decision({decisionType:"technical_finding",targetState:null});assert.throws(()=>assertReviewerAuthorization({workspaceRole:"reviewer",assignedRoles:["legal_reviewer"],decision:value}),{code:"DECISION_ROLE_DENIED"});});
test("external advisers cannot approve protected internal states",()=>{const value=decision({reviewerRole:"external_adviser"});assert.throws(()=>assertReviewerAuthorization({workspaceRole:"reviewer",assignedRoles:["external_adviser"],decision:value}),{code:"DECISION_ROLE_DENIED"});});
test("resolution fails closed while mandatory corrective actions remain open",()=>{assert.throws(()=>assertTransitionPrerequisites({from:"corrective_action_open",decision:decision({decisionType:"closure_approval",targetState:"resolved"}),hasSubmissionEvidence:true,hasRegulatorResponse:false,outstandingMandatoryCorrectiveActionIds:["action:1"]}),{code:"CORRECTIVE_ACTIONS_OUTSTANDING"});assert.doesNotThrow(()=>assertTransitionPrerequisites({from:"corrective_action_open",decision:decision({reviewerRole:"legal_reviewer",decisionType:"closure_approval",targetState:"resolved",conditions:["authorized_corrective_action_override"]}),hasSubmissionEvidence:true,hasRegulatorResponse:false,outstandingMandatoryCorrectiveActionIds:["action:1"]}));});
test("additional information requires submission or regulator response evidence",()=>{const value=decision({targetState:"additional_information_requested"});assert.throws(()=>assertTransitionPrerequisites({from:"submitted",decision:value,hasSubmissionEvidence:false,hasRegulatorResponse:false,outstandingMandatoryCorrectiveActionIds:[]}),{code:"REGULATOR_FOLLOW_UP_EVIDENCE_REQUIRED"});assert.doesNotThrow(()=>assertTransitionPrerequisites({from:"submitted",decision:value,hasSubmissionEvidence:true,hasRegulatorResponse:false,outstandingMandatoryCorrectiveActionIds:[]}));});
test("containment requested is not confirmation",()=>{assert.equal(containmentEvidenceLevel("requested"),"not_confirmed");assert.equal(containmentEvidenceLevel("provider_acknowledged"),"acknowledged_only");});
test("provider acknowledgement does not equal containment confirmation",()=>{assert.doesNotThrow(()=>assertContainmentProgression({state:"provider_acknowledged",evidenceReferences:[]}));assert.throws(()=>assertContainmentProgression({state:"provider_confirmed",evidenceReferences:[]}),{code:"CONTAINMENT_EVIDENCE_REQUIRED"});});
test("independent containment confirmation requires attributed evidence",()=>{assert.throws(()=>assertContainmentProgression({state:"independently_confirmed",evidenceReferences:["evidence:1"]}),{code:"INDEPENDENT_CONTAINMENT_SOURCE_REQUIRED"});assert.equal(assertContainmentProgression({state:"independently_confirmed",evidenceReferences:["evidence:1"],independentSource:"sensor:1"}).evidenceLevel,"independently_confirmed");});
test("impact is not inferred solely from an unconfirmed provider alert",()=>{assert.throws(()=>validateImpact({id:"99999999-9999-4999-8999-999999999999",categories:["confidentiality_impact"],affectedResourceReferences:["resource:1"],affectedDataClassifications:["confidential"],affectedOrganizations:[],affectedUserEstimate:null,durationSeconds:null,geographicScope:[],reversibility:"unknown",persistence:"unknown",independentConfirmation:false,sourceType:"provider_assertion",sourceReference:"provider-alert:1",evidenceStrength:"asserted",evidenceReferences:["provider-alert:1"],evidenceLimitations:[],confidence:"low",reviewerConfirmed:false,assessedAt:at,supersedesImpactId:null}),{code:"IMPACT_CONFIRMATION_REQUIRED"});});
test("independently confirmed external impact is preserved",()=>{const value=validateImpact({id:"99999999-9999-4999-8999-999999999999",categories:["third_party_impact"],affectedResourceReferences:["resource:1"],affectedDataClassifications:["confidential"],affectedOrganizations:["organization:third-party"],affectedUserEstimate:1,durationSeconds:30,geographicScope:["EU"],reversibility:"reversible",persistence:"bounded",independentConfirmation:true,sourceType:"independent_evidence",sourceReference:"independent:evidence:1",evidenceStrength:"independently_confirmed",evidenceReferences:["independent:evidence:1"],evidenceLimitations:[],confidence:"confirmed",reviewerConfirmed:false,assessedAt:at,supersedesImpactId:null});assert.equal(value.independentConfirmation,true);});
test("attempted access is not promoted to successful access or disclosure",()=>{const value=validateImpact({id:"99999999-9999-4999-8999-999999999998",categories:["attempted_access"],affectedResourceReferences:["resource:1"],affectedDataClassifications:[],affectedOrganizations:[],affectedUserEstimate:null,durationSeconds:null,geographicScope:[],reversibility:"unknown",persistence:"none",independentConfirmation:false,sourceType:"provider_assertion",sourceReference:"provider:1",evidenceStrength:"asserted",evidenceReferences:["provider:1"],evidenceLimitations:["Outcome unconfirmed"],confidence:"low",reviewerConfirmed:false,assessedAt:at,supersedesImpactId:null});assert.deepEqual(value.categories,["attempted_access"]);});
test("successful access does not automatically prove data disclosure",()=>{const value=validateImpact({id:"99999999-9999-4999-8999-999999999997",categories:["successful_unauthorized_access"],affectedResourceReferences:["resource:1"],affectedDataClassifications:["confidential"],affectedOrganizations:[],affectedUserEstimate:null,durationSeconds:30,geographicScope:["EU"],reversibility:"unknown",persistence:"bounded",independentConfirmation:false,sourceType:"reviewer_assessment",sourceReference:"review:1",evidenceStrength:"corroborated",evidenceReferences:["runtime:1"],evidenceLimitations:["Disclosure not established"],confidence:"high",reviewerConfirmed:true,assessedAt:at,supersedesImpactId:null});assert.equal(value.categories.includes("confidentiality_impact"),false);});
test("chronology preserves uncertain source ordering",()=>{const value=validateChronologyEvent({id:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",enterpriseId:"11111111-1111-4111-8111-111111111111",incidentId:"33333333-3333-4333-8333-333333333333",eventType:"provider_signal_received",source:"provider:1",sourceType:"provider_assertion",sourceAuthority:"provider",occurredAt:"2026-08-01T10:05:00.000Z",timestampConfidence:"low",ingestedAt:"2026-08-01T10:04:00.000Z",orderingConfidence:"unknown",evidenceReference:"provider:signal:1",integrityState:"unverified",correlationId,classification:"PROVIDER ASSERTION",summary:"Provider-supplied timestamp conflicts with ingestion ordering.",containmentState:null,supersedesEventId:null});assert.equal(value.orderingConfidence,"unknown");});
test("evidence snapshot rejects raw exploit payloads and secrets",()=>{assert.throws(()=>assertDataMinimized({raw_payload:"redacted?"}),{code:"PROHIBITED_EVIDENCE_FIELD"});assert.throws(()=>assertDataMinimized({secret:"value"}),{code:"PROHIBITED_EVIDENCE_FIELD"});});
test("draft package digest is stable and excludes unsupported legal claims",()=>{const {assessment,artifacts}=scenario();const left=buildSubmissionPackage({assessment,packageInput:packageInput(),artifacts,reviewerRole:null});const right=buildSubmissionPackage({assessment,packageInput:packageInput(),artifacts,reviewerRole:null});assert.equal(left.packageDigest,right.packageDigest);assert.match(left.humanReadableSummary,/not a legal conclusion/i);});
test("package digest covers version, state, approval and supersession envelope",()=>{const {assessment,artifacts}=scenario();const base=buildSubmissionPackage({assessment,packageInput:packageInput(),artifacts,reviewerRole:null});const changed=buildSubmissionPackage({assessment,packageInput:packageInput({id:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",version:2,supersedesPackageId:base.id}),artifacts,reviewerRole:null});assert.notEqual(base.packageDigest,changed.packageDigest);});
test("package content digest remains stable when only the version envelope changes",()=>{const {assessment,artifacts}=scenario();const base=buildSubmissionPackage({assessment,packageInput:packageInput(),artifacts,reviewerRole:null});const changed=buildSubmissionPackage({assessment,packageInput:packageInput({id:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",version:2,supersedesPackageId:base.id}),artifacts,reviewerRole:null});assert.equal(base.contentDigest,changed.contentDigest);});
test("approved package requires an authorized approval decision",()=>{const {assessment,artifacts}=scenario();assert.throws(()=>buildSubmissionPackage({assessment,packageInput:packageInput({state:"regulator_ready"}),artifacts,reviewerRole:null}),{code:"PACKAGE_APPROVAL_REQUIRED"});const value=buildSubmissionPackage({assessment,packageInput:packageInput({state:"regulator_ready",approvedByDecisionId:"77777777-7777-4777-8777-777777777777"}),artifacts,reviewerRole:"legal_reviewer"});assert.equal(value.state,"regulator_ready");});
test("approved package cannot be edited",()=>{const {assessment,artifacts}=scenario();const existing=buildSubmissionPackage({assessment,packageInput:packageInput({state:"reviewer_approved",approvedByDecisionId:"77777777-7777-4777-8777-777777777777"}),artifacts,reviewerRole:"legal_reviewer"});assert.throws(()=>assertPackageMutation(existing,packageInput()),{code:"PACKAGE_IMMUTABLE"});});
test("superseding package preserves prior version",()=>{const {assessment,artifacts}=scenario();const previous=buildSubmissionPackage({assessment,packageInput:packageInput(),artifacts,reviewerRole:null});const next=packageInput({id:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",version:2,supersedesPackageId:previous.id});assert.equal(assertSupersedingPackage(previous,next).version,2);});
test("corrective action completion requires evidence and validation remains separate",()=>{const base={id:"cccccccc-cccc-4ccc-8ccc-cccccccccccc",actionType:"policy_updated",actionOwner:"human:owner",accountableApprover:"human:approver",targetDate:null,completionDate:at,completionEvidenceReferences:[],completionSourceType:"owner_evidence",validationEvidenceReferences:[],residualRisk:"under review",reviewerApprovalDecisionId:null,effectivenessState:"completed_unvalidated",linkedContradictionReference:null,linkedFindingReference:null,linkedPackageReference:null,supersedesCorrectiveActionId:null};assert.throws(()=>validateCorrectiveAction(base),{code:"COMPLETION_EVIDENCE_REQUIRED"});const completed=validateCorrectiveAction({...base,completionEvidenceReferences:["evidence:completion"]});assert.equal(completed.effectivenessState,"completed_unvalidated");assert.throws(()=>validateCorrectiveAction({...base,effectivenessState:"validated",completionEvidenceReferences:["evidence:completion"]}),{code:"VALIDATION_EVIDENCE_REQUIRED"});const validated=validateCorrectiveAction({...base,effectivenessState:"validated",completionEvidenceReferences:["evidence:completion"],completionSourceType:"reviewer_validation",validationEvidenceReferences:["evidence:validation"],reviewerApprovalDecisionId:"77777777-7777-4777-8777-777777777777"});assert.equal(validated.effectivenessState,"validated");assert.throws(()=>validateCorrectiveAction({...base,completionEvidenceReferences:["provider:ack"],completionSourceType:"provider_assertion"}),{code:"PROVIDER_ACKNOWLEDGEMENT_NOT_COMPLETION"});});
test("reviewer-supplied deadline preserves source and rationale",()=>{const value=deadlineProvenance({deadline:"2026-08-03T12:00:00.000Z",sourceType:"reviewer_supplied",ruleSource:"legal-review:1",rationale:"Reviewer-entered calculation.",timezone:"Europe/Madrid",approvedBy:"reviewer:1"});assert.equal(value.sourceType,"reviewer_supplied");assert.throws(()=>deadlineProvenance({deadline:"2026-08-03T12:00:00.000Z",sourceType:"unknown"}),{code:"DEADLINE_SOURCE_REQUIRED"});});
test("deadline metadata validates provenance without calculating a legal clock",()=>{const value=validateDeadlineMetadata({deadline:"2026-08-03T12:00:00.000Z",sourceType:"reviewer_supplied",ruleSource:"review:1",rationale:"Supplied by authorized reviewer.",timezone:"Europe/Madrid",uncertainty:"Specialist confirmation pending.",approvedBy:"reviewer:1"});assert.equal(value.sourceType,"reviewer_supplied");});
test("evidence corrections preserve distinct original and corrected records",()=>{const value=validateEvidenceSupersession({id:"dddddddd-dddd-4ddd-8ddd-dddddddddddd",recordType:"responsibility_attribution",originalRecordId:"eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",correctedRecordId:"ffffffff-ffff-4fff-8fff-ffffffffffff",correctionReason:"Independent evidence changed attribution.",evidenceReferences:["evidence:correction"],approvedByDecisionId:null,correctedAt:at});assert.notEqual(value.originalRecordId,value.correctedRecordId);});
test("external acknowledgement records receipt only with exact package digest",()=>{const value=validateExternalSubmission({id:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaab",state:"acknowledged",destinationAuthority:"authority:1",jurisdiction:"EU",submissionChannel:"external_portal",externalReference:"masked:123",submittedAt:at,submittingActor:"22222222-2222-4222-8222-222222222222",packageId:"88888888-8888-4888-8888-888888888888",packageVersion:1,packageDigest:"a".repeat(64),acknowledgementReference:"receipt:1",acknowledgementAt:at,followUpDeadline:null,followUpDeadlineMetadata:null,limitations:["Receipt is not acceptance"],supersedesSubmissionId:null});assert.equal(value.state,"acknowledged");assert.equal(value.packageDigest.length,64);});
test("regulator response states require attributed external evidence",()=>{const base={id:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaac",state:"rejected",destinationAuthority:"authority:1",jurisdiction:"EU",submissionChannel:"external_portal",externalReference:"masked:456",submittedAt:at,submittingActor:null,packageId:"88888888-8888-4888-8888-888888888888",packageVersion:1,packageDigest:"a".repeat(64),acknowledgementReference:null,acknowledgementAt:null,followUpDeadline:null,followUpDeadlineMetadata:null,limitations:[],supersedesSubmissionId:null};assert.throws(()=>validateExternalSubmission(base),{code:"REGULATOR_RESPONSE_EVIDENCE_REQUIRED"});assert.equal(validateExternalSubmission({...base,acknowledgementReference:"response:1",acknowledgementAt:at}).state,"rejected");});
test("Evidence Graph relationships retain required direction and typed endpoint semantics",()=>{const {artifacts}=scenario();const directions=artifacts.evidenceGraph.relationships.map((edge)=>`${edge.fromType}:${edge.from}|${edge.type}|${edge.toType}:${edge.to}`);assert.ok(directions.some((edge)=>edge.includes("incident:")&&edge.includes("|INVOLVES|ai_system:")));assert.ok(directions.some((edge)=>edge.includes("ai_system:")&&edge.includes("|OPERATED_AS|ai_agent:")));assert.ok(directions.some((edge)=>edge.includes("runtime:")&&edge.includes("|RAN_IN|environment_attestation:")));assert.ok(directions.some((edge)=>edge.includes("runtime:")&&edge.includes("|AUTHORIZED_BY|scope_authorization_lease:")));assert.ok(directions.some((edge)=>edge.includes("incident:")&&edge.includes("|DETECTED_BY|monitor:")));assert.ok(directions.some((edge)=>edge.includes("ai_system:")&&edge.includes("|DERIVED_FROM|provider:")));assert.ok(directions.some((edge)=>edge.includes("incident:")&&edge.includes("|AFFECTED|affected_resource:")));});
test("Replay separates technical, screening, and reviewer layers without unsupported action",()=>{const {artifacts}=scenario();assert.ok(artifacts.replay.some((event)=>event.classification==="TECHNICAL EVIDENCE"));assert.ok(artifacts.replay.some((event)=>event.classification==="CYBER SENTINELS OPERATIONAL SCREENING"));assert.equal(artifacts.replay.some((event)=>event.eventType==="submission_made"),false);});
test("Trust Memory records material events without arbitrary numeric penalties",()=>{const {artifacts}=scenario();assert.ok(artifacts.trustMemory.some((event)=>event.eventKind==="serious_incident_opened"));assert.equal(JSON.stringify(artifacts.trustMemory).includes("penalty"),false);});
test("corrected attribution creates a superseding material event",()=>{const value=correctionTrustMemory({incidentId:"incident:1",subject:"agent:1",originalClassification:"provider_fault_suspected",revisedClassification:"infrastructure_fault_confirmed",evidenceReferences:["evidence:correction"],actor:"reviewer:1",occurredAt:at,supersedesEventId:"memory:old"});assert.equal(value.supersedesEventId,"memory:old");assert.equal(value.eventKind,"incident_classification_revised");});
