-- Read-only RLS, grant and security-invoker validation.
do $$
declare expected_tables text[]:=array['execution_context_declarations','environment_attestations','scope_authorization_leases','scope_continuity_decisions','scope_decision_attestations','context_contradiction_events','scope_continuity_reviewer_actions','incident_regulatory_assessments','incident_responsibility_roles','incident_chronology_events','incident_evidence_snapshots','incident_impact_assessments','incident_regulatory_trigger_findings','incident_reviewer_decisions','incident_submission_packages','incident_external_submissions','incident_corrective_actions','incident_evidence_supersessions']; missing text[];
begin
  select array_agg(name) into missing from unnest(expected_tables) name where not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=name and c.relrowsecurity);
  if cardinality(coalesce(missing,'{}'))>0 then raise exception 'EPIC_26_27_RLS_DISABLED: %',array_to_string(missing,', '); end if;
  if exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name=any(expected_tables) and grantee in ('anon','authenticated') and privilege_type in ('INSERT','UPDATE','DELETE','TRUNCATE')) then raise exception 'EPIC_26_27_UNSAFE_CLIENT_WRITE_GRANT'; end if;
  if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('persist_scope_continuity_decision_v1','persist_serious_incident_case_v1','append_serious_incident_record_v1') and has_function_privilege('authenticated',p.oid,'EXECUTE')) then raise exception 'EPIC_26_27_UNSAFE_RPC_GRANT'; end if;
  if exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('scope_continuity_replay','incident_reporting_replay') and coalesce(c.reloptions,'{}')@>array['security_invoker=false']) then raise exception 'EPIC_26_27_REPLAY_NOT_SECURITY_INVOKER'; end if;
  if not (select relrowsecurity from pg_class where oid='public.provider_operational_health_snapshots'::regclass) then raise exception 'PROVIDER_OPERATIONAL_HEALTH_RLS_DISABLED'; end if;
  if has_table_privilege('anon','public.provider_operational_health_snapshots','SELECT,INSERT,UPDATE,DELETE') or has_table_privilege('authenticated','public.provider_operational_health_snapshots','SELECT,INSERT,UPDATE,DELETE') then raise exception 'PROVIDER_OPERATIONAL_HEALTH_UNSAFE_CLIENT_GRANT'; end if;
  if not (select relrowsecurity from pg_class where oid='public.provider_health_snapshots'::regclass) then raise exception 'PROVIDER_CONSENSUS_HEALTH_RLS_DISABLED'; end if;
  if has_table_privilege('anon','public.provider_health_snapshots','SELECT,INSERT,UPDATE,DELETE') or has_table_privilege('authenticated','public.provider_health_snapshots','INSERT,UPDATE,DELETE') then raise exception 'PROVIDER_HEALTH_UNSAFE_CLIENT_GRANT'; end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='provider_health_snapshots' and policyname='tenant reads provider health' and roles=array['authenticated']::name[] and cmd='SELECT' and regexp_replace(qual,'\s+','','g')=regexp_replace('user_can_access_trust_workspace(enterprise_id)','\s+','','g')) then raise exception 'PROVIDER_HEALTH_POLICY_DRIFT'; end if;
end $$;
