import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

export default async function IdentityVerificationPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect(`/login?next=/dashboard/identity/verifications/${id}`);
  const request = await supabase.from("identity_verification_requests").select("*").eq("id", id).maybeSingle(); if (!request.data) notFound();
  const [evidence, confidence, transactions] = await Promise.all([supabase.from("identity_signal_evidence").select("*").eq("verification_request_id", id).order("created_at"), supabase.from("identity_confidence_results").select("*").eq("verification_request_id", id).maybeSingle(), supabase.from("identity_provider_transactions").select("*").eq("verification_request_id", id).order("created_at")]);
  return <main className="min-h-screen bg-black px-6 py-10 text-zinc-100"><div className="mx-auto max-w-6xl"><Link href="/dashboard/identity" className="text-sm text-cyan-400">← Identity Signals</Link><div className="mt-5 flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-semibold">Verification detail</h1><p className="mt-2 font-mono text-xs text-zinc-500">{id}</p></div><span className="h-fit rounded border border-zinc-700 px-3 py-1 text-sm">{request.data.status}</span></div><section className="mt-8 grid gap-5 md:grid-cols-3"><div className="rounded-xl border border-zinc-800 p-5"><p className="text-sm text-zinc-500">Confidence</p><p className="mt-2 text-3xl font-semibold">{confidence.data?.score ?? 0}</p><p className="mt-1 text-sm text-zinc-400">{confidence.data?.status ?? "INSUFFICIENT_EVIDENCE"}</p></div><div className="rounded-xl border border-zinc-800 p-5"><p className="text-sm text-zinc-500">Evidence records</p><p className="mt-2 text-3xl font-semibold">{evidence.data?.length ?? 0}</p></div><div className="rounded-xl border border-zinc-800 p-5"><p className="text-sm text-zinc-500">Provider transactions</p><p className="mt-2 text-3xl font-semibold">{transactions.data?.length ?? 0}</p></div></section><section className="mt-8 grid gap-3">{evidence.data?.map((row) => <article key={row.id} className="rounded-xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">{row.signal_type}</h2><span className="text-sm text-zinc-400">{row.outcome}</span></div><p className="mt-2 text-sm text-zinc-500">{row.provider_id} · server verified: {row.server_verified ? "yes" : "no"} · contribution: {row.server_verified ? row.confidence : 0}</p><p className="mt-2 text-xs text-zinc-600">{row.reason_codes.join(", ")}</p></article>)}</section></div></main>;
}
