import type { MetadataRoute } from "next";

const protectedPaths = [
  "/admin/",
  "/api/admin/",
  "/api/demo/seed",
  "/api/providers",
  "/api/status",
  "/api-docs",
  "/architecture",
  "/back-office",
  "/command-center",
  "/dashboard/",
  "/demo-lab",
  "/developer-console",
  "/developers/",
  "/evidence-vault",
  "/launch-console",
  "/launch-control",
  "/mission-control",
  "/qa-console",
  "/signals",
  "/status",
  "/api/ai-governance/analyze",
  "/api/hpg/analyze",
  "/api/origin/analyze",
  "/api/reality-twin/analyze",
  "/api/trust-algorithm/run",
  "/api/trust-events",
  "/api/trust-recovery",
  "/trust-graph-engine",
  "/trust-intelligence",
  "/trust-prediction",
  "/verification-queue",
  "/workspace/",
];

const experimentalPaths = [
  "/agent-passport",
  "/agent-registry",
  "/deepfake-detection",
  "/global-trust",
  "/human-presence-",
  "/marketplace-trust",
  "/origin-",
  "/permissions-firewall",
  "/policy-engine",
  "/profile",
  "/reality-",
  "/revocation-engine",
  "/synthetic-counterpart",
  "/trust-algorithm",
  "/trust-badges",
  "/trust-embeds",
  "/trust-evaluation-lab",
  "/trust-fabric",
  "/trust-feed",
  "/trust-graph",
  "/trust-ledger",
  "/trust-os",
  "/trust-radar",
  "/trust-recovery",
  "/trust-registry",
  "/trust-seal-authority",
  "/trust-timeline",
  "/video-verification",
  "/step-up-verification",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: [...protectedPaths, ...experimentalPaths],
    },
    host: "https://www.cybersentinels.com",
  };
}
