import { buildSeriousIncidentArtifacts } from "./integrations.ts";
import { screenPotentialRegulatoryRelevance } from "./screening.ts";
import type { SeriousIncidentAssessmentInput } from "./types.ts";

const enterpriseId = "11111111-1111-4111-8111-111111111111";
const actorId = "22222222-2222-4222-8222-222222222222";

export function seriousIncidentScenario() {
  const assessment: SeriousIncidentAssessmentInput = {
    id: "33333333-3333-4333-8333-333333333333", enterpriseId, state: "evidence_collection", createdAt: "2026-08-01T10:06:00.000Z",
    identity: { agentId: "agent:customer-support:42", aiSystemId: "system:customer-support", modelProvider: "provider:example-model", modelFamily: "example-family", modelVersion: "2026-07", agentVersion: "4.8.1", deploymentReference: "deployment:prod:2026-07-31", runtimeSessionReference: "runtime:session:incident-42", responsibleHuman: actorId, accountableOrganization: "organization:example-enterprise", systemOwner: actorId, incidentOwner: actorId },
    regulatoryContext: { jurisdiction: "EU", frameworkReference: "reviewer-supplied:EU-AI-Act-context", systemClassification: "classification_requires_specialist_confirmation", gpaiSystemicRiskStatus: "not_supplied", organizationalRole: "deployer", incidentCategory: "execution_boundary_violation", providerClassification: "provider_security_signal", technicalClassification: "production_boundary_contradiction", operationalScreeningClassification: "specialist_review_required", complianceReviewClassification: null, legalReviewClassification: null, regulatorClassification: null },
    clocks: { firstOccurrenceAt: "2026-08-01T10:00:00.000Z", firstProviderObservationAt: "2026-08-01T10:01:00.000Z", firstRuntimeSecurityObservationAt:"2026-08-01T10:01:30.000Z", firstCyberSentinelsIngestionAt: "2026-08-01T10:02:00.000Z", firstDetectionAt: "2026-08-01T10:02:30.000Z", firstHumanReviewAt: "2026-08-01T10:05:00.000Z", organizationAwarenessAt: "2026-08-01T10:06:00.000Z", materialityDeterminationAt: null, containmentStartedAt: "2026-08-01T10:07:00.000Z", containmentConfirmedAt: null, reportingDecisionAt: null, submissionAt: null, regulatorAcknowledgementAt: null, recoveryAt: null, closureAt: null },
    references: { affectedSystems: ["system:customer-support"], affectedOrganizations: ["organization:example-enterprise"], affectedThirdParties: [], impactSummary: "A runtime observation contradicted the declared execution boundary. External impact is not yet confirmed.", evidenceCompleteness: "partial", evidenceLimitations: ["Containment was requested but is not independently confirmed.", "Third-party impact remains under review."], replayReference: "replay:incident-42", trustMemoryReference: "memory:incident-42", evidenceGraphReference: "graph:incident-42", authorityLineageReference: "authority:incident-42", environmentAttestationReference: "attestation:production-observation", scopeContinuityDecisionReference: "scope-decision:deny-42" },
    responsibilityRoles: [
      { id: "44444444-4444-4444-8444-444444444441", roleType: "incident_owner", partyType: "human", partyReference: actorId, authorityReference: "authority:incident-owner", assignedAt: "2026-08-01T10:06:00.000Z", assignedBy: actorId, supersedesRoleId: null },
      { id: "44444444-4444-4444-8444-444444444442", roleType: "legal_reviewer", partyType: "human", partyReference: "55555555-5555-4555-8555-555555555555", authorityReference: "authority:legal-review", assignedAt: "2026-08-01T10:06:00.000Z", assignedBy: actorId, supersedesRoleId: null },
      { id: "44444444-4444-4444-8444-444444444443", roleType: "model_provider", partyType: "provider", partyReference: "provider:example-model", authorityReference: null, assignedAt: "2026-08-01T10:06:00.000Z", assignedBy: actorId, supersedesRoleId: null },
      { id: "44444444-4444-4444-8444-444444444444", roleType: "runtime_security_provider", partyType: "provider", partyReference: "provider:runtime-security", authorityReference: null, assignedAt: "2026-08-01T10:06:00.000Z", assignedBy: actorId, supersedesRoleId: null },
    ],
    evidenceSnapshot: { id: "55555555-5555-4555-8555-555555555555", capturedAt: "2026-08-01T10:02:30.000Z", aiSystemIdentity: "system:customer-support", agentIdentity: "agent:customer-support:42", modelProvider: "provider:example-model", modelFamily: "example-family", modelVersion: "2026-07", agentVersion: "4.8.1", promptConfigurationDigest: "a".repeat(64), maskedPromptReference: "prompt-config:masked:42", toolConfiguration: ["connector:crm:read-only"], connectorConfiguration: ["crm:masked-config-reference"], authorityGrantReferences: ["authority:runtime-42"], scopeAuthorizationLeaseReference: "scope-lease:42", declaredEnvironmentReference: "context:declared-simulation", configuredEnvironmentReference: "context:harness-simulation", observedEnvironmentReferences: ["attestation:production-observation"], effectiveAccess: ["network:external-observed"], permittedTargets: ["target:simulation-crm"], observedTargets: ["target:production-crm"], credentialStateClassification: "credential_present_masked_reference_only", policyVersion: "scope-continuity:1.0.0", monitoringProviderHealth: "available", unresolvedFindings: ["production_boundary_contradiction"], approvedExceptionReferences: [], responsibleHumanState: "available", deploymentApprovalReference: "deployment:prod:2026-07-31", assuranceBaselineReference: "assurance:baseline:42", containmentReadiness: "provider_request_available", providerEvidenceReferences: ["provider-signal:42"], sourceEvidenceVersions: [{sourceType:"provider_signal",sourceReference:"provider-signal:42",version:"1",digest:"b".repeat(64)}], missingEvidence: ["independent_containment_confirmation"], evidenceLimitations: ["No independent containment confirmation."], supersedesSnapshotId: null },
    screeningInput: { jurisdiction: "EU", systemClassification: "classification_requires_specialist_confirmation", gpaiSystemicRisk: null, highRiskUseContext: null, cybersecurityImpact: true, executionBoundaryViolation: true, outsideAuthorizedHumanControl: true, seriousMalfunction: null, thirdPartyHarm: null, fundamentalRightsImpact: null, criticalSectorImpact: false, modelProviderRole: false, deployerRole: true, contractualReportingObligation: null, organizationAwarenessRecorded: true, containmentFailure: null, evidenceCompleteness: "partial" },
  };
  const screening = screenPotentialRegulatoryRelevance(assessment.screeningInput, assessment.createdAt);
  const artifacts = buildSeriousIncidentArtifacts(assessment, screening, "66666666-6666-4666-8666-666666666666");
  return { assessment, screening, artifacts };
}
