import "server-only";
import { hashCanonical } from "../trust-core/hash.ts";
import { buildSeriousIncidentArtifacts } from "./integrations.ts";
import { buildSubmissionPackage, assertSupersedingPackage } from "./packages.ts";
import { seriousIncidentRepository } from "./repository.ts";
import { screenPotentialRegulatoryRelevance } from "./screening.ts";
import type { ReviewerRole, WorkspaceRole } from "./types.ts";
import { assertContainmentProgression, assertReviewerAuthorization, deadlineProvenance } from "./workflow.ts";
import { assertSeriousIncidentRecordShape, validateAssessmentInput, validateChronologyEvent, validateCorrectiveAction, validateDeadlineMetadata, validateEvidenceSnapshot, validateEvidenceSupersession, validateExternalSubmission, validateImpact, validatePackage, validateReviewerDecision } from "./validation.ts";

function conflict(code: string, message: string): never { throw Object.assign(new Error(message), { status: 409, code }); }

export async function createSeriousIncidentAssessment(input: { enterpriseId: string; actorId: string; value: unknown; correlationId: string }) {
  const assessment = validateAssessmentInput(input.value);
  if (assessment.enterpriseId !== input.enterpriseId) throw Object.assign(new Error("Cross-enterprise incident input is denied."), { status: 403, code: "CROSS_ENTERPRISE_REFERENCE" });
  if (assessment.state !== "draft" && assessment.state !== "evidence_collection") throw Object.assign(new Error("A new incident assessment must start in draft or evidence collection."), { status: 400, code: "INITIAL_STATE_INVALID" });
  if (!assessment.responsibilityRoles.some((role) => role.partyReference === input.actorId && ["incident_owner", "system_owner"].includes(role.roleType))) throw Object.assign(new Error("The creating actor must be recorded as an incident or system owner."), { status: 403, code: "INCIDENT_OWNER_REQUIRED" });
  if (assessment.responsibilityRoles.some((role) => role.assignedBy !== input.actorId)) throw Object.assign(new Error("Initial responsibility assignments must be attributed to the creating actor."), { status: 403, code: "RESPONSIBILITY_ASSIGNER_MISMATCH" });
  const repository = seriousIncidentRepository(); const existing = await repository.assessment(input.enterpriseId, assessment.id);
  if (existing) { if (String((existing as Record<string, unknown>).immutable_hash) !== hashCanonical(assessment)) conflict("INCIDENT_ID_CONFLICT", "The incident identifier is already bound to different immutable evidence."); return { assessmentId: assessment.id, idempotentReplay: true }; }
  const screening = screenPotentialRegulatoryRelevance(assessment.screeningInput, assessment.createdAt);
  const artifacts = buildSeriousIncidentArtifacts(assessment, screening, input.correlationId);
  await repository.create(assessment, screening, artifacts, input.actorId, input.correlationId);
  return { assessment, screening, artifacts, idempotentReplay: false };
}

async function ensureCase(repository: ReturnType<typeof seriousIncidentRepository>, enterpriseId: string, incidentId: string) { const incident = await repository.assessment(enterpriseId, incidentId); if (!incident) throw Object.assign(new Error("Incident assessment was not found."), { status: 404, code: "INCIDENT_NOT_FOUND" }); return incident; }

export async function appendIncidentChronology(input: { enterpriseId: string; actorId: string; incidentId: string; value: unknown; correlationId: string }) {
  const repository = seriousIncidentRepository(); await ensureCase(repository, input.enterpriseId, input.incidentId); assertSeriousIncidentRecordShape(input.value, "chronology"); const deadlineMetadata=validateDeadlineMetadata((input.value as Record<string,unknown>).deadlineMetadata); const event = {...validateChronologyEvent(input.value),deadlineMetadata};
  if (event.enterpriseId !== input.enterpriseId || event.incidentId !== input.incidentId || event.correlationId !== input.correlationId) throw Object.assign(new Error("Chronology tenant, incident, or correlation reference is invalid."), { status: 403, code: "CHRONOLOGY_REFERENCE_MISMATCH" });
  if(event.deadlineMetadata){deadlineProvenance({deadline:event.deadlineMetadata.deadline,sourceType:event.deadlineMetadata.sourceType,ruleSource:event.deadlineMetadata.ruleSource,rationale:event.deadlineMetadata.rationale,timezone:event.deadlineMetadata.timezone,approvedBy:event.deadlineMetadata.approvedBy});if(event.deadlineMetadata.sourceType==="reviewer_supplied"&&event.deadlineMetadata.approvedBy!==input.actorId)throw Object.assign(new Error("Reviewer-supplied deadline approval must match the authenticated actor."),{status:403,code:"DEADLINE_APPROVER_MISMATCH"});}
  if (event.containmentState) assertContainmentProgression({ state: event.containmentState, evidenceReferences: event.evidenceReference ? [event.evidenceReference] : [], independentSource: event.containmentState === "independently_confirmed" ? event.source : null });
  await repository.append(input.enterpriseId, input.incidentId, "chronology", event as unknown as Record<string, unknown>, input.actorId, input.correlationId); return event;
}

export async function appendIncidentImpact(input: { enterpriseId: string; actorId: string; incidentId: string; value: unknown; correlationId: string }) { const repository = seriousIncidentRepository(); await ensureCase(repository, input.enterpriseId, input.incidentId); assertSeriousIncidentRecordShape(input.value, "impact"); const impact = validateImpact(input.value); await repository.append(input.enterpriseId, input.incidentId, "impact", impact as unknown as Record<string, unknown>, input.actorId, input.correlationId); return impact; }

export async function appendReviewerDecision(input: { enterpriseId: string; actorId: string; workspaceRole: WorkspaceRole; incidentId: string; value: unknown; correlationId: string }) {
  const repository = seriousIncidentRepository(); await ensureCase(repository, input.enterpriseId, input.incidentId); assertSeriousIncidentRecordShape(input.value, "reviewerDecision"); const rawApprovedPackageId=typeof (input.value as Record<string,unknown>).approvedPackageId==="string"?String((input.value as Record<string,unknown>).approvedPackageId):null;if(rawApprovedPackageId&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(rawApprovedPackageId))throw Object.assign(new Error("approvedPackageId must be a UUID."),{status:400,code:"PACKAGE_REFERENCE_INVALID"}); const decision = {...validateReviewerDecision(input.value),approvedPackageId:rawApprovedPackageId}; const assignedRoles = await repository.assignedReviewerRoles(input.enterpriseId, input.incidentId, input.actorId);
  const approvedPackageId = decision.approvedPackageId ?? null;
  if (decision.targetState === "submitted" && approvedPackageId) {
    const bundle = await repository.bundle(input.enterpriseId, input.incidentId);
    const packageRecord = (bundle.incident_submission_packages as Array<Record<string, unknown>>).find((row) => row.id === approvedPackageId && ["reviewer_approved", "regulator_ready", "submitted"].includes(String(row.state)));
    const submissionRecord = (bundle.incident_external_submissions as Array<Record<string, unknown>>).find((row) => row.package_id === approvedPackageId && ["transferred", "acknowledged", "supplemented", "closed"].includes(String(row.state)));
    if (!packageRecord || !submissionRecord) throw Object.assign(new Error("Submitted state requires the exact approved package and a linked external submission record."), { status: 409, code: "SUBMISSION_EVIDENCE_REQUIRED" });
  }
  assertReviewerAuthorization({ workspaceRole: input.workspaceRole, assignedRoles, decision, approvedPackageId });
  await repository.append(input.enterpriseId, input.incidentId, "reviewer_decision", decision as unknown as Record<string, unknown>, input.actorId, input.correlationId); return decision;
}

export async function appendSubmissionPackage(input: { enterpriseId: string; actorId: string; incidentId: string; value: unknown; correlationId: string }) {
  const repository = seriousIncidentRepository(); const assessmentRow = await ensureCase(repository, input.enterpriseId, input.incidentId); assertSeriousIncidentRecordShape(input.value, "submissionPackage"); const packageInput = validatePackage(input.value); let reviewerRole: ReviewerRole | null = null;
  if (packageInput.approvedByDecisionId) { const decision = await repository.reviewerDecision(input.enterpriseId, input.incidentId, packageInput.approvedByDecisionId); if (!decision) throw Object.assign(new Error("Package approval decision was not found."), { status: 409, code: "PACKAGE_APPROVAL_NOT_FOUND" }); reviewerRole = String((decision as Record<string, unknown>).reviewer_role) as ReviewerRole; }
  if (packageInput.supersedesPackageId) { const prior = await repository.package(input.enterpriseId, input.incidentId, packageInput.supersedesPackageId); if (!prior) throw Object.assign(new Error("Superseded package was not found."), { status: 409, code: "PACKAGE_SUPERSESSION_NOT_FOUND" }); assertSupersedingPackage({ id: String((prior as Record<string, unknown>).id), version: Number((prior as Record<string, unknown>).version) }, packageInput); }
  const row = assessmentRow as Record<string, unknown>; const assessment = validateAssessmentInput(row.canonical_case ?? row.case_payload); const bundle = await repository.bundle(input.enterpriseId, input.incidentId); const packageRecord = buildSubmissionPackage({ assessment, packageInput, reviewerRole, artifacts: bundle });
  await repository.append(input.enterpriseId, input.incidentId, "submission_package", packageRecord as unknown as Record<string, unknown>, input.actorId, input.correlationId); return packageRecord;
}

export async function appendExternalSubmission(input: { enterpriseId: string; actorId: string; incidentId: string; value: unknown; correlationId: string }) { const repository = seriousIncidentRepository(); await ensureCase(repository, input.enterpriseId, input.incidentId); const assignedRoles = await repository.assignedReviewerRoles(input.enterpriseId, input.incidentId, input.actorId); if (!assignedRoles.some((role) => ["regulator_liaison", "executive_approver"].includes(role))) throw Object.assign(new Error("An assigned regulator liaison or executive approver must record external submission evidence."), { status: 403, code: "SUBMISSION_ACTOR_NOT_AUTHORIZED" }); const submission = validateExternalSubmission(input.value); const packageRecord = await repository.package(input.enterpriseId, input.incidentId, submission.packageId); if (!packageRecord || !["reviewer_approved", "regulator_ready", "submitted"].includes(String((packageRecord as Record<string, unknown>).state)) || String((packageRecord as Record<string, unknown>).package_digest) !== submission.packageDigest) throw Object.assign(new Error("External submission requires the exact approved immutable package."), { status: 409, code: "APPROVED_PACKAGE_MISMATCH" }); await repository.append(input.enterpriseId, input.incidentId, "external_submission", submission as unknown as Record<string, unknown>, input.actorId, input.correlationId); return submission; }

export async function appendCorrectiveAction(input: { enterpriseId: string; actorId: string; incidentId: string; value: unknown; correlationId: string }) { const repository = seriousIncidentRepository(); await ensureCase(repository, input.enterpriseId, input.incidentId); const action = validateCorrectiveAction(input.value); await repository.append(input.enterpriseId, input.incidentId, "corrective_action", action as unknown as Record<string, unknown>, input.actorId, input.correlationId); return action; }

export async function appendEvidenceSnapshot(input:{enterpriseId:string;actorId:string;incidentId:string;value:unknown;correlationId:string}){const repository=seriousIncidentRepository();await ensureCase(repository,input.enterpriseId,input.incidentId);const snapshot=validateEvidenceSnapshot(input.value);if(!snapshot.supersedesSnapshotId)throw Object.assign(new Error("A later evidence snapshot must supersede the preserved incident-time snapshot."),{status:409,code:"SNAPSHOT_SUPERSESSION_REQUIRED"});const bundle=await repository.bundle(input.enterpriseId,input.incidentId);if(!(bundle.incident_evidence_snapshots as Array<Record<string,unknown>>).some((row)=>row.id===snapshot.supersedesSnapshotId))throw Object.assign(new Error("The superseded snapshot was not found in this incident."),{status:409,code:"SNAPSHOT_SUPERSESSION_NOT_FOUND"});await repository.append(input.enterpriseId,input.incidentId,"evidence_snapshot",snapshot as unknown as Record<string,unknown>,input.actorId,input.correlationId);return snapshot;}

export async function appendEvidenceCorrection(input:{enterpriseId:string;actorId:string;incidentId:string;value:unknown;correlationId:string}){const repository=seriousIncidentRepository();await ensureCase(repository,input.enterpriseId,input.incidentId);const correction=validateEvidenceSupersession(input.value);if(correction.approvedByDecisionId&&!await repository.reviewerDecision(input.enterpriseId,input.incidentId,correction.approvedByDecisionId))throw Object.assign(new Error("Correction approval decision was not found."),{status:409,code:"CORRECTION_APPROVAL_NOT_FOUND"});await repository.append(input.enterpriseId,input.incidentId,"evidence_supersession",correction as unknown as Record<string,unknown>,input.actorId,input.correlationId);return correction;}
