import {
  assessmentStates,
  chronologyEventTypes,
  containmentStates,
  decisionTypes,
  impactCategories,
  incidentCategories,
  organizationRoles,
  packageStates,
  responsibilityRoleTypes,
  reviewerRoles,
  type CorrectiveActionInput,
  type EvidenceSnapshotInput,
  type EvidenceSupersessionInput,
  type ExternalSubmissionInput,
  type ImpactAssessmentInput,
  type IncidentChronologyEvent,
  type ReviewerDecisionInput,
  type SeriousIncidentAssessmentInput,
  type SubmissionPackageInput,
} from "./types.ts";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SHA256 = /^[a-f0-9]{64}$/;
const SAFE_REFERENCE = /^[A-Za-z0-9_.:@/ -]{1,256}$/;
const PROHIBITED_KEYS = /(^|_)(password|secret|token|cookie|credential|private_key|raw_payload|exploit_payload|full_prompt)(_|$)/i;

function invalid(code: string, message: string): never { throw Object.assign(new TypeError(message), { code }); }
function object(value: unknown, name: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) invalid("OBJECT_REQUIRED", `${name} must be an object.`); return value as Record<string, unknown>; }
function string(value: unknown, name: string, max = 2_000) { const result = typeof value === "string" ? value.trim() : ""; if (!result || result.length > max) invalid("STRING_INVALID", `${name} is invalid.`); return result; }
function optionalString(value: unknown, name: string, max = 2_000) { if (value === null || value === undefined || value === "") return null; return string(value, name, max); }
function timestamp(value: unknown, name: string) { const result = string(value, name, 64); if (Number.isNaN(Date.parse(result))) invalid("TIMESTAMP_INVALID", `${name} must be an ISO timestamp.`); return new Date(result).toISOString(); }
function optionalTimestamp(value: unknown, name: string) { return value === null || value === undefined || value === "" ? null : timestamp(value, name); }
function uuid(value: unknown, name: string) { const result = string(value, name, 64); if (!UUID.test(result)) invalid("UUID_INVALID", `${name} must be a UUID.`); return result; }
function list(value: unknown, name: string, maxItems = 100) { if (!Array.isArray(value) || value.length > maxItems) invalid("ARRAY_INVALID", `${name} must be a bounded array.`); return value.map((item, index) => string(item, `${name}[${index}]`, 512)); }
function optionalNonnegativeInteger(value: unknown, name: string) { if (value === null || value === undefined || value === "") return null; if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0) invalid("NUMBER_INVALID", `${name} must be a non-negative integer.`); return value; }
function enumValue<T extends readonly string[]>(value: unknown, values: T, name: string): T[number] { const result = string(value, name, 100); if (!values.includes(result)) invalid("ENUM_INVALID", `${name} is invalid.`); return result as T[number]; }
function assertKnownFields(value: unknown, allowed: readonly string[], name: string) { const record = object(value, name); const unknown = Object.keys(record).filter((key) => !allowed.includes(key)); if (unknown.length) invalid("UNKNOWN_FIELD", `${name} contains unsupported fields: ${unknown.join(", ")}.`); }

const recordFields = {
  chronology: ["id","enterpriseId","incidentId","eventType","source","sourceType","sourceAuthority","occurredAt","timestampConfidence","ingestedAt","orderingConfidence","evidenceReference","integrityState","correlationId","classification","summary","containmentState","deadlineMetadata","supersedesEventId"],
  impact: ["id","categories","affectedResourceReferences","affectedDataClassifications","affectedOrganizations","affectedUserEstimate","durationSeconds","geographicScope","reversibility","persistence","independentConfirmation","evidenceReferences","evidenceLimitations","confidence","reviewerConfirmed","assessedAt","supersedesImpactId"],
  reviewerDecision: ["id","reviewerRole","organizationalAuthority","decisionType","decision","targetState","rationale","evidenceReferences","unresolvedIssues","conditions","decidedAt","approvalChain","supersedesDecisionId","conflictOfInterestDeclared","approvedPackageId"],
  submissionPackage: ["id","version","state","incidentSummary","evidenceIndex","unresolvedUncertainty","evidenceIntegrityDigests","replayReference","trustMemoryReference","exportSchemaVersion","exportedAt","approvedByDecisionId","supersedesPackageId"],
  externalSubmission: ["id","state","destinationAuthority","jurisdiction","submissionChannel","externalReference","submittedAt","submittingActor","packageId","packageVersion","packageDigest","acknowledgementReference","acknowledgementAt","followUpDeadline","limitations","supersedesSubmissionId"],
  correctiveAction: ["id","actionType","actionOwner","accountableApprover","targetDate","completionDate","completionEvidenceReferences","validationEvidenceReferences","residualRisk","reviewerApprovalDecisionId","effectivenessState","linkedContradictionReference","linkedFindingReference","linkedPackageReference","supersedesCorrectiveActionId"],
  evidenceSupersession: ["id","recordType","originalRecordId","correctedRecordId","correctionReason","evidenceReferences","approvedByDecisionId","correctedAt"],
} as const;

export function assertSeriousIncidentRecordShape(value: unknown, kind: keyof typeof recordFields) {
  assertKnownFields(value, recordFields[kind], kind);
  const item=object(value,kind);
  if(kind==="impact"){optionalNonnegativeInteger(item.affectedUserEstimate,"affectedUserEstimate");optionalNonnegativeInteger(item.durationSeconds,"durationSeconds");}
  if(kind==="submissionPackage"&&(typeof item.version!=="number"||!Number.isSafeInteger(item.version)||item.version<1))invalid("PACKAGE_VERSION_INVALID","Package version must be a positive integer.");
  if(kind==="externalSubmission"){
    if(typeof item.packageVersion!=="number"||!Number.isSafeInteger(item.packageVersion)||item.packageVersion<1)invalid("PACKAGE_VERSION_INVALID","Submitted package version must be a positive integer.");
    if(!SHA256.test(typeof item.packageDigest==="string"?item.packageDigest:""))invalid("PACKAGE_DIGEST_INVALID","Submitted package digest must be SHA-256.");
    if(item.supersedesSubmissionId&&item.supersedesSubmissionId===item.id)invalid("SUBMISSION_SELF_SUPERSESSION","A submission cannot supersede itself.");
    if(["transferred","acknowledged","rejected","returned_for_clarification","supplemented","closed"].includes(String(item.state))&&(!item.submittedAt||!item.submittingActor))invalid("SUBMISSION_EVIDENCE_INCOMPLETE","A transferred submission state requires actor and timestamp evidence.");
    if(item.state==="acknowledged"&&(!item.acknowledgementReference||!item.acknowledgementAt))invalid("ACKNOWLEDGEMENT_EVIDENCE_REQUIRED","Acknowledgement requires its reference and timestamp.");
  }
  if(kind==="correctiveAction"&&item.supersedesCorrectiveActionId&&item.supersedesCorrectiveActionId===item.id)invalid("CORRECTIVE_ACTION_SELF_SUPERSESSION","A corrective action cannot supersede itself.");
}

export function validateDeadlineMetadata(value: unknown) {
  if(value===null||value===undefined)return null;
  assertKnownFields(value,["deadline","sourceType","ruleSource","rationale","timezone","uncertainty","approvedBy"],"deadlineMetadata");
  const item=object(value,"deadlineMetadata");
  return {deadline:timestamp(item.deadline,"deadline"),sourceType:enumValue(item.sourceType,["reviewer_supplied","policy_supplied","externally_supplied"] as const,"deadline.sourceType"),ruleSource:string(item.ruleSource,"deadline.ruleSource"),rationale:string(item.rationale,"deadline.rationale",4_000),timezone:string(item.timezone,"deadline.timezone",100),uncertainty:string(item.uncertainty,"deadline.uncertainty",1_000),approvedBy:string(item.approvedBy,"deadline.approvedBy")};
}

export function assertDataMinimized(value: unknown, path = "record"): void {
  if (Array.isArray(value)) { value.forEach((item, index) => assertDataMinimized(item, `${path}[${index}]`)); return; }
  if (!value || typeof value !== "object") return;
  if (path in recordFields) assertSeriousIncidentRecordShape(value, path as keyof typeof recordFields);
  for (const [key, item] of Object.entries(value as Record<string, unknown>)) {
    if (PROHIBITED_KEYS.test(key)) invalid("PROHIBITED_EVIDENCE_FIELD", `${path}.${key} is prohibited; store a digest or masked reference.`);
    assertDataMinimized(item, `${path}.${key}`);
  }
}

export function validateEvidenceSnapshot(value: unknown): EvidenceSnapshotInput {
  const allowed = ["id", "capturedAt", "aiSystemIdentity", "agentIdentity", "modelProvider", "modelFamily", "modelVersion", "agentVersion", "promptConfigurationDigest", "maskedPromptReference", "toolConfiguration", "connectorConfiguration", "authorityGrantReferences", "scopeAuthorizationLeaseReference", "declaredEnvironmentReference", "configuredEnvironmentReference", "observedEnvironmentReferences", "effectiveAccess", "permittedTargets", "observedTargets", "credentialStateClassification", "policyVersion", "monitoringProviderHealth", "unresolvedFindings", "approvedExceptionReferences", "responsibleHumanState", "deploymentApprovalReference", "assuranceBaselineReference", "containmentReadiness", "providerEvidenceReferences", "evidenceLimitations", "supersedesSnapshotId"];
  assertKnownFields(value, allowed, "evidenceSnapshot"); assertDataMinimized(value, "evidenceSnapshot");
  const item = object(value, "evidenceSnapshot");
  const digest = optionalString(item.promptConfigurationDigest, "promptConfigurationDigest", 64);
  if (digest && !SHA256.test(digest)) invalid("PROMPT_DIGEST_INVALID", "Prompt configuration digest must be SHA-256.");
  const result: EvidenceSnapshotInput = {
    id: uuid(item.id, "snapshot.id"), capturedAt: timestamp(item.capturedAt, "snapshot.capturedAt"), aiSystemIdentity: string(item.aiSystemIdentity, "aiSystemIdentity"), agentIdentity: string(item.agentIdentity, "agentIdentity"),
    modelProvider: string(item.modelProvider, "modelProvider"), modelFamily: string(item.modelFamily, "modelFamily"), modelVersion: string(item.modelVersion, "modelVersion"), agentVersion: string(item.agentVersion, "agentVersion"),
    promptConfigurationDigest: digest, maskedPromptReference: optionalString(item.maskedPromptReference, "maskedPromptReference"), toolConfiguration: list(item.toolConfiguration, "toolConfiguration"), connectorConfiguration: list(item.connectorConfiguration, "connectorConfiguration"), authorityGrantReferences: list(item.authorityGrantReferences, "authorityGrantReferences"),
    scopeAuthorizationLeaseReference: optionalString(item.scopeAuthorizationLeaseReference, "scopeAuthorizationLeaseReference"), declaredEnvironmentReference: optionalString(item.declaredEnvironmentReference, "declaredEnvironmentReference"), configuredEnvironmentReference: optionalString(item.configuredEnvironmentReference, "configuredEnvironmentReference"), observedEnvironmentReferences: list(item.observedEnvironmentReferences, "observedEnvironmentReferences"),
    effectiveAccess: list(item.effectiveAccess, "effectiveAccess"), permittedTargets: list(item.permittedTargets, "permittedTargets"), observedTargets: list(item.observedTargets, "observedTargets"), credentialStateClassification: string(item.credentialStateClassification, "credentialStateClassification"), policyVersion: string(item.policyVersion, "policyVersion"), monitoringProviderHealth: string(item.monitoringProviderHealth, "monitoringProviderHealth"),
    unresolvedFindings: list(item.unresolvedFindings, "unresolvedFindings"), approvedExceptionReferences: list(item.approvedExceptionReferences, "approvedExceptionReferences"), responsibleHumanState: string(item.responsibleHumanState, "responsibleHumanState"), deploymentApprovalReference: optionalString(item.deploymentApprovalReference, "deploymentApprovalReference"), assuranceBaselineReference: optionalString(item.assuranceBaselineReference, "assuranceBaselineReference"), containmentReadiness: string(item.containmentReadiness, "containmentReadiness"), providerEvidenceReferences: list(item.providerEvidenceReferences, "providerEvidenceReferences"), evidenceLimitations: list(item.evidenceLimitations, "evidenceLimitations"), supersedesSnapshotId: item.supersedesSnapshotId ? uuid(item.supersedesSnapshotId, "supersedesSnapshotId") : null,
  };
  if (result.supersedesSnapshotId === result.id) invalid("SNAPSHOT_SELF_SUPERSESSION", "A snapshot cannot supersede itself.");
  return result;
}

export function validateAssessmentInput(value: unknown): SeriousIncidentAssessmentInput {
  const rootFields = ["id", "enterpriseId", "state", "identity", "regulatoryContext", "clocks", "references", "responsibilityRoles", "evidenceSnapshot", "screeningInput", "createdAt"];
  assertKnownFields(value, rootFields, "assessment"); assertDataMinimized(value, "assessment"); const root = object(value, "assessment");
  assertKnownFields(root.identity, ["agentId","aiSystemId","modelProvider","modelFamily","modelVersion","agentVersion","deploymentReference","runtimeSessionReference","responsibleHuman","accountableOrganization","systemOwner","incidentOwner"], "identity");
  assertKnownFields(root.regulatoryContext, ["jurisdiction","frameworkReference","systemClassification","gpaiSystemicRiskStatus","organizationalRole","incidentCategory","providerClassification","technicalClassification","operationalScreeningClassification","complianceReviewClassification","legalReviewClassification","regulatorClassification"], "regulatoryContext");
  assertKnownFields(root.clocks, ["firstOccurrenceAt","firstProviderObservationAt","firstCyberSentinelsIngestionAt","firstDetectionAt","firstHumanReviewAt","organizationAwarenessAt","materialityDeterminationAt","containmentStartedAt","containmentConfirmedAt","reportingDecisionAt","submissionAt","regulatorAcknowledgementAt","recoveryAt","closureAt"], "clocks");
  assertKnownFields(root.references, ["affectedSystems","affectedOrganizations","affectedThirdParties","impactSummary","evidenceCompleteness","evidenceLimitations","replayReference","trustMemoryReference","evidenceGraphReference","authorityLineageReference","environmentAttestationReference","scopeContinuityDecisionReference"], "references");
  assertKnownFields(root.screeningInput, ["jurisdiction","systemClassification","gpaiSystemicRisk","highRiskUseContext","cybersecurityImpact","outsideAuthorizedHumanControl","seriousMalfunction","thirdPartyHarm","fundamentalRightsImpact","criticalSectorImpact","modelProviderRole","deployerRole","contractualReportingObligation","organizationAwarenessRecorded","containmentFailure","evidenceCompleteness"], "screeningInput");
  const identity = object(root.identity, "identity"); const regulatory = object(root.regulatoryContext, "regulatoryContext"); const clocks = object(root.clocks, "clocks"); const references = object(root.references, "references");
  if (!Array.isArray(root.responsibilityRoles) || !root.responsibilityRoles.length) invalid("RESPONSIBILITY_LINEAGE_REQUIRED", "At least one responsibility role is required.");
  root.responsibilityRoles.forEach((raw, index) => assertKnownFields(raw, ["id","roleType","partyType","partyReference","authorityReference","assignedAt","assignedBy","supersedesRoleId"], `responsibilityRoles[${index}]`));
  const roles = root.responsibilityRoles.map((raw, index) => { const item = object(raw, `responsibilityRoles[${index}]`); const id = uuid(item.id, "role.id"); const supersedesRoleId = item.supersedesRoleId ? uuid(item.supersedesRoleId, "supersedesRoleId") : null; if (id === supersedesRoleId) invalid("ROLE_SELF_SUPERSESSION", "A responsibility role cannot supersede itself."); return { id, roleType: enumValue(item.roleType,responsibilityRoleTypes,"roleType"), partyType: enumValue(item.partyType, ["organization", "human", "provider", "system"] as const, "partyType"), partyReference: string(item.partyReference, "partyReference"), authorityReference: optionalString(item.authorityReference, "authorityReference"), assignedAt: timestamp(item.assignedAt, "assignedAt"), assignedBy: string(item.assignedBy, "assignedBy"), supersedesRoleId }; });
  const screening = object(root.screeningInput, "screeningInput");
  if(typeof screening.organizationAwarenessRecorded!=="boolean")invalid("BOOLEAN_INVALID","organizationAwarenessRecorded must be boolean.");
  const nullableBoolean = (item: unknown, name: string) => { if (item === null) return null; if (typeof item !== "boolean") invalid("BOOLEAN_INVALID", `${name} must be boolean or null.`); return item; };
  return {
    id: uuid(root.id, "assessment.id"), enterpriseId: uuid(root.enterpriseId, "enterpriseId"), state: enumValue(root.state, assessmentStates, "state"),
    identity: { agentId: string(identity.agentId, "agentId"), aiSystemId: string(identity.aiSystemId, "aiSystemId"), modelProvider: string(identity.modelProvider, "modelProvider"), modelFamily: string(identity.modelFamily, "modelFamily"), modelVersion: string(identity.modelVersion, "modelVersion"), agentVersion: string(identity.agentVersion, "agentVersion"), deploymentReference: string(identity.deploymentReference, "deploymentReference"), runtimeSessionReference: optionalString(identity.runtimeSessionReference, "runtimeSessionReference"), responsibleHuman: string(identity.responsibleHuman, "responsibleHuman"), accountableOrganization: string(identity.accountableOrganization, "accountableOrganization"), systemOwner: string(identity.systemOwner, "systemOwner"), incidentOwner: string(identity.incidentOwner, "incidentOwner") },
    regulatoryContext: { jurisdiction: string(regulatory.jurisdiction, "jurisdiction"), frameworkReference: optionalString(regulatory.frameworkReference, "frameworkReference"), systemClassification: string(regulatory.systemClassification, "systemClassification"), gpaiSystemicRiskStatus: optionalString(regulatory.gpaiSystemicRiskStatus, "gpaiSystemicRiskStatus"), organizationalRole: enumValue(regulatory.organizationalRole, organizationRoles, "organizationalRole"), incidentCategory: enumValue(regulatory.incidentCategory, incidentCategories, "incidentCategory"), providerClassification: optionalString(regulatory.providerClassification, "providerClassification"), technicalClassification: string(regulatory.technicalClassification, "technicalClassification"), operationalScreeningClassification: optionalString(regulatory.operationalScreeningClassification, "operationalScreeningClassification"), complianceReviewClassification: optionalString(regulatory.complianceReviewClassification, "complianceReviewClassification"), legalReviewClassification: optionalString(regulatory.legalReviewClassification, "legalReviewClassification"), regulatorClassification: optionalString(regulatory.regulatorClassification, "regulatorClassification") },
    clocks: { firstOccurrenceAt: optionalTimestamp(clocks.firstOccurrenceAt, "firstOccurrenceAt"), firstProviderObservationAt: optionalTimestamp(clocks.firstProviderObservationAt, "firstProviderObservationAt"), firstCyberSentinelsIngestionAt: timestamp(clocks.firstCyberSentinelsIngestionAt, "firstCyberSentinelsIngestionAt"), firstDetectionAt: timestamp(clocks.firstDetectionAt, "firstDetectionAt"), firstHumanReviewAt: optionalTimestamp(clocks.firstHumanReviewAt, "firstHumanReviewAt"), organizationAwarenessAt: optionalTimestamp(clocks.organizationAwarenessAt, "organizationAwarenessAt"), materialityDeterminationAt: optionalTimestamp(clocks.materialityDeterminationAt, "materialityDeterminationAt"), containmentStartedAt: optionalTimestamp(clocks.containmentStartedAt, "containmentStartedAt"), containmentConfirmedAt: optionalTimestamp(clocks.containmentConfirmedAt, "containmentConfirmedAt"), reportingDecisionAt: optionalTimestamp(clocks.reportingDecisionAt, "reportingDecisionAt"), submissionAt: optionalTimestamp(clocks.submissionAt, "submissionAt"), regulatorAcknowledgementAt: optionalTimestamp(clocks.regulatorAcknowledgementAt, "regulatorAcknowledgementAt"), recoveryAt: optionalTimestamp(clocks.recoveryAt, "recoveryAt"), closureAt: optionalTimestamp(clocks.closureAt, "closureAt") },
    references: { affectedSystems: list(references.affectedSystems, "affectedSystems"), affectedOrganizations: list(references.affectedOrganizations, "affectedOrganizations"), affectedThirdParties: list(references.affectedThirdParties, "affectedThirdParties"), impactSummary: string(references.impactSummary, "impactSummary", 4_000), evidenceCompleteness: enumValue(references.evidenceCompleteness, ["complete", "partial", "insufficient", "unknown"] as const, "evidenceCompleteness"), evidenceLimitations: list(references.evidenceLimitations, "evidenceLimitations"), replayReference: optionalString(references.replayReference, "replayReference"), trustMemoryReference: optionalString(references.trustMemoryReference, "trustMemoryReference"), evidenceGraphReference: optionalString(references.evidenceGraphReference, "evidenceGraphReference"), authorityLineageReference: optionalString(references.authorityLineageReference, "authorityLineageReference"), environmentAttestationReference: optionalString(references.environmentAttestationReference, "environmentAttestationReference"), scopeContinuityDecisionReference: optionalString(references.scopeContinuityDecisionReference, "scopeContinuityDecisionReference") },
    responsibilityRoles: roles, evidenceSnapshot: validateEvidenceSnapshot(root.evidenceSnapshot),
    screeningInput: { jurisdiction: optionalString(screening.jurisdiction, "screening.jurisdiction"), systemClassification: optionalString(screening.systemClassification, "screening.systemClassification"), gpaiSystemicRisk: nullableBoolean(screening.gpaiSystemicRisk, "gpaiSystemicRisk"), highRiskUseContext: nullableBoolean(screening.highRiskUseContext, "highRiskUseContext"), cybersecurityImpact: nullableBoolean(screening.cybersecurityImpact, "cybersecurityImpact"), outsideAuthorizedHumanControl: nullableBoolean(screening.outsideAuthorizedHumanControl, "outsideAuthorizedHumanControl"), seriousMalfunction: nullableBoolean(screening.seriousMalfunction, "seriousMalfunction"), thirdPartyHarm: nullableBoolean(screening.thirdPartyHarm, "thirdPartyHarm"), fundamentalRightsImpact: nullableBoolean(screening.fundamentalRightsImpact, "fundamentalRightsImpact"), criticalSectorImpact: nullableBoolean(screening.criticalSectorImpact, "criticalSectorImpact"), modelProviderRole: nullableBoolean(screening.modelProviderRole, "modelProviderRole"), deployerRole: nullableBoolean(screening.deployerRole, "deployerRole"), contractualReportingObligation: nullableBoolean(screening.contractualReportingObligation, "contractualReportingObligation"), organizationAwarenessRecorded: Boolean(screening.organizationAwarenessRecorded), containmentFailure: nullableBoolean(screening.containmentFailure, "containmentFailure"), evidenceCompleteness: enumValue(screening.evidenceCompleteness, ["complete", "partial", "insufficient", "unknown"] as const, "screening.evidenceCompleteness") },
    createdAt: timestamp(root.createdAt, "createdAt"),
  };
}

export function validateChronologyEvent(value: unknown): IncidentChronologyEvent { assertDataMinimized(value, "chronology"); const item = object(value, "chronology"); const id = uuid(item.id, "event.id"); const supersedesEventId = item.supersedesEventId ? uuid(item.supersedesEventId, "supersedesEventId") : null; if (id === supersedesEventId) invalid("EVENT_SELF_SUPERSESSION", "An event cannot supersede itself."); return { id, enterpriseId: uuid(item.enterpriseId, "enterpriseId"), incidentId: uuid(item.incidentId, "incidentId"), eventType: enumValue(item.eventType, chronologyEventTypes, "eventType"), source: string(item.source, "source"), sourceType: string(item.sourceType, "sourceType"), sourceAuthority: string(item.sourceAuthority, "sourceAuthority"), occurredAt: timestamp(item.occurredAt, "occurredAt"), timestampConfidence: enumValue(item.timestampConfidence, ["confirmed", "high", "medium", "low", "unknown"] as const, "timestampConfidence"), ingestedAt: timestamp(item.ingestedAt, "ingestedAt"), orderingConfidence: enumValue(item.orderingConfidence, ["confirmed", "high", "medium", "low", "unknown"] as const, "orderingConfidence"), evidenceReference: optionalString(item.evidenceReference, "evidenceReference"), integrityState: enumValue(item.integrityState, ["verified", "unverified", "invalid", "unknown"] as const, "integrityState"), correlationId: uuid(item.correlationId, "correlationId"), classification: enumValue(item.classification, ["TECHNICAL EVIDENCE", "PROVIDER ASSERTION", "PROVIDER CONCLUSION", "CYBER SENTINELS OPERATIONAL SCREENING", "REVIEWER DECISION", "LEGAL CONCLUSION", "REGULATOR RESPONSE", "CORRECTIVE ACTION"] as const, "classification"), summary: string(item.summary, "summary", 2_000), containmentState: item.containmentState ? enumValue(item.containmentState, containmentStates, "containmentState") : null, supersedesEventId }; }

export function validateImpact(value: unknown): ImpactAssessmentInput { assertDataMinimized(value, "impact"); const item = object(value, "impact"); const categories = Array.isArray(item.categories) ? item.categories.map((value) => enumValue(value, impactCategories, "impact.category")) : invalid("ARRAY_INVALID", "impact.categories must be an array."); if (!categories.length) invalid("IMPACT_CATEGORY_REQUIRED", "At least one impact category is required."); if (!Boolean(item.independentConfirmation) && !Boolean(item.reviewerConfirmed) && categories.some((category) => !["attempted_access", "unknown", "no_confirmed_impact"].includes(category))) invalid("IMPACT_CONFIRMATION_REQUIRED", "Confirmed impact requires independent or reviewer confirmation."); const id = uuid(item.id, "impact.id"); const supersedesImpactId = item.supersedesImpactId ? uuid(item.supersedesImpactId, "supersedesImpactId") : null; if (id === supersedesImpactId) invalid("IMPACT_SELF_SUPERSESSION", "An impact assessment cannot supersede itself."); return { id, categories, affectedResourceReferences: list(item.affectedResourceReferences, "affectedResourceReferences"), affectedDataClassifications: list(item.affectedDataClassifications, "affectedDataClassifications"), affectedOrganizations: list(item.affectedOrganizations, "affectedOrganizations"), affectedUserEstimate: item.affectedUserEstimate === null || item.affectedUserEstimate === undefined ? null : Number(item.affectedUserEstimate), durationSeconds: item.durationSeconds === null || item.durationSeconds === undefined ? null : Number(item.durationSeconds), geographicScope: list(item.geographicScope, "geographicScope"), reversibility: string(item.reversibility, "reversibility"), persistence: string(item.persistence, "persistence"), independentConfirmation: Boolean(item.independentConfirmation), evidenceReferences: list(item.evidenceReferences, "evidenceReferences"), evidenceLimitations: list(item.evidenceLimitations, "evidenceLimitations"), confidence: enumValue(item.confidence, ["confirmed", "high", "medium", "low", "unknown"] as const, "confidence"), reviewerConfirmed: Boolean(item.reviewerConfirmed), assessedAt: timestamp(item.assessedAt, "assessedAt"), supersedesImpactId }; }

export function validateReviewerDecision(value: unknown): ReviewerDecisionInput { assertDataMinimized(value, "reviewerDecision"); const item = object(value, "reviewerDecision"); const id = uuid(item.id, "decision.id"); const supersedesDecisionId = item.supersedesDecisionId ? uuid(item.supersedesDecisionId, "supersedesDecisionId") : null; if (id === supersedesDecisionId) invalid("DECISION_SELF_SUPERSESSION", "A decision cannot supersede itself."); return { id, reviewerRole: enumValue(item.reviewerRole, reviewerRoles, "reviewerRole"), organizationalAuthority: string(item.organizationalAuthority, "organizationalAuthority"), decisionType: enumValue(item.decisionType, decisionTypes, "decisionType"), decision: string(item.decision, "decision"), targetState: item.targetState ? enumValue(item.targetState, assessmentStates, "targetState") : null, rationale: string(item.rationale, "rationale", 8_000), evidenceReferences: list(item.evidenceReferences, "evidenceReferences"), unresolvedIssues: list(item.unresolvedIssues, "unresolvedIssues"), conditions: list(item.conditions, "conditions"), decidedAt: timestamp(item.decidedAt, "decidedAt"), approvalChain: list(item.approvalChain, "approvalChain"), supersedesDecisionId, conflictOfInterestDeclared: item.conflictOfInterestDeclared === null || item.conflictOfInterestDeclared === undefined ? null : Boolean(item.conflictOfInterestDeclared) }; }

export function validatePackage(value: unknown): SubmissionPackageInput { assertDataMinimized(value, "submissionPackage"); const item = object(value, "submissionPackage"); const id = uuid(item.id, "package.id"); const supersedesPackageId = item.supersedesPackageId ? uuid(item.supersedesPackageId, "supersedesPackageId") : null; if (id === supersedesPackageId) invalid("PACKAGE_SELF_SUPERSESSION", "A package cannot supersede itself."); return { id, version: Number(item.version), state: enumValue(item.state, packageStates, "package.state"), incidentSummary: string(item.incidentSummary, "incidentSummary", 8_000), evidenceIndex: list(item.evidenceIndex, "evidenceIndex", 500), unresolvedUncertainty: list(item.unresolvedUncertainty, "unresolvedUncertainty"), evidenceIntegrityDigests: list(item.evidenceIntegrityDigests, "evidenceIntegrityDigests", 500), replayReference: optionalString(item.replayReference, "replayReference"), trustMemoryReference: optionalString(item.trustMemoryReference, "trustMemoryReference"), exportSchemaVersion: string(item.exportSchemaVersion, "exportSchemaVersion"), exportedAt: timestamp(item.exportedAt, "exportedAt"), approvedByDecisionId: item.approvedByDecisionId ? uuid(item.approvedByDecisionId, "approvedByDecisionId") : null, supersedesPackageId }; }

export function validateExternalSubmission(value: unknown): ExternalSubmissionInput { assertDataMinimized(value, "externalSubmission"); const item = object(value, "externalSubmission"); return { id: uuid(item.id, "submission.id"), state: enumValue(item.state, ["prepared", "internally_approved", "transferred", "acknowledged", "rejected", "returned_for_clarification", "supplemented", "closed"] as const, "submission.state"), destinationAuthority: string(item.destinationAuthority, "destinationAuthority"), jurisdiction: string(item.jurisdiction, "jurisdiction"), submissionChannel: string(item.submissionChannel, "submissionChannel"), externalReference: optionalString(item.externalReference, "externalReference"), submittedAt: optionalTimestamp(item.submittedAt, "submittedAt"), submittingActor: optionalString(item.submittingActor, "submittingActor"), packageId: uuid(item.packageId, "packageId"), packageVersion: Number(item.packageVersion), packageDigest: string(item.packageDigest, "packageDigest", 64), acknowledgementReference: optionalString(item.acknowledgementReference, "acknowledgementReference"), acknowledgementAt: optionalTimestamp(item.acknowledgementAt, "acknowledgementAt"), followUpDeadline: optionalTimestamp(item.followUpDeadline, "followUpDeadline"), limitations: list(item.limitations, "limitations"), supersedesSubmissionId: item.supersedesSubmissionId ? uuid(item.supersedesSubmissionId, "supersedesSubmissionId") : null }; }

export function validateCorrectiveAction(value: unknown): CorrectiveActionInput { assertDataMinimized(value, "correctiveAction"); const item = object(value, "correctiveAction"); const state = enumValue(item.effectivenessState, ["planned", "in_progress", "completed_unvalidated", "validated", "ineffective", "unknown"] as const, "effectivenessState"); const completion = list(item.completionEvidenceReferences, "completionEvidenceReferences"); const validation = list(item.validationEvidenceReferences, "validationEvidenceReferences"); if (["completed_unvalidated", "validated"].includes(state) && !completion.length) invalid("COMPLETION_EVIDENCE_REQUIRED", "Corrective-action completion requires evidence."); if (state === "validated" && !validation.length) invalid("VALIDATION_EVIDENCE_REQUIRED", "Validated corrective action requires validation evidence."); const id = uuid(item.id, "correctiveAction.id"); const supersedesCorrectiveActionId = item.supersedesCorrectiveActionId ? uuid(item.supersedesCorrectiveActionId, "supersedesCorrectiveActionId") : null; return { id, actionType: string(item.actionType, "actionType"), actionOwner: string(item.actionOwner, "actionOwner"), accountableApprover: string(item.accountableApprover, "accountableApprover"), targetDate: optionalTimestamp(item.targetDate, "targetDate"), completionDate: optionalTimestamp(item.completionDate, "completionDate"), completionEvidenceReferences: completion, validationEvidenceReferences: validation, residualRisk: string(item.residualRisk, "residualRisk"), reviewerApprovalDecisionId: item.reviewerApprovalDecisionId ? uuid(item.reviewerApprovalDecisionId, "reviewerApprovalDecisionId") : null, effectivenessState: state, linkedContradictionReference: optionalString(item.linkedContradictionReference, "linkedContradictionReference"), linkedFindingReference: optionalString(item.linkedFindingReference, "linkedFindingReference"), linkedPackageReference: optionalString(item.linkedPackageReference, "linkedPackageReference"), supersedesCorrectiveActionId }; }

export function validateIncidentReference(value: unknown, name: string) { const result = string(value, name, 160); if (!SAFE_REFERENCE.test(result)) invalid("REFERENCE_INVALID", `${name} is invalid.`); return result; }

export function validateEvidenceSupersession(value: unknown): EvidenceSupersessionInput {
  assertDataMinimized(value,"evidenceSupersession");const item=object(value,"evidenceSupersession");const id=uuid(item.id,"correction.id");const originalRecordId=uuid(item.originalRecordId,"originalRecordId");const correctedRecordId=uuid(item.correctedRecordId,"correctedRecordId");if(originalRecordId===correctedRecordId)invalid("CORRECTION_SELF_REFERENCE","A correction must link distinct original and corrected records.");return {id,recordType:enumValue(item.recordType,["provider_evidence","impact_assessment","incident_classification","responsibility_attribution","containment_outcome","reporting_decision","corrective_action","evidence_snapshot"] as const,"recordType"),originalRecordId,correctedRecordId,correctionReason:string(item.correctionReason,"correctionReason",4_000),evidenceReferences:list(item.evidenceReferences,"evidenceReferences"),approvedByDecisionId:item.approvedByDecisionId?uuid(item.approvedByDecisionId,"approvedByDecisionId"):null,correctedAt:timestamp(item.correctedAt,"correctedAt")};
}
