import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const sql = await readFile(new URL("../../supabase/migrations/202607210002_continuous_trust_runtime.sql", import.meta.url), "utf8");
test("EPIC 19 extends authoritative tables and creates no duplicate alert or state table", () => { for (const name of ["evidence_objects", "subject_trust_state", "trust_alerts", "evidence_graph_edges"]) assert.match(sql, new RegExp(`alter table public\\.${name}`)); assert.doesNotMatch(sql, /create table public\.trust_alerts/); assert.doesNotMatch(sql, /create table public\.subject_trust_state/); assert.match(sql, /create table public\.continuous_trust_assessments/); assert.match(sql, /create table public\.trust_drift_findings/); });
test("continuous tables deny anonymous access and tenant-scope authenticated reads", () => { assert.match(sql, /revoke all on public\.%I from anon,authenticated/); assert.match(sql, /tenant reads continuous trust assessments/); assert.match(sql, /tenant reads trust drift findings/); assert.match(sql, /tenant reads continuous trust alerts/); assert.match(sql, /user_can_access_trust_workspace\(enterprise_id\)/); });
test("only the service wrapper can apply assessments and it calls the sole Trust State mutation RPC", () => { const segment = sql.slice(sql.indexOf("create or replace function public.apply_continuous_trust_assessment_v1"), sql.indexOf("create or replace function public.transition_continuous_trust_alert_v1")); assert.match(segment, /auth\.role\(\)<>'service_role'/); assert.match(segment, /public\.apply_trust_state_decision_v1/); assert.doesNotMatch(segment, /update public\.subject_trust_state set state=/); assert.match(segment, /CONTINUOUS_TRUST_ASSESSMENT_APPLIED/); });
test("drift history is append-only and alert transitions are bounded", () => { assert.match(sql, /trust_drift_findings_append_only/); assert.match(sql, /prevent_trust_architecture_history_mutation/); assert.match(sql, /p_next_state not in \('acknowledged','investigating','resolved','dismissed'\)/); assert.match(sql, /Closed alert transition denied/); assert.match(sql, /revoke insert,update,delete on public\.trust_alerts from authenticated/); });
test("evidence expiry and graph queries have tenant-first indexes", () => { assert.match(sql, /evidence_objects_runtime_due_idx.*enterprise_id,subject_id,expires_at/); assert.match(sql, /subject_trust_state_next_evaluation_idx.*enterprise_id,next_evaluation_at,subject_id/); assert.match(sql, /trust_alerts_runtime_idx.*enterprise_id,status,severity,detected_at/); assert.match(sql, /ALERTED_BY/); });
