import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { randomUUID } from "node:crypto";

const migration = await readFile(new URL("../../supabase/migrations/202610040001_p0p1_security_closure.sql", import.meta.url), "utf8");
const approvalMigration = await readFile(new URL("../../supabase/migrations/202610040002_account_access_approval.sql", import.meta.url), "utf8");
const approvalGateMigration = await readFile(new URL("../../supabase/migrations/202610040003_require_approved_accounts_for_data_api.sql", import.meta.url), "utf8");
const passportDecisionMigration = await readFile(new URL("../../supabase/migrations/202610040004_lock_legacy_passport_decision_writes.sql", import.meta.url), "utf8");

test("legacy tenant rows and evidence objects are isolated across authenticated users", async () => {
  const db = new PGlite();
  const userA = "11111111-1111-4111-8111-111111111111";
  const userB = "22222222-2222-4222-8222-222222222222";
  const pendingUser = "33333333-3333-4333-8333-333333333333";
  const caseA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
  const caseB = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
  const teamA = "dddddddd-dddd-4ddd-8ddd-dddddddddddd";
  try {
    await db.exec(`
      create role anon;
      create role authenticated;
      create role service_role bypassrls;
      create schema auth;
      create schema storage;
      grant usage on schema public, auth, storage to anon, authenticated, service_role;
      create table auth.users(id uuid primary key, email text, raw_user_meta_data jsonb default '{}'::jsonb, created_at timestamptz default now());
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
      create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb) $$;
      create function public.user_can_access_trust_workspace(uuid) returns boolean language sql stable as $$ select false $$;
      create table public.ai_agents(id uuid, owner_user_id uuid, owner_enterprise_id uuid, enterprise_id uuid, owner_email text);
      create table public.api_keys(id uuid, owner_user_id uuid, user_id uuid, user_email text, tenant_id uuid);
      create table public.audit_logs(id uuid, owner_email text, actor text, metadata jsonb, team_id text);
      create table public.autonomy_profiles(id uuid, created_by text);
      create table public.data_rights_requests(id uuid, requester_user_id uuid, requester_email text);
      create table public.decisions(id uuid, owner_email text, team_id text, case_id uuid, verification_case_id uuid, passport_id uuid);
      create table public.enterprise_access_requests(id uuid, work_email text, name text, company text, role text, company_size text, current_problem_category text, current_problem text, ai_usage_level text, use_case text, message text, design_partner_interest boolean, governance_interest boolean, operational_ai_interest boolean, status text);
      create table public.evidence_files(id uuid, owner_email text, uploaded_by text, team_id text, verification_case_id uuid, passport_id uuid);
      create table public.execution_passports(id uuid, created_by text, passport_id uuid);
      create table public.feedback_reports(id uuid, submitted_by_user_id uuid, submitted_by_email text);
      create table public.help_questions(id uuid, created_by_user_id uuid, created_by_email text, created_by text);
      create table public.intent_requests(id uuid, created_by text);
      create table public.interest_signals(id uuid);
      create table public.knowledge_articles(id uuid, status text);
      create table public.passport_state_checks(id uuid, created_by text, passport_id uuid);
      create table public.passports(id uuid primary key, owner_email text, user_email text, team_id text, verified boolean, clearance text);
      create table public.provenance_events(id uuid, created_by text, enterprise_id uuid);
      create table public.risk_scores(id uuid, team_id text, verification_case_id uuid, case_id uuid);
      create table public.signals(id uuid, owner_email text, team_id text);
      create table public.teams(id uuid primary key);
      create table public.team_members(id uuid, team_id uuid, member_email text, invitation_status text);
      create table public.trust_alerts(id uuid, created_by uuid, enterprise_id uuid);
      create table public.trust_algorithm_runs(id uuid, subject_type text, subject_id uuid);
      create table public.trust_assistant_questions(id uuid, asked_by_user_id uuid, asked_by_email text);
      create table public.trust_certifications(id uuid, created_by uuid, enterprise_id uuid, status text, notes text, updated_at timestamptz);
      create table public.trust_graph_edges(id uuid);
      create table public.trust_graph_nodes(id uuid);
      create table public.trust_reports(id uuid primary key, owner_email text, team_id text, passport_id uuid, review_status text);
      create table public.verification_cases(id uuid primary key, owner_email text, team_id text, passport_id uuid);
      create table public.verification_passports(id uuid);
      create table public.verifiers(id uuid, created_by uuid, status text);
      create table public.waitlist(email text);
      create table storage.buckets(id text primary key, public boolean);
      create table storage.objects(id uuid default gen_random_uuid(), bucket_id text, name text);
      alter table storage.objects enable row level security;
    `);

    await db.exec(migration);
  await db.query("insert into auth.users(id, email, raw_user_meta_data) values ($1, 'a@example.test', '{\"organization\":\"Tenant A\"}'), ($2, 'b@example.test', '{\"organization\":\"Tenant B\"}')", [userA, userB]);
  await db.exec(approvalMigration);
  await db.exec(approvalGateMigration);
  await db.exec(passportDecisionMigration);
  const emailLessUser = randomUUID();
  await db.query("insert into auth.users(id, email) values ($1, null)", [emailLessUser]);
  assert.equal((await db.query("select count(*)::int n from public.account_access_approvals where user_id = $1", [emailLessUser])).rows[0].n, 0);
  await db.query("insert into auth.users(id, email) values ($1, 'pending@example.test')", [pendingUser]);
  await db.query("insert into public.passports(id, owner_email, user_email) values ($1, 'pending@example.test', 'pending@example.test')", [randomUUID()]);
    await db.exec("grant all on all tables in schema public to service_role; grant all on storage.objects to service_role");
    for (const table of ["interest_signals", "trust_graph_edges", "trust_graph_nodes", "verification_passports", "waitlist"]) {
      assert.equal((await db.query("select has_table_privilege('authenticated', $1, 'select') allowed", [`public.${table}`])).rows[0].allowed, false, table);
      assert.equal((await db.query("select has_table_privilege('service_role', $1, 'select') allowed", [`public.${table}`])).rows[0].allowed, true, table);
    }
    assert.equal((await db.query("select to_regclass('public.system_health_checks') is null absent")).rows[0].absent, true);
  assert.equal((await db.query("select count(*)::int n from public.account_access_approvals where status = 'PENDING'")).rows[0].n, 3);
  assert.equal((await db.query("select count(*)::int n from public.account_access_approval_events where event_type = 'ACCESS_REQUESTED'")).rows[0].n, 3);
  await db.exec("select set_config('request.jwt.claim.sub', '33333333-3333-4333-8333-333333333333', false); select set_config('request.jwt.claims', '{\"email\":\"pending@example.test\"}', false); set role authenticated");
  assert.equal((await db.query("select status from public.account_access_approvals where user_id = $1", [pendingUser])).rows[0].status, "PENDING");
  assert.equal((await db.query("select count(*)::int n from public.passports")).rows[0].n, 0);
  await assert.rejects(db.query("insert into public.passports(id, owner_email, user_email) values ($1, 'pending@example.test', 'pending@example.test')", [randomUUID()]), error => error.code === "42501");
  await db.query("select public.record_account_access_attempt(false)");
  await db.exec("reset role");
  assert.equal((await db.query("select count(*)::int n from public.account_access_approval_events where user_id = $1 and event_type = 'BLOCKED_LOGIN_ATTEMPT'", [pendingUser])).rows[0].n, 1);
  await db.query("update public.account_access_approvals set status='APPROVED', approved_at=now(), approved_by=$1 where user_id in ($1,$2)", [userA, userB]);
    await db.query("insert into public.passports values ($1, $2, $2, null), ($3, $4, $4, null)", [randomUUID(), "a@example.test", randomUUID(), "b@example.test"]);
    const passportRows = (await db.query("select id, owner_email from public.passports order by owner_email")).rows;
    await db.query("insert into public.verification_cases values ($1, $2, null, $3), ($4, $5, null, $6)", [caseA, "a@example.test", passportRows[0].id, caseB, "b@example.test", passportRows[1].id]);
    await db.query("insert into public.trust_reports values ($1, $2, null, $3, 'pending'), ($4, $5, null, $6, 'pending')", [randomUUID(), "a@example.test", passportRows[0].id, randomUUID(), "b@example.test", passportRows[1].id]);
    await db.query("insert into public.evidence_files values ($1, $2, $2, null, $3, $4), ($5, $6, $6, null, $7, $8)", [randomUUID(), "a@example.test", caseA, passportRows[0].id, randomUUID(), "b@example.test", caseB, passportRows[1].id]);
    await db.query("insert into public.teams(id) values ($1)", [teamA]);
    await db.query("insert into public.team_members(id, team_id, member_email, invitation_status) values ($1, $2, 'a@example.test', 'active')", [randomUUID(), teamA]);
    await db.query("insert into public.trust_reports values ($1, null, $2, null, 'team-owned')", [randomUUID(), teamA]);
    await db.query("insert into public.evidence_files values ($1, null, null, $2, null, null)", [randomUUID(), teamA]);
    const foreignKeyId = randomUUID();
    await db.query("insert into public.api_keys(id, owner_user_id, user_id, user_email, tenant_id) values ($1, $2, $2, 'a@example.test', $3)", [foreignKeyId, userA, userB]);
    await db.query("insert into storage.objects(bucket_id, name) values ('evidence-files', $1), ('evidence-files', $2)", [`${caseA}/evidence-a.pdf`, `${caseB}/evidence-b.pdf`]);

    assert.equal((await db.query("select has_table_privilege('authenticated', 'public.trust_reports', 'select') allowed")).rows[0].allowed, true);
    await db.exec("select set_config('request.jwt.claim.sub', '11111111-1111-4111-8111-111111111111', false); select set_config('request.jwt.claims', '{\"email\":\"a@example.test\"}', false); set role authenticated");
    assert.deepEqual((await db.query("select current_user, has_table_privilege(current_user, 'public.trust_reports', 'select') allowed")).rows[0], { current_user: "authenticated", allowed: true });
    assert.equal((await db.query("select public.security_closure_team_member(null::uuid) allowed")).rows[0].allowed, false);
    assert.equal((await db.query("select public.security_closure_passport_owner($1::uuid) allowed", [passportRows[0].id])).rows[0].allowed, true);
    await assert.rejects(db.query("update public.passports set verified = true, clearance = 'approved' where id = $1", [passportRows[0].id]), error => error.code === "42501");
    assert.equal((await db.query("select count(*)::int n from public.trust_reports")).rows[0].n, 2);
    assert.equal((await db.query("select count(*)::int n from public.evidence_files")).rows[0].n, 2);
    assert.equal((await db.query("select count(*)::int n from public.api_keys where id = $1", [foreignKeyId])).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from storage.objects where bucket_id = 'evidence-files'")).rows[0].n, 1);
    await db.query("insert into storage.objects(bucket_id, name) values ('evidence-files', $1)", [`${caseA}/evidence-a-new.pdf`]);
    assert.equal((await db.query("select count(*)::int n from storage.objects where bucket_id = 'evidence-files'")).rows[0].n, 2);
    const signalId = randomUUID();
    await db.query("insert into public.signals(id, owner_email) values ($1, 'b@example.test')", [signalId]);
    assert.equal((await db.query("select owner_email from public.signals where id = $1", [signalId])).rows[0].owner_email, "a@example.test");
    const auditId = randomUUID();
    await db.query("insert into public.audit_logs(id, owner_email, actor, metadata) values ($1, 'b@example.test', 'Candidate Alice', '{}')", [auditId]);
    assert.equal((await db.query("select owner_email from public.audit_logs where id = $1", [auditId])).rows[0].owner_email, "a@example.test");
    const foreignTeamId = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";
    await assert.rejects(db.query("insert into public.signals(id, team_id) values ($1, $2)", [randomUUID(), foreignTeamId]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.audit_logs(id, actor, team_id, metadata) values ($1, 'Candidate Alice', $2, '{}')", [randomUUID(), foreignTeamId]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.passports(id, owner_email, team_id) values ($1, 'a@example.test', $2)", [randomUUID(), foreignTeamId]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.trust_reports(id, owner_email, team_id) values ($1, 'a@example.test', $2)", [randomUUID(), foreignTeamId]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.trust_reports(id, owner_email, passport_id) values ($1, 'a@example.test', $2)", [randomUUID(), passportRows[1].id]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.verification_cases(id, owner_email, passport_id) values ($1, 'a@example.test', $2)", [randomUUID(), passportRows[1].id]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.evidence_files(id, owner_email, verification_case_id, passport_id) values ($1, 'a@example.test', $2, $3)", [randomUUID(), caseB, passportRows[1].id]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.decisions(id, owner_email, verification_case_id) values ($1, 'a@example.test', $2)", [randomUUID(), caseB]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.ai_agents(id, owner_user_id, owner_email, owner_enterprise_id) values ($1, $2, 'a@example.test', $3)", [randomUUID(), userA, userB]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.ai_agents(id, owner_user_id, owner_email) values ($1, $2, 'b@example.test')", [randomUUID(), userA]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.data_rights_requests(id, requester_user_id, requester_email) values ($1, $2, 'b@example.test')", [randomUUID(), userA]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.feedback_reports(id, submitted_by_user_id, submitted_by_email) values ($1, $2, 'b@example.test')", [randomUUID(), userA]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.help_questions(id, created_by_user_id, created_by_email) values ($1, $2, 'b@example.test')", [randomUUID(), userA]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.trust_assistant_questions(id, asked_by_user_id, asked_by_email) values ($1, $2, 'b@example.test')", [randomUUID(), userA]), error => error.code === "42501");
    const verifierId = randomUUID();
    await db.query("insert into public.verifiers(id, created_by, status) values ($1, $2, 'pending')", [verifierId, userA]);
    assert.equal((await db.query("select count(*)::int n from public.verifiers")).rows[0].n, 1);
    await assert.rejects(db.query("insert into public.verifiers(id, created_by, status) values ($1, $2, 'pending')", [randomUUID(), userB]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.verifiers(id, created_by, status) values ($1, $2, 'approved')", [randomUUID(), userA]), error => error.code === "42501");
    const certificationId = randomUUID();
    await db.query("insert into public.trust_certifications(id, created_by, status, notes) values ($1, $2, 'pending', 'request')", [certificationId, userA]);
    await db.query("update public.trust_certifications set notes = 'updated request' where id = $1", [certificationId]);
    await assert.rejects(db.query("update public.trust_certifications set status = 'verified' where id = $1", [certificationId]), error => error.code === "42501");
    assert.equal((await db.query("select status from public.trust_certifications where id = $1", [certificationId])).rows[0].status, "pending");
    await assert.rejects(db.query("insert into public.trust_reports(id, owner_email) values ($1, 'b@example.test')", [randomUUID()]), error => error.code === "42501");
    assert.equal((await db.query("update public.trust_reports set review_status = 'tampered' where owner_email = 'b@example.test' returning id")).rows.length, 0);
    await assert.rejects(db.query("delete from public.trust_reports where owner_email = 'b@example.test'"), error => error.code === "42501");
    assert.equal((await db.query("update storage.objects set name = name where name like 'bbbbbbbb-%' returning id")).rows.length, 0);
    assert.equal((await db.query("delete from storage.objects where name like 'bbbbbbbb-%' returning id")).rows.length, 0);
    await assert.rejects(db.query("insert into storage.objects(bucket_id, name) values ('evidence-files', $1)", [`${caseB}/forged.pdf`]), error => error.code === "42501");
    await assert.rejects(db.query("insert into public.enterprise_access_requests(name) values ('direct anon bypass')"), error => error.code === "42501");
    await db.exec("reset role; select set_config('request.jwt.claim.sub', '22222222-2222-4222-8222-222222222222', false); select set_config('request.jwt.claims', '{\"email\":\"b@example.test\"}', false); set role authenticated");
    assert.equal((await db.query("select count(*)::int n from public.trust_reports")).rows[0].n, 1);
    assert.equal((await db.query("select count(*)::int n from public.evidence_files")).rows[0].n, 1);
    assert.equal((await db.query("select count(*)::int n from storage.objects where bucket_id = 'evidence-files'")).rows[0].n, 1);
    assert.equal((await db.query("update public.trust_reports set review_status = 'tampered' where owner_email = 'a@example.test' returning id")).rows.length, 0);
    await db.exec("reset role; select set_config('request.jwt.claim.sub', '', false); select set_config('request.jwt.claims', '{}', false); set role anon");
    await assert.rejects(db.query("insert into public.enterprise_access_requests(name) values ('direct anon bypass')"), error => error.code === "42501");
    await assert.rejects(db.query("select count(*)::int n from storage.objects where bucket_id = 'evidence-files'"), error => error.code === "42501");
    await assert.rejects(db.query("insert into storage.objects(bucket_id, name) values ('evidence-files', $1)", [`${caseA}/anonymous.pdf`]), error => error.code === "42501");
    await db.exec("reset role; select set_config('request.jwt.claim.sub', '11111111-1111-4111-8111-111111111111', false); select set_config('request.jwt.claims', '{\"email\":\"a@example.test\"}', false); set role authenticated");
    await db.exec("reset role");
    await db.query("update public.account_access_approvals set status = 'PENDING', approved_at = null, approved_by = null where user_id = $1", [userA]);
    await db.exec("set role authenticated");
    await assert.rejects(db.query("select public.record_account_access_attempt(true)"), error => error.code === "42501");
    assert.equal((await db.query("select count(*)::int n from public.passports")).rows[0].n, 0);
    await db.exec("reset role");
    await db.query("update public.account_access_approvals set status = 'APPROVED', approved_at = now(), approved_by = $1 where user_id = $1", [userA]);
    await db.exec("set role authenticated");
    await db.query("select public.record_account_access_attempt(true)");
    assert.equal((await db.query("select last_successful_login is not null ok from public.account_access_approvals where user_id = $1", [userA])).rows[0].ok, true);
    await db.exec("reset role");
    await db.query("update public.account_access_approvals set status = 'PENDING' where user_id = $1", [userB]);
    await db.exec("select set_config('request.jwt.claim.sub', '22222222-2222-4222-8222-222222222222', false); select set_config('request.jwt.claims', '{\"email\":\"b@example.test\"}', false); set role authenticated");
    await db.query("select public.record_account_access_attempt(false)");
    await db.exec("reset role");
    assert.equal((await db.query("select count(*)::int n from public.account_access_approval_events where user_id = $1 and event_type = 'BLOCKED_LOGIN_ATTEMPT'", [userB])).rows[0].n, 1);
    await db.query("delete from public.account_access_approvals where user_id = $1", [userB]);
    await db.exec("select set_config('request.jwt.claim.sub', '22222222-2222-4222-8222-222222222222', false); select set_config('request.jwt.claims', '{\"email\":\"b@example.test\"}', false); set role authenticated");
    await db.query("select public.record_account_access_attempt(false)");
    await db.exec("reset role");
    assert.equal((await db.query("select count(*)::int n from public.account_access_approval_events where user_id = $1 and event_type = 'BLOCKED_LOGIN_ATTEMPT'", [userB])).rows[0].n, 1);
    await db.exec("reset role; set role service_role");
    assert.equal((await db.query("select count(*)::int n from public.trust_reports")).rows[0].n, 3);
    assert.equal((await db.query("select count(*)::int n from storage.objects")).rows[0].n, 3);
  } finally {
    await db.close();
  }
});