import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const sql=readFileSync(new URL("../../supabase/migrations/202607310001_environment_attestation_scope_continuity.sql",import.meta.url),"utf8");

test("migration creates the canonical Scope Continuity relational model",()=>{for(const table of ["execution_context_declarations","environment_attestations","scope_authorization_leases","scope_continuity_decisions","scope_decision_attestations","context_contradiction_events","scope_continuity_reviewer_actions"])assert.match(sql,new RegExp(`public\\.${table}`));});
test("every new table enables RLS and denies anonymous or direct authenticated writes",()=>{assert.match(sql,/enable row level security/);assert.match(sql,/revoke all on public\.%I from anon,authenticated/);assert.doesNotMatch(sql,/for insert to authenticated|for update to authenticated|for all to authenticated/i);});
test("tenant reads use canonical workspace authorization",()=>{assert.equal((sql.match(/user_can_access_trust_workspace\(enterprise_id\)/g)??[]).length,7);});
test("composite foreign keys reject cross-enterprise evidence attachment",()=>{assert.match(sql,/foreign key\(enterprise_id,execution_context_id\)/);assert.match(sql,/foreign key\(enterprise_id,attestation_id\)/);assert.match(sql,/foreign key\(enterprise_id,authorization_id\)/);assert.match(sql,/Cross-tenant attestation reference rejected/);});
test("unauthenticated and client-side service-role paths are denied",()=>{assert.match(sql,/auth\.role\(\)<>\'service_role\'/);assert.match(sql,/revoke all on function public\.persist_scope_continuity_decision_v1[^;]+from public,anon,authenticated/s);assert.match(sql,/grant execute on function public\.persist_scope_continuity_decision_v1[^;]+to service_role/s);});
test("evidence and decisions are append-only with superseding corrections",()=>{assert.match(sql,/prevent_scope_continuity_history_mutation/);assert.match(sql,/supersedes_attestation_id/);assert.match(sql,/supersedes_lease_id/);assert.match(sql,/supersedes_action_id/);});
test("append-only correction records cannot supersede themselves",()=>{for(const field of ["supersedes_attestation_id","supersedes_lease_id","supersedes_action_id"])assert.match(sql,new RegExp(`${field} is null or ${field}<>id`));});
test("idempotency and correlation are tenant-scoped and reject changed retries",()=>{assert.match(sql,/unique\(enterprise_id,execution_context_id,correlation_id\)/);assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/idempotentReplay/);assert.match(sql,/Scope Continuity idempotency conflict/);});
test("reused immutable identifiers are validated after conflict races",()=>{assert.ok((sql.match(/immutable_hash/g)??[]).length>=12);for(const message of ["Conflicting execution-context identifier","Conflicting environment-attestation identifier","Conflicting scope-authorization identifier"])assert.match(sql,new RegExp(message));});
test("provider assertions and cryptographic claims are constrained",()=>{assert.match(sql,/provider_or_third_party_identity is not null/);assert.match(sql,/provider_assertion','operator_assertion'[^;]+evidence_strength='asserted'/s);assert.match(sql,/signatureVerified'='true'/);assert.match(sql,/integrity_metadata->>'status'='verified'/);assert.match(sql,/integrity_metadata->>'digest'.*\^\[a-f0-9\]\{64\}\$/);});
test("Replay is a security-invoker projection and does not contain an external-action branch",()=>{assert.match(sql,/scope_continuity_replay with \(security_invoker=true\)/);assert.doesNotMatch(sql,/'external_action'/);assert.match(sql,/when 'provider_assertion' then 'ASSERTED'/);});
test("Evidence Graph direction reads context authorized and observed by evidence",()=>{assert.match(sql,/values\(enterprise,context_node,lease_node,'AUTHORIZED_BY'\)/);assert.match(sql,/values\(enterprise,context_node,item_node,'OBSERVED_BY'\)/);assert.doesNotMatch(sql,/values\(enterprise,lease_node,context_node,'AUTHORIZED_BY'\)/);});
test("migration is additive and contains no remote execution command",()=>{assert.doesNotMatch(sql,/\b(drop table|truncate table|delete from)\b|supabase db push|psql\s/i);});
