import { spawnSync } from "node:child_process";
import { existsSync,mkdirSync,readFileSync,writeFileSync } from "node:fs";
import { join,resolve } from "node:path";
type Status="PASS"|"FAIL"|"BLOCKED";type Check={name:string;status:Status;critical:boolean;detail:string;durationMs?:number};
const root=resolve(import.meta.dirname,"..");const checks:Check[]=[];const required=[
"src/lib/consensus/provider-capabilities.ts","src/lib/consensus/provider-registry.ts","src/lib/consensus/types.ts","src/lib/consensus/engine.ts","src/lib/consensus/independence.ts","src/lib/consensus/freshness.ts","src/lib/consensus/conflicts.ts","src/lib/consensus/explain.ts","src/lib/consensus/decision-lineage.ts","src/lib/consensus/replay.ts","src/lib/consensus/repository.ts","src/lib/consensus/health-service.ts",
"src/components/consensus/ConsensusStatus.tsx","src/components/consensus/ConsensusScore.tsx","src/components/consensus/ProviderContributionList.tsx","src/components/consensus/ConflictPanel.tsx","src/components/consensus/DecisionExplanation.tsx","src/components/consensus/ProviderHealthGrid.tsx","src/components/consensus/ConsensusTimeline.tsx","src/components/consensus/PolicySummary.tsx",
"app/dashboard/consensus/page.tsx","app/dashboard/consensus/subjects/[subjectId]/page.tsx","app/dashboard/consensus/decisions/[decisionId]/page.tsx","app/admin/consensus/providers/page.tsx","app/admin/consensus/policies/page.tsx",
"app/api/consensus/evaluate/route.ts","app/api/consensus/decisions/route.ts","app/api/consensus/decisions/[id]/route.ts","app/api/consensus/decisions/[id]/explanation/route.ts","app/api/consensus/subjects/[subjectId]/route.ts","app/api/consensus/subjects/[subjectId]/timeline/route.ts","app/api/consensus/providers/route.ts","app/api/consensus/providers/health/route.ts","app/api/consensus/policies/route.ts","app/api/admin/consensus/policies/route.ts","app/api/admin/consensus/policies/[id]/route.ts","app/api/admin/consensus/simulate/route.ts",
"supabase/migrations/202607200003_provider_consensus_engine.sql","docs/implementation/EPIC-17.2-IMPLEMENTATION-REPORT.md","docs/architecture/PROVIDER-CONSENSUS-ENGINE.md","docs/architecture/CONSENSUS-POLICY-MODEL.md","docs/architecture/PROVIDER-INDEPENDENCE.md","docs/security/CONSENSUS-INTEGRITY.md","docs/operations/PROVIDER-HEALTH-RUNBOOK.md","docs/operations/CONSENSUS-DECISION-RUNBOOK.md","docs/implementation/EPIC-17.2-TEST-REPORT.md"];
for(const path of required)checks.push({name:`Artifact: ${path}`,status:existsSync(join(root,path))?"PASS":"FAIL",critical:true,detail:existsSync(join(root,path))?"Present":"Missing"});
function source(name:string,path:string,patterns:RegExp[],critical=true){try{const value=readFileSync(join(root,path),"utf8");const missing=patterns.filter((pattern)=>!pattern.test(value));checks.push({name,status:missing.length?"FAIL":"PASS",critical,detail:missing.length?`${missing.length} invariant(s) absent`:"Required invariants present"});}catch{checks.push({name,status:"FAIL",critical,detail:"Unreadable artifact"});}}
const git=(args:string[])=>spawnSync("git",args,{cwd:root,encoding:"utf8",windowsHide:true});const branch=git(["branch","--show-current"]);checks.push({name:"Branch is main",status:branch.status===0&&branch.stdout.trim()==="main"?"PASS":"FAIL",critical:true,detail:branch.status===0?`Branch: ${branch.stdout.trim()}`:"Git branch unavailable"});
const files=git(["ls-files","--cached","--others","--exclude-standard"]);let conflicts=0,secrets=0;if(files.status===0){for(const relative of files.stdout.split(/\r?\n/).filter(Boolean)){if(relative.startsWith("reports/")||relative.startsWith(".env"))continue;try{const value=readFileSync(join(root,relative),"utf8");if(/^(<{7}|={7}|>{7})/m.test(value))conflicts+=1;if(/(?:sk_live_[A-Za-z0-9]{12,}|sb_secret_[A-Za-z0-9]{12,}|-----BEGIN (?:RSA |EC )?PRIVATE KEY-----)/.test(value))secrets+=1;}catch{}}}else conflicts=1;
checks.push({name:"Merge conflicts",status:conflicts?"FAIL":"PASS",critical:true,detail:conflicts?`${conflicts} file(s) contain conflict markers`:"No conflict markers"},{name:"Secret scan",status:secrets?"FAIL":"PASS",critical:true,detail:secrets?`${secrets} file(s) contain a high-confidence secret pattern`:"No high-confidence secret patterns"});
source("World ID and placeholder zero weight","src/lib/consensus/provider-capabilities.ts",[/providerKey: "world_id"[\s\S]+baseWeight: 0[\s\S]+positiveEvidence: false/,/placeholders\.map[\s\S]+baseWeight: 0/]);source("Weighted consensus is not provider voting","src/lib/consensus/engine.ts",[/baseWeight/,/freshnessMultiplier/,/healthMultiplier/,/independenceMultiplier/,/signalMultipliers/]);source("Duplicate and unknown evidence safety","src/lib/consensus/engine.ts",[/DUPLICATE_EVIDENCE/,/UNKNOWN_PROVIDER/,/CRYPTOGRAPHIC_VERIFICATION_REQUIRED/]);source("Correlation and freshness","src/lib/consensus/independence.ts",[/CORRELATED_EVIDENCE_PENALTY/]);source("Conflict and revocation","src/lib/consensus/conflicts.ts",[/CRITICAL/,/AUTHORITATIVE_REVOCATION_CONFLICT/]);source("Decision integrity","src/lib/consensus/decision-lineage.ts",[/canonicalizeJson/,/hashConsensusDecision/,/verifyConsensusDecision/]);source("Replay simulation","src/lib/consensus/replay.ts",[/excludeObservationIds/,/providerOutages/,/policyOverride/,/simulated:true/]);source("RLS, append-only, locking and Trust Events","supabase/migrations/202607200003_provider_consensus_engine.sql",[/enable row level security/,/prevent_consensus_history_mutation/,/pg_advisory_xact_lock/,/append_trust_event_v1/]);source("Required Trust Events","src/lib/trust-events/event-types.ts",[/consensus\.evaluation\.started/,/consensus\.evaluation\.completed/,/consensus\.conflict\.detected/,/provider\.health\.changed/]);source("Mandatory safety regressions","tests/consensus-engine.test.mjs",[/provider count and placeholders cannot verify/,/World ID remains inconclusive/,/duplicate evidence is counted once/,/high-assurance negative evidence overrides/]);
for(const [name,script] of [["Lint","lint"],["TypeScript","typecheck"],["Consensus unit/integration/RLS tests","test:consensus-engine"],["Production build","build"]] as const){const started=Date.now();const executable=process.platform==="win32"?(process.env.ComSpec??"C:\\Windows\\System32\\cmd.exe"):"npm";const args=process.platform==="win32"?["/d","/s","/c",`npm.cmd run ${script}`]:["run",script];const result=spawnSync(executable,args,{cwd:root,encoding:"utf8",windowsHide:true,timeout:600_000,env:{...process.env,NEXT_TELEMETRY_DISABLED:"1"}});checks.push({name,status:result.status===0?"PASS":"FAIL",critical:false,detail:result.status===0?"Command passed":`Command exited ${result.status??"without a code"}`,durationMs:Date.now()-started});}
checks.push({name:"Deployed Supabase migration and live RLS",status:"BLOCKED",critical:false,detail:"BLOCKED_BY_EXTERNAL_CONFIGURATION — verifier does not mutate infrastructure"},{name:"Production provider health and credentials",status:"BLOCKED",critical:false,detail:"BLOCKED_BY_EXTERNAL_CONFIGURATION — requires direct production evidence"});const criticalFailures=checks.filter((check)=>check.status==="FAIL"&&check.critical);const failures=checks.filter((check)=>check.status==="FAIL");const exitCode=criticalFailures.length?2:failures.length?1:0;
const timestamp=new Date().toISOString().replace(/[:.]/g,"-");const reports=join(root,"reports");mkdirSync(reports,{recursive:true});const reportPath=join(reports,`epic-17.2-verification-${timestamp}.md`);const lines=["# EPIC 17.2 Verification Report","",`Generated: ${new Date().toISOString()}`,`Aggregate exit code: ${exitCode}`,"","| Check | Status | Critical | Detail |","|---|---|---:|---|",...checks.map((check)=>`| ${check.name.replaceAll("|","\\|")} | ${check.status} | ${check.critical?"yes":"no"} | ${check.detail.replaceAll("|","\\|")}${check.durationMs===undefined?"":` (${check.durationMs} ms)`} |`),"","No deployment, infrastructure mutation, Production data access or secret output was performed.",""];writeFileSync(reportPath,lines.join("\n"),"utf8");console.log(`EPIC 17.2 verifier: ${exitCode===0?"PASSED":exitCode===1?"REMEDIATION REQUIRED":"CRITICAL BLOCKER"}`);console.log(`Report: ${reportPath}`);process.exitCode=exitCode;
