import { existsSync,readFileSync,readdirSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

type Severity="remediation"|"critical";
const findings:Array<{severity:Severity;check:string;detail:string}>=[];
const root=process.cwd();
const requiredFiles=[
  "docs/reviews/EPICS-17.1D-17.2-ARCHITECTURE-REVIEW.md","docs/architecture/evidence-graph.md","docs/architecture/trust-memory.md","src/lib/trust-core/canonicalize.ts","src/lib/trust-core/hash.ts","src/lib/trust-core/reason-codes.ts","src/lib/trust-core/references.ts","src/lib/trust-core/time.ts","src/lib/trust-core/types.ts","src/lib/trust-architecture/domains.ts","src/lib/trust-architecture/domain-registry.ts","src/lib/trust-architecture/evidence.ts","src/lib/trust-architecture/decision-contracts.ts","src/lib/trust-state/engine.ts","src/lib/trust-policy/policy-resolution.ts","supabase/migrations/202607210001_enterprise_trust_architecture.sql","app/api/trust-architecture/route.ts","app/dashboard/trust-architecture/page.tsx","app/admin/trust-architecture/page.tsx","tests/enterprise-trust-architecture.test.mjs","vercel.json","app/api/health/route.ts","app/api/ready/route.ts","public/robots.txt","public/security.txt"
];
function add(severity:Severity,check:string,detail:string){findings.push({severity,check,detail});}
function text(path:string){return readFileSync(join(root,path),"utf8");}
function output(result:ReturnType<typeof spawnSync>){return `${result.stdout??""}${result.stderr??""}${result.error?.message??""}`.slice(-2000);}
for(const path of requiredFiles)if(!existsSync(join(root,path)))add("critical","required-file",path);
const branch=spawnSync("git",["branch","--show-current"],{cwd:root,encoding:"utf8"});if(branch.status!==0||branch.stdout.trim()!=="main")add("critical","git-branch",branch.stdout.trim()||"unavailable");
const conflict=spawnSync("git",["diff","--check"],{cwd:root,encoding:"utf8"});if(conflict.status!==0)add("critical","git-conflicts",conflict.stdout||conflict.stderr);
if(existsSync(join(root,"src/lib/consensus/engine.ts"))){const source=text("src/lib/consensus/engine.ts");if(!/ConsensusRecommendation/.test(source)||!/recommendConsensus/.test(source))add("critical","consensus-separation","Consensus does not return a recommendation contract.");}
if(existsSync(join(root,"supabase/migrations/202607210001_enterprise_trust_architecture.sql"))){const sql=text("supabase/migrations/202607210001_enterprise_trust_architecture.sql");const consensus=sql.slice(sql.indexOf("create or replace function public.persist_consensus_decision_v1"),sql.indexOf("create or replace function public.apply_trust_state_decision_v1"));if(/insert into public\.subject_trust_state/.test(consensus))add("critical","consensus-state-mutation","Consensus persistence still mutates current state.");for(const token of ["user_can_access_trust_workspace","enable row level security","revoke all on public.%I from anon,authenticated","apply_trust_state_decision_v1","persist_trust_simulation_v1"])if(!sql.includes(token))add("critical","sql-rls",token);}
const worldSources=["src/lib/consensus/provider-capabilities.ts","src/lib/trust-events/provider-registry.ts","src/lib/trust-architecture/evidence.ts"].filter((path)=>existsSync(join(root,path))).map(text).join("\n");if(!/world_id/.test(worldSources)||!/server verification|serverVerified|SERVER_VERIFICATION/i.test(worldSources)||!/baseWeight:\s*0|positiveEvidence:\s*false|INCONCLUSIVE/.test(worldSources))add("critical","world-id-zero-weight","World ID fail-closed evidence was not found.");
const hopae=["src/lib/trust-events/gateway.ts","src/lib/trust-events/provider-registry.ts","tests/hopae-provider-integration.test.mjs"].filter((path)=>existsSync(join(root,path))).map(text).join("\n");if(!/hopae/i.test(hopae)||!/idempot/i.test(hopae)||!/HMAC|signature/i.test(hopae))add("critical","hopae-preservation","Signed/idempotent Hopae path evidence is incomplete.");
const sourceRoots=["app","src","lib","scripts"];const secretPattern=/(SUPABASE_SERVICE_ROLE_KEY|STRIPE_SECRET_KEY|OPENAI_API_KEY)\s*[:=]\s*["'][^"']{12,}["']/;for(const folder of sourceRoots){const directory=join(root,folder);if(!existsSync(directory))continue;const stack=[directory];while(stack.length){const current=stack.pop()!;for(const entry of readdirSync(current,{withFileTypes:true})){const path=join(current,entry.name);if(entry.isDirectory())stack.push(path);else if(/\.(ts|tsx|js|mjs)$/.test(entry.name)&&secretPattern.test(readFileSync(path,"utf8")))add("critical","secret-leak",path.slice(root.length+1));}}}
const typecheck=spawnSync(process.execPath,[join(root,"node_modules","typescript","bin","tsc"),"--noEmit"],{cwd:root,encoding:"utf8",timeout:120000});if(typecheck.status!==0)add("critical","typecheck",output(typecheck));
const tests=spawnSync(process.execPath,["--experimental-strip-types","--test","tests/enterprise-trust-architecture.test.mjs","tests/rls/enterprise-trust-architecture.test.mjs"],{cwd:root,encoding:"utf8",timeout:120000});if(tests.status!==0)add("critical","epic-18-tests",output(tests));
if(!existsSync(join(root,".next","BUILD_ID")))add("remediation","production-build","Run npm run build before the final verifier.");
const critical=findings.filter((item)=>item.severity==="critical");console.log("EPIC 18 VERIFIER");console.log(JSON.stringify({status:critical.length?"CRITICAL_BLOCKER":findings.length?"REMEDIATION_REQUIRED":"PASSED",branch:branch.stdout.trim(),checks:{requiredFiles:requiredFiles.length,typecheck:typecheck.status===0,tests:tests.status===0,buildArtifact:existsSync(join(root,".next","BUILD_ID"))},findings},null,2));process.exit(critical.length?2:findings.length?1:0);
