import { InteractiveDemoScenario, type DemoScenarioStep } from "@/components/interactive-demo-scenario";

const steps: DemoScenarioStep[] = [
  { title: "Synthetic candidate enters", state: "Intake recorded", explanation: "A candidate enters the remote hiring workflow with a polished profile, a newly created email address and employment history that does not fully match the submitted identity evidence.", evidence: "Candidate profile, application source, declared identity context, recruiter owner, workflow CS-HIRE-1043 and intake timestamp.", action: "Keep the workflow reviewable instead of allowing silent progression." },
  { title: "Verification begins", state: "Verification active", explanation: "Cyber Sentinels opens a verification workflow and links the recruiter, candidate and interview session before the case moves to panel review.", evidence: "Verification request, workflow owner, recruiter handoff, identity assurance response and initiation timestamp.", action: "Tie the candidate, recruiter and interview session to the same review path." },
  { title: "Session integrity fails", state: "Flag raised", explanation: "During the interview, channel evidence changes: device context shifts, the video feed becomes inconsistent and the voice/video timing no longer matches the verified session context.", evidence: "Signal category, source, review-priority score, channel evidence, anomaly timestamp and confidence explanation.", action: "Raise an active flag and prevent the signal from becoming buried in logs." },
  { title: "Governance review opens", state: "Review required", explanation: "The workflow pauses and routes identity context, session evidence and the injection-risk signal to Maya Chen in Trust Operations.", evidence: "Governance action, reviewer assignment, escalation reason, evidence reviewed and analyst notes.", action: "Assign ownership, require a reviewer decision and preserve the escalation reason." },
  { title: "Replay evidence generated", state: "Chronology ready", explanation: "The reviewer can replay the ordered sequence: candidate intake, verification start, session anomaly, escalation, analyst notes and final action.", evidence: "Timeline events, actor context, signal records, reviewer notes, workflow references and audit references.", action: "Make the investigation readable for security, talent and compliance stakeholders." },
  { title: "Risky session blocked", state: "Session blocked", explanation: "The compromised interview session is stopped and the candidate decision remains separate from the session-integrity action.", evidence: "Block action, human authority, timestamp, reviewer note, escalation closure reason and operational rationale.", action: "Block the risky session while keeping candidate outcome decisions human-governed." },
  { title: "Verification receipt issued", state: "Review complete", explanation: "An enterprise receipt summarizes the mismatch, the session anomaly, the evidence reviewed by the analyst and the replay reference.", evidence: "Verification receipt, evidence summary, audit references, reviewer attribution, workflow outcome and replay link.", action: "Issue a concise record that can be shared after the incident review." },
];

export default function HiringAttackDemoPage() {
  return <InteractiveDemoScenario label="Hiring Security" title="A synthetic applicant reaches the interview. The workflow does not have to guess." summary="Follow the operational chain from candidate intake to session block, human review, replay and verification receipt." steps={steps} nextScenario={{ href: "/demo/session-integrity", label: "Open Session Integrity" }} />;
}
