export type EnterpriseTrustRow = Record<string, any>;

export const mockTrustCertifications: EnterpriseTrustRow[] = [
  {
    id: "mock-cert-human",
    certification_type: "verified_human",
    status: "verified",
    trust_score: 91,
    risk_level: "low",
    verification_method: "governance_review",
    reviewed_by: "Maya Chen, Trust Operations",
    escalation_reason: "Candidate evidence matched the declared workflow owner and no unresolved session integrity flags remained.",
    evidence_reviewed: "Government ID assurance result, recruiter handoff record, session start metadata and evidence-chain checksum.",
    workflow_reference: "hiring-security/CS-HIRE-1042",
    analyst_notes: "Review completed after confirming the candidate identity evidence and interview workflow belonged to the same case.",
    notes: "Candidate identity and evidence review completed by Trust Operations.",
    issued_at: "2026-06-18T09:00:00.000Z",
    expires_at: "2026-09-18T09:00:00.000Z",
  },
  {
    id: "mock-cert-agent",
    certification_type: "verified_ai_agent",
    status: "pending",
    trust_score: 72,
    risk_level: "medium",
    verification_method: "permission_review",
    reviewed_by: "Governance Review Queue",
    escalation_reason: "Assistant can read evidence summaries and draft receipt language; production use requires explicit owner approval.",
    evidence_reviewed: "Agent permission set, owner record, last activity log and governance policy note.",
    workflow_reference: "agent-governance/CS-AGENT-219",
    analyst_notes: "Keep in review until People Security confirms read-only scope and audit logging.",
    notes: "Agent permissions require named owner review before production use.",
    issued_at: "2026-06-18T10:00:00.000Z",
    expires_at: "2026-07-18T10:00:00.000Z",
  },
  {
    id: "mock-cert-enterprise",
    certification_type: "verified_enterprise",
    status: "verified",
    trust_score: 88,
    risk_level: "low",
    verification_method: "workspace_governance_review",
    reviewed_by: "Avery Patel, Founder Control",
    escalation_reason: "Pilot workspace needs accountable review before first enterprise walkthrough.",
    evidence_reviewed: "Admin access posture, verification receipt route, replay route, governance dashboard and runtime validation log.",
    workflow_reference: "enterprise-pilot/CS-PILOT-001",
    analyst_notes: "Workspace controls are ready for pilot review; production policy language remains counsel-reviewed.",
    notes: "Enterprise workspace controls are ready for pilot review.",
    issued_at: "2026-06-18T11:00:00.000Z",
    expires_at: "2026-10-18T11:00:00.000Z",
  },
];

export const mockTrustAlerts: EnterpriseTrustRow[] = [
  {
    id: "mock-alert-drift",
    alert_type: "behavioural_drift",
    status: "active",
    alert_title: "Agent behaviour changed after permission update",
    alert_description: "Trust operations should compare the new permissions with the approved owner record before allowing production workflow access.",
    risk_level: "high",
    owner_name: "Trust Operations",
    escalation_reason: "Permission scope changed after prior approval.",
    evidence_reviewed: "Permission diff, owner record, agent activity log and prior certification.",
    workflow_reference: "agent-governance/CS-AGENT-219",
    analyst_notes: "Hold production workflow access until owner re-approves the changed scope.",
    created_at: "2026-06-18T12:00:00.000Z",
  },
  {
    id: "mock-alert-workflow",
    alert_type: "workflow_anomaly",
    status: "in_review",
    alert_title: "Hiring workflow skipped evidence review",
    alert_description: "Governance review should confirm whether the missing evidence is expected before the candidate workflow advances.",
    risk_level: "medium",
    owner_name: "People Security",
    escalation_reason: "Candidate workflow advanced without a completed evidence-chain review.",
    evidence_reviewed: "Recruiter handoff, evidence-chain status, session metadata and workflow audit log.",
    workflow_reference: "hiring-security/CS-HIRE-1042",
    analyst_notes: "Request evidence-chain completion or document the exception before closure.",
    created_at: "2026-06-18T12:15:00.000Z",
  },
  {
    id: "mock-alert-identity",
    alert_type: "synthetic_identity_flag",
    status: "active",
    alert_title: "Synthetic identity flag on candidate evidence",
    alert_description: "A human reviewer should inspect candidate verification records, session channel evidence and recruiter notes before any hiring outcome is recorded.",
    risk_level: "high",
    owner_name: "People Security",
    escalation_reason: "Candidate evidence and session behavior diverged after intake.",
    evidence_reviewed: "Candidate profile, identity assurance response, device-channel state, audio/video timing marker and recruiter note.",
    workflow_reference: "hiring-security/CS-HIRE-1043",
    analyst_notes: "Pause the interview session and keep the candidate employment decision separate from the session integrity action.",
    created_at: "2026-06-18T12:30:00.000Z",
  },
];

export const mockAiAgents: EnterpriseTrustRow[] = [
  {
    id: "mock-agent-review",
    agent_name: "Hiring Review Assistant",
    owner_name: "People Security",
    owner_email: "people-security@cybersentinels.ai",
    agent_type: "review_assistant",
    capabilities: ["evidence_summary", "workflow_review"],
    permissions: ["read_evidence", "draft_summary"],
    trust_score: 84,
    status: "verified",
    reviewed_by: "Maya Chen, Trust Operations",
    analyst_notes: "Read-only summary assistant; cannot approve, reject or change workflow state.",
    last_activity_at: "2026-06-18T12:20:00.000Z",
    created_at: "2026-06-17T08:00:00.000Z",
  },
  {
    id: "mock-agent-governance",
    agent_name: "Governance Intake Assistant",
    owner_name: "Trust Operations",
    owner_email: "trust@cybersentinels.ai",
    agent_type: "governance_assistant",
    capabilities: ["case_triage", "receipt_draft"],
    permissions: ["read_cases"],
    trust_score: 76,
    status: "pending",
    reviewed_by: "Governance Review Queue",
    analyst_notes: "Pending approval for receipt draft scope and evidence-source limits.",
    last_activity_at: "2026-06-18T11:45:00.000Z",
    created_at: "2026-06-16T09:30:00.000Z",
  },
];

export const mockProvenanceEvents: EnterpriseTrustRow[] = [
  {
    id: "mock-prov-1",
    subject_type: "ai_agent",
    event_type: "agent_registered",
    event_title: "AI agent registered",
    event_description: "Hiring Review Assistant entered governance review with owner, scope and audit logging references attached.",
    risk_level: "low",
    created_by: "Trust Operations",
    workflow_reference: "agent-governance/CS-AGENT-219",
    created_at: "2026-06-18T12:00:00.000Z",
  },
  {
    id: "mock-prov-2",
    subject_type: "workflow",
    event_type: "evidence_uploaded",
    event_title: "Evidence added to hiring review",
    event_description: "Interview evidence was attached to a governance case with recruiter handoff, session metadata and analyst note references.",
    risk_level: "medium",
    created_by: "People Security",
    workflow_reference: "hiring-security/CS-HIRE-1042",
    created_at: "2026-06-18T12:10:00.000Z",
  },
  {
    id: "mock-prov-3",
    subject_type: "enterprise",
    event_type: "certification_issued",
    event_title: "Enterprise certification updated",
    event_description: "Workspace governance controls passed review after admin access, replay route and receipt route checks were confirmed.",
    risk_level: "low",
    created_by: "Founder Control",
    workflow_reference: "enterprise-pilot/CS-PILOT-001",
    created_at: "2026-06-18T12:40:00.000Z",
  },
];
