export type EnterpriseTrustRow = Record<string, any>;

export const mockTrustCertifications: EnterpriseTrustRow[] = [
  {
    id: "mock-cert-human",
    certification_type: "verified_human",
    status: "verified",
    trust_score: 91,
    risk_level: "low",
    verification_method: "governance_review",
    reviewed_by: "Security Review",
    notes: "Candidate identity and evidence review completed.",
    issued_at: "2026-06-18T09:00:00.000Z",
    expires_at: "2026-09-18T09:00:00.000Z",
  },
  {
    id: "mock-cert-agent",
    certification_type: "verified_ai_agent",
    status: "pending",
    trust_score: 72,
    risk_level: "medium",
    verification_method: "permission_review",
    reviewed_by: "Governance Queue",
    notes: "Agent permissions require review before production use.",
    issued_at: "2026-06-18T10:00:00.000Z",
    expires_at: "2026-07-18T10:00:00.000Z",
  },
  {
    id: "mock-cert-enterprise",
    certification_type: "verified_enterprise",
    status: "verified",
    trust_score: 88,
    risk_level: "low",
    verification_method: "workspace_governance_review",
    reviewed_by: "Founder Control",
    notes: "Enterprise workspace controls are ready for pilot review.",
    issued_at: "2026-06-18T11:00:00.000Z",
    expires_at: "2026-10-18T11:00:00.000Z",
  },
];

export const mockTrustAlerts: EnterpriseTrustRow[] = [
  {
    id: "mock-alert-drift",
    alert_type: "behavioural_drift",
    status: "active",
    alert_title: "Agent behaviour changed after permission update",
    alert_description: "Review new permissions before allowing production workflow access.",
    risk_level: "high",
    created_at: "2026-06-18T12:00:00.000Z",
  },
  {
    id: "mock-alert-workflow",
    alert_type: "workflow_anomaly",
    status: "in_review",
    alert_title: "Hiring workflow skipped evidence review",
    alert_description: "Governance review should confirm whether the missing evidence is expected.",
    risk_level: "medium",
    created_at: "2026-06-18T12:15:00.000Z",
  },
  {
    id: "mock-alert-identity",
    alert_type: "synthetic_identity_flag",
    status: "active",
    alert_title: "Synthetic identity flag on candidate evidence",
    alert_description: "Human reviewer should inspect candidate verification records.",
    risk_level: "high",
    created_at: "2026-06-18T12:30:00.000Z",
  },
];

export const mockAiAgents: EnterpriseTrustRow[] = [
  {
    id: "mock-agent-review",
    agent_name: "Hiring Review Assistant",
    owner_name: "People Security",
    owner_email: "security@example.com",
    agent_type: "review_assistant",
    capabilities: ["evidence_summary", "workflow_review"],
    permissions: ["read_evidence", "draft_summary"],
    trust_score: 84,
    status: "verified",
    last_activity_at: "2026-06-18T12:20:00.000Z",
    created_at: "2026-06-17T08:00:00.000Z",
  },
  {
    id: "mock-agent-governance",
    agent_name: "Governance Intake Assistant",
    owner_name: "Trust Operations",
    owner_email: "governance@example.com",
    agent_type: "governance_assistant",
    capabilities: ["case_triage", "receipt_draft"],
    permissions: ["read_cases"],
    trust_score: 76,
    status: "pending",
    last_activity_at: "2026-06-18T11:45:00.000Z",
    created_at: "2026-06-16T09:30:00.000Z",
  },
];

export const mockProvenanceEvents: EnterpriseTrustRow[] = [
  {
    id: "mock-prov-1",
    subject_type: "ai_agent",
    event_type: "agent_registered",
    event_title: "AI agent registered",
    event_description: "Hiring Review Assistant entered governance review.",
    risk_level: "low",
    created_by: "system",
    created_at: "2026-06-18T12:00:00.000Z",
  },
  {
    id: "mock-prov-2",
    subject_type: "workflow",
    event_type: "evidence_uploaded",
    event_title: "Evidence added to hiring review",
    event_description: "Interview evidence was attached to a governance case.",
    risk_level: "medium",
    created_by: "reviewer",
    created_at: "2026-06-18T12:10:00.000Z",
  },
  {
    id: "mock-prov-3",
    subject_type: "enterprise",
    event_type: "certification_issued",
    event_title: "Enterprise certification updated",
    event_description: "Workspace governance controls passed review.",
    risk_level: "low",
    created_by: "founder_control",
    created_at: "2026-06-18T12:40:00.000Z",
  },
];
