import "server-only";

import { createServiceRoleClient } from "@/lib/supabase/service-role";
import type { CanonicalTrustEvent } from "@/src/lib/trust-events/types";
import type { ConsensusDecision, ConsensusPolicy, ProviderHealth, ProviderObservation } from "./types.ts";

function fail(operation:string,error:unknown):never{console.error(`${operation} failed.`,{code:(error as {code?:string})?.code});throw Object.assign(new Error(`${operation} failed safely.`),{status:500,code:"CONSENSUS_PERSISTENCE_FAILED"});}
const observation=(row:Record<string,unknown>):ProviderObservation=>({observationId:String(row.observation_id),enterpriseId:String(row.enterprise_id),subjectId:String(row.subject_id),workflowId:row.workflow_id?String(row.workflow_id):null,providerKey:String(row.provider_key),signalType:String(row.signal_type),result:String(row.result) as ProviderObservation["result"],assurance:Number(row.assurance),quality:Number(row.quality),signatureVerified:row.signature_verified===true,serverVerified:row.server_verified===true,authoritative:row.authoritative===true,evidenceDigest:String(row.evidence_digest),evidenceReference:String(row.evidence_reference),correlationKey:row.correlation_key?String(row.correlation_key):null,occurredAt:String(row.occurred_at),receivedAt:String(row.received_at),expiresAt:row.expires_at?String(row.expires_at):null,supersedesObservationId:row.supersedes_observation_id?String(row.supersedes_observation_id):null,revokedObservationId:row.revoked_observation_id?String(row.revoked_observation_id):null,reasonCodes:Array.isArray(row.reason_codes)?row.reason_codes.map(String):[]});

export function consensusRepository(){const db=createServiceRoleClient();return {
  async chainHead(enterpriseId:string){const result=await db.from("trust_event_chain_heads").select("last_sequence,last_event_hash").eq("enterprise_id",enterpriseId).eq("partition_key","default").maybeSingle();if(result.error)fail("Consensus chain head",result.error);return {sequence:Number(result.data?.last_sequence??0),eventHash:result.data?.last_event_hash?String(result.data.last_event_hash):null};},
  async observations(enterpriseId:string,subjectId:string,asOf?:string){let query=db.from("provider_observations").select("observation_id,enterprise_id,subject_id,workflow_id,provider_key,signal_type,result,assurance,quality,signature_verified,server_verified,authoritative,evidence_digest,evidence_reference,correlation_key,occurred_at,received_at,expires_at,supersedes_observation_id,revoked_observation_id,reason_codes").eq("enterprise_id",enterpriseId).eq("subject_id",subjectId).order("occurred_at",{ascending:true}).order("observation_id",{ascending:true});if(asOf)query=query.lte("received_at",asOf);const result=await query;if(result.error)fail("Consensus observations",result.error);return (result.data??[]).map((row)=>observation(row as Record<string,unknown>));},
  async health(enterpriseId:string,asOf?:string){let query=db.from("provider_health_snapshots").select("provider_key,state,observed_at,latency_ms,error_rate,timeout_rate,signature_failures,schema_failures,circuit_open,reason_codes").eq("enterprise_id",enterpriseId).order("observed_at",{ascending:false});if(asOf)query=query.lte("observed_at",asOf);const result=await query;if(result.error)fail("Provider health",result.error);const seen=new Set<string>();return (result.data??[]).flatMap((row)=>{if(seen.has(row.provider_key))return[];seen.add(row.provider_key);return [{providerKey:String(row.provider_key),state:String(row.state) as ProviderHealth["state"],observedAt:String(row.observed_at),latencyMs:row.latency_ms===null?null:Number(row.latency_ms),errorRate:row.error_rate===null?null:Number(row.error_rate),timeoutRate:row.timeout_rate===null?null:Number(row.timeout_rate),signatureFailures:Number(row.signature_failures??0),schemaFailures:Number(row.schema_failures??0),circuitOpen:row.circuit_open===true,reasonCodes:Array.isArray(row.reason_codes)?row.reason_codes.map(String):[]}];});},
  async policies(enterpriseId:string,asOf?:string){let query=db.from("consensus_policy_versions").select("policy_json,valid_from").or(`enterprise_id.is.null,enterprise_id.eq.${enterpriseId}`).order("valid_from",{ascending:false});if(asOf)query=query.lte("valid_from",asOf);const result=await query;if(result.error)fail("Consensus policies",result.error);return (result.data??[]).map((row)=>row.policy_json as unknown as ConsensusPolicy);},
  async priorDecision(enterpriseId:string,subjectId:string){const result=await db.from("consensus_decisions").select("decision_id,state").eq("enterprise_id",enterpriseId).eq("subject_id",subjectId).eq("simulated",false).order("evaluated_at",{ascending:false}).limit(1).maybeSingle();if(result.error)fail("Prior consensus decision",result.error);return result.data?{decisionId:String(result.data.decision_id),state:String(result.data.state) as ConsensusDecision["state"]}:null;},
  async persist(decision:ConsensusDecision,events:CanonicalTrustEvent[],correlationId:string){const result=await db.rpc("persist_consensus_decision_v1",{p_decision:decision,p_trust_events:events,p_correlation_id:correlationId});if(result.error){if(/chain conflict/i.test(result.error.message))return {status:"CHAIN_CONFLICT" as const};fail("Consensus decision persistence",result.error);}return result.data as {status:"CREATED"|"DUPLICATE";decisionId:string;decisionHash:string;recommendedState:string;confidence:number};},
  async decisions(enterpriseId:string,limit:number,cursor?:string){let query=db.from("consensus_decisions").select("decision_id,subject_id,workflow_id,policy_id,policy_version,evaluated_at,state,prior_state,confidence,reason_codes,decision_hash,prior_decision_id,simulated").eq("enterprise_id",enterpriseId).order("evaluated_at",{ascending:false}).order("decision_id",{ascending:false}).limit(limit+1);if(cursor){const decoded=JSON.parse(Buffer.from(cursor,"base64url").toString("utf8"));query=query.or(`evaluated_at.lt.${decoded.evaluatedAt},and(evaluated_at.eq.${decoded.evaluatedAt},decision_id.lt.${decoded.decisionId})`);}const result=await query;if(result.error)fail("Consensus decisions",result.error);return result.data??[];},
  async subjectDecisions(enterpriseId:string,subjectId:string,limit=100){const result=await db.from("consensus_decisions").select("decision_id,subject_id,workflow_id,policy_id,policy_version,evaluated_at,state,prior_state,confidence,reason_codes,decision_hash,prior_decision_id,simulated").eq("enterprise_id",enterpriseId).eq("subject_id",subjectId).order("evaluated_at",{ascending:false}).order("decision_id",{ascending:false}).limit(limit);if(result.error)fail("Subject consensus timeline",result.error);return result.data??[];},
  async decision(enterpriseId:string,decisionId:string){const result=await db.from("consensus_decisions").select("decision_json").eq("enterprise_id",enterpriseId).eq("decision_id",decisionId).maybeSingle();if(result.error)fail("Consensus decision",result.error);return result.data?.decision_json as unknown as ConsensusDecision|null;},
  async subjectState(enterpriseId:string,subjectId:string){const result=await db.from("subject_trust_state").select("subject_id,workflow_id,state,confidence,current_decision_id,updated_at").eq("enterprise_id",enterpriseId).eq("subject_id",subjectId).maybeSingle();if(result.error)fail("Subject trust state",result.error);return result.data;},
  async createPolicy(enterpriseId:string,actorId:string,policy:ConsensusPolicy,correlationId:string,event:CanonicalTrustEvent){const result=await db.rpc("create_consensus_policy_v1",{p_enterprise_id:enterpriseId,p_actor_id:actorId,p_policy:policy,p_correlation_id:correlationId,p_trust_event:event});if(result.error)fail("Consensus policy creation",result.error);return result.data;},
  async recordHealth(enterpriseId:string,health:ProviderHealth,event:CanonicalTrustEvent,correlationId:string){const result=await db.rpc("record_provider_health_v1",{p_enterprise_id:enterpriseId,p_health:health,p_trust_event:event,p_correlation_id:correlationId});if(result.error)fail("Provider health persistence",result.error);return result.data;},
};}
