import "server-only";

import { signTrustEvent } from "@/src/lib/trust-events/hash";
import { TRUST_EVENT_CANONICALIZATION,TRUST_EVENT_HASH_ALGORITHM,TRUST_EVENT_SCHEMA_VERSION,type CanonicalTrustEvent } from "@/src/lib/trust-events/types";
import { evaluateConsensus } from "./engine.ts";
import { defaultConsensusPolicy } from "./policy.ts";
import { consensusRepository } from "./repository.ts";

function eventBase(input:{enterpriseId:string;subjectId:string;workflowId:string|null;evaluatedAt:string;decisionId:string;correlationId:string}){return {enterpriseId:input.enterpriseId,schemaVersion:TRUST_EVENT_SCHEMA_VERSION,subject:{type:"HUMAN" as const,id:input.subjectId},actor:{type:"SYSTEM" as const,id:"provider-consensus-engine"},workflow:input.workflowId?{type:"WORKFLOW" as const,id:input.workflowId}:null,session:null,authority:null,provider:{key:"cyber_sentinels_consensus",protocol:"UNSIGNED" as const,serverVerified:true,eventId:input.decisionId,transactionId:input.correlationId,deliveryId:null},evidenceReferences:[`consensus-decision:${input.decisionId}`],occurredAt:input.evaluatedAt,receivedAt:input.evaluatedAt,canonicalization:TRUST_EVENT_CANONICALIZATION,hashAlgorithm:TRUST_EVENT_HASH_ALGORITHM,ordering:{late:false,supersedesEventId:null,providerSequence:null}};}

export async function evaluateAndPersistConsensus(input:{enterpriseId:string;subjectId:string;workflowId?:string|null;correlationId:string}){
  const repository=consensusRepository();const [observations,health,policies,prior]=await Promise.all([repository.observations(input.enterpriseId,input.subjectId),repository.health(input.enterpriseId),repository.policies(input.enterpriseId),repository.priorDecision(input.enterpriseId,input.subjectId)]);const policy=policies.find((item)=>item.active)??defaultConsensusPolicy;
  for(let attempt=0;attempt<5;attempt+=1){const decision=evaluateConsensus({enterpriseId:input.enterpriseId,subjectId:input.subjectId,workflowId:input.workflowId,observations,health,policy,priorDecision:prior});const head=await repository.chainHead(input.enterpriseId);const base=eventBase({enterpriseId:input.enterpriseId,subjectId:input.subjectId,workflowId:input.workflowId??null,evaluatedAt:decision.evaluatedAt,decisionId:decision.decisionId,correlationId:input.correlationId});let sequence=head.sequence;let previousHash=head.eventHash;const events:CanonicalTrustEvent[]=[];
    for(const [eventType,codes,facts] of [["consensus.evaluation.started",["CONSENSUS_EVALUATION_STARTED"],{policyVersion:decision.policyVersion,evidenceSnapshotHash:decision.evidenceSnapshotHash}],["consensus.evaluation.completed",decision.reasonCodes,{state:decision.state,confidence:decision.confidence,decisionHash:decision.decisionHash}],[`consensus.${decision.state.toLowerCase()}`,[`CONSENSUS_${decision.state}`],{state:decision.state,confidence:decision.confidence}]] as const){const signed=signTrustEvent({...base,eventId:crypto.randomUUID(),eventType,reasonCodes:[...codes],normalizedFacts:facts,sequence:++sequence,previousHash});events.push(signed);previousHash=signed.eventHash;}
    for(const conflict of decision.conflicts){const signed=signTrustEvent({...base,eventId:crypto.randomUUID(),eventType:"consensus.conflict.detected",reasonCodes:[conflict.reasonCode],normalizedFacts:{severity:conflict.severity,type:conflict.type,conflictId:conflict.conflictId},sequence:++sequence,previousHash});events.push(signed);previousHash=signed.eventHash;}
    const persisted=await repository.persist(decision,events,input.correlationId);if(persisted.status==="CHAIN_CONFLICT")continue;if(persisted.status==="DUPLICATE"){const existing=await repository.decision(input.enterpriseId,persisted.decisionId);return {decision:existing??decision,replayed:true};}return {decision,replayed:false};}
  throw Object.assign(new Error("Consensus ledger contention exceeded the safe retry limit."),{status:503,code:"CONSENSUS_CHAIN_CONTENTION"});
}
