-- Record independent Agent Gamma authority issuance as a first-class native
-- Replay event. The constraint replacement is atomic, so invalid event types
-- are never accepted outside this explicitly enumerated set.

begin;

alter table public.operational_entity_native_replay_events
  drop constraint if exists operational_entity_native_replay_events_event_type_check;

alter table public.operational_entity_native_replay_events
  add constraint operational_entity_native_replay_events_event_type_check
  check(event_type in (
    'MANIFEST_REGISTERED','CREDENTIAL_REGISTERED','CHALLENGE_ISSUED','CHALLENGE_VERIFIED','NATIVE_IDENTITY_VERIFIED','OWNER_CONFIRMED','RUNTIME_BOUND','BUILD_VERIFIED','ENTITY_CHANGED','CREDENTIAL_ROTATED','CREDENTIAL_REVOKED','VERIFICATION_EXPIRED','REVERIFICATION_COMPLETED','ENTITY_SUSPENDED','AUTHORITY_REVOKED','OWNER_REVOKED','MANIFEST_REVOKED',
    'ALPHA_VERIFIED','BETA_REGISTERED','BETA_VERIFIED','ALPHA_AUTHORITY_ISSUED','GAMMA_AUTHORITY_ISSUED','DELEGATION_PROPOSED','DELEGATION_VALIDATED','BETA_ACCEPTED','DELEGATION_ACTIVATED','BETA_ACTION_REQUESTED','BETA_ACTION_ALLOWED','BETA_ACTION_REVIEW_REQUIRED','BETA_ACTION_DENIED','BETA_SCOPE_VIOLATION_DENIED','PARENT_AUTHORITY_REVOKED','DELEGATION_INVALIDATED','DELEGATION_REVOKED',
    'DELEGATED_AUTHORITY_VALID','ACTION_REQUESTED','DECISION_ALLOW','DECISION_DENY','HUMAN_APPROVAL_RECORDED','ENFORCEMENT_REQUESTED','ENFORCEMENT_ACKNOWLEDGED','DESTINATION_OBSERVED','OUTCOME_CONFIRMED','UNAUTHORIZED_EXECUTION_OBSERVED','CONTROL_FAILURE_DETECTED','AUTHORITY_CHANGED_BEFORE_EXECUTION','CONTROL_RECOVERY_CONFIRMED'
  ));

commit;
