-- Historical Production migration identity only; no executable SQL.
-- Already applied to Production kecgtsfibkypjuaxqbjx; do not replay.
-- Original SQL: supabase/history/production/20260819084329_restrict_evidence_trigger_functions.sql
-- This marker does not reconstruct the archived change on a fresh database.
