-- Canonical Replay appends the immutable authority-integrity, Trust Twin,
-- forecast, and adaptive-verification projections captured at decision time.
-- Keep those controlled event types compatible with the transaction ledger.

alter table public.canonical_trust_transaction_events
  drop constraint if exists canonical_trust_transaction_events_event_type_check;

alter table public.canonical_trust_transaction_events
  add constraint canonical_trust_transaction_events_event_type_check check(event_type in (
    'DECISION_PERSISTED','EVIDENCE_GRAPH_LINKED','REPLAY_WRITTEN','TRUST_MEMORY_WRITTEN',
    'EXTERNAL_EXECUTION_REQUESTED','EXTERNAL_ACKNOWLEDGED','EXTERNAL_OUTCOME_RECORDED',
    'NATIVE_ENFORCEMENT_REQUESTED','NATIVE_ENFORCEMENT_ACKNOWLEDGED','DESTINATION_OBSERVED',
    'NATIVE_OUTCOME_CORRELATED','CONTROL_FAILURE_DETECTED','REVIEW_REQUESTED','REVIEW_RESOLVED',
    'AUTHORITY_BOUND_PARAMETERS_SNAPSHOTTED','AUTHORITY_PARAMETER_BINDING_EVALUATED',
    'RUNTIME_AUTHORITY_OBSERVED','AUTHORIZATION_PROPAGATION_TIMELINE_RECORDED',
    'AIMS_COMPATIBLE_EVIDENCE_MAPPED','AUTHORIZATION_CHANGE_PROPAGATION_OBSERVED',
    'MODEL_CONTROLLED_SECURITY_BOUNDARY','CONSENT_BOUNDARY_MODEL_CONTROLLED',
    'TENANT_BOUNDARY_MISMATCH','CREDENTIAL_DESTINATION_CHANGED','MODEL_CONTROLLED_PROXY',
    'CREDENTIAL_SENT_OUTSIDE_BOUND_DESTINATION','DESTINATION_AUTHORITY_UNRESOLVED',
    'TOOL_SECURITY_SCHEMA_CHANGE','STALE_AUTHORITY_STILL_ACTIVE',
    'DELEGATED_SUBJECT_CONTEXT_LOST','RETROSPECTIVE_TOOL_AUTHORITY_REVIEW_RECOMMENDED',
    'AUTHORITY_PARAMETER_DRIFT','DESTINATION_BINDING_LOST','UNRESOLVED_PARAMETER_PROVENANCE',
    'STALE_AUTHORITY_POSSIBLE','RUNTIME_AUTHORITY_MISMATCH','DESTINATION_AUTHORITY_MISMATCH',
    'AUTHORITY_PROPAGATION_UNRESOLVED','PROVIDER_CONFLICT',
    'TRUST_TWIN_PROJECTED','TRUST_PRESSURE_EVALUATED','TRUST_BUDGET_EVALUATED',
    'TRUST_FORECAST_EVALUATED','TRUST_FORECAST_CHANGED','TRUST_FORECAST_CONTROL_RECOMMENDED',
    'TWIN_AUTHORITY_CHANGED','TWIN_MONITORING_DEGRADED','TWIN_IDENTITY_CHANGED',
    'TWIN_RUNTIME_CHANGED','TWIN_DESTINATION_CHANGED','TWIN_PRESSURE_SPIKE',
    'TWIN_BUDGET_NEAR_LIMIT','TWIN_BUDGET_EXCEEDED','TWIN_FORECAST_DETERIORATED',
    'TWIN_FORECAST_IMPROVED','ADAPTIVE_VERIFICATION_EVALUATED'
  ));

comment on constraint canonical_trust_transaction_events_event_type_check
  on public.canonical_trust_transaction_events
  is 'Allowlist for canonical transaction lifecycle and controlled decision-time projection events appended to Replay.';
