import "server-only";
import { createTrustDecisionContract } from "../trust-architecture/decision-contracts.ts";
import type { AssuranceLevel, EvidenceObject, EvidenceResult } from "../trust-architecture/evidence.ts";
import { TRUST_CANONICALIZATION, TRUST_HASH_ALGORITHM } from "../trust-core/types.ts";
import { signTrustEvent } from "../trust-events/hash.ts";
import { TRUST_EVENT_CANONICALIZATION,TRUST_EVENT_HASH_ALGORITHM,TRUST_EVENT_SCHEMA_VERSION } from "../trust-events/types.ts";
import type { ConsensusRecommendation, ProviderObservation } from "../consensus/types.ts";
import { evaluateTrustState } from "./engine.ts";
import { trustStateRepository } from "./repository.ts";

function assurance(value:number):AssuranceLevel{return value>=0.9?"VERY_HIGH":value>=0.7?"HIGH":value>=0.4?"MEDIUM":value>0?"LOW":"NONE";}
function result(observation:ProviderObservation,included:boolean):EvidenceResult{if(observation.result==="REVOKED")return "REVOKED";if(observation.result==="UNAVAILABLE")return "UNAVAILABLE";if(["FAIL","BLOCKED"].includes(observation.result))return "NEGATIVE";if(observation.result==="PASS"&&included&&observation.providerKey!=="world_id")return "POSITIVE";return "INCONCLUSIVE";}

function recommendationEvidence(recommendation:ConsensusRecommendation,observations:ProviderObservation[]):EvidenceObject[]{const byId=new Map(observations.map((item)=>[item.observationId,item]));return recommendation.evidence.map((line)=>{const item=byId.get(line.observationId);if(!item)throw Object.assign(new Error("Consensus recommendation references missing evidence."),{code:"EVIDENCE_REFERENCE_MISSING"});return {evidenceId:item.observationId,enterpriseId:item.enterpriseId,domainKey:"IDENTITY",subjectId:item.subjectId,subjectType:"HUMAN",evidenceType:item.signalType,sourceType:"PROVIDER_OBSERVATION",sourceKey:item.providerKey,result:result(item,line.included),assuranceLevel:assurance(item.assurance),cryptographicallyVerified:item.signatureVerified,serverVerified:item.serverVerified,occurredAt:item.occurredAt,receivedAt:item.receivedAt,...(item.expiresAt?{expiresAt:item.expiresAt}:{}),payloadHash:item.evidenceDigest,canonicalization:TRUST_CANONICALIZATION,hashAlgorithm:TRUST_HASH_ALGORITHM,references:[{refType:"PROVIDER_OBSERVATION",refId:item.observationId}],reasonCodes:[...item.reasonCodes,...(line.ignoredReason?[line.ignoredReason]:[])]};});}

export async function applyConsensusRecommendation(input:{recommendation:ConsensusRecommendation;observations:ProviderObservation[];correlationId:string}){const repository=trustStateRepository();const existing=await repository.forRecommendation(input.recommendation.enterpriseId,input.recommendation.recommendationId);if(existing)return {contract:null,decision:existing,persisted:{status:"DUPLICATE" as const,stateDecisionId:String(existing.state_decision_id),state:String(existing.next_state)}};const evidence=recommendationEvidence(input.recommendation,input.observations);const current=await repository.current(input.recommendation.enterpriseId,input.recommendation.subjectId);const requestedAt=input.recommendation.evaluatedAt;const contract=createTrustDecisionContract({enterpriseId:input.recommendation.enterpriseId,domainKey:"IDENTITY",subjectId:input.recommendation.subjectId,...(input.recommendation.workflowId?{workflowId:input.recommendation.workflowId}:{}),policyId:input.recommendation.policyId,policyVersion:input.recommendation.policyVersion,evidenceSnapshotHash:input.recommendation.evidenceSnapshotHash,requestedAt,decisionInputs:{recommendationId:input.recommendation.recommendationId,recommendedState:input.recommendation.recommendedState,confidence:input.recommendation.confidence,priorState:current?.state??"UNKNOWN"}});const decision=evaluateTrustState({contract,priorState:current?.state??"UNKNOWN",recommendation:{recommendationId:input.recommendation.recommendationId,recommendedState:input.recommendation.recommendedState,confidence:input.recommendation.confidence,reasonCodes:input.recommendation.reasonCodes,evidenceSnapshotHash:input.recommendation.evidenceSnapshotHash},evidence,policy:{policyId:input.recommendation.policyId,policyVersion:input.recommendation.policyVersion,allowRecoveryFromBlocked:false,minimumEvidenceForTrusted:1,minimumEvidenceForVerified:Math.max(2,Number(input.recommendation.thresholds.minimumIndependentGroupsVerified??2))},decidedAt:requestedAt});
  for(let attempt=0;attempt<5;attempt+=1){const head=await repository.chainHead(decision.enterpriseId);const event=signTrustEvent({eventId:crypto.randomUUID(),enterpriseId:decision.enterpriseId,schemaVersion:TRUST_EVENT_SCHEMA_VERSION,eventType:"runtime.trust_state.transitioned",subject:{type:"HUMAN",id:decision.subjectId},actor:{type:"SYSTEM",id:"trust-state-engine"},workflow:input.recommendation.workflowId?{type:"WORKFLOW",id:input.recommendation.workflowId}:null,session:null,authority:null,provider:{key:"cyber_sentinels_trust_state",protocol:"UNSIGNED",serverVerified:true,eventId:decision.stateDecisionId,transactionId:input.correlationId,deliveryId:null},normalizedFacts:{priorState:decision.priorState,nextState:decision.nextState,decisionHash:decision.decisionHash,decisionContractId:decision.decisionContractId},reasonCodes:decision.reasonCodes,evidenceReferences:evidence.map((item)=>`evidence:${item.evidenceId}`),occurredAt:decision.decidedAt,receivedAt:decision.decidedAt,sequence:head.sequence+1,previousHash:head.eventHash,canonicalization:TRUST_EVENT_CANONICALIZATION,hashAlgorithm:TRUST_EVENT_HASH_ALGORITHM,ordering:{late:false,supersedesEventId:null,providerSequence:null}});const persisted=await repository.apply(contract,decision,event,input.correlationId);if(persisted.status==="CHAIN_CONFLICT")continue;if(persisted.status==="STATE_CONFLICT")throw Object.assign(new Error("Trust state changed after recommendation; evaluate again against the current state."),{status:409,code:"TRUST_STATE_CHANGED"});return {contract,decision,persisted};}throw Object.assign(new Error("Trust State Engine contention exceeded the safe retry limit."),{status:503,code:"TRUST_STATE_CONTENTION"});}
